package fr.xephi.authme.libs.org.mariadb.jdbc;

import fr.xephi.authme.libs.org.mariadb.jdbc.client.ColumnDecoder;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.util.Parameter;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.util.Parameters;
import fr.xephi.authme.libs.org.mariadb.jdbc.codec.NonNullParameter;
import fr.xephi.authme.libs.org.mariadb.jdbc.codec.ParameterWithCal;
import fr.xephi.authme.libs.org.mariadb.jdbc.export.ExceptionFactory;
import fr.xephi.authme.libs.org.mariadb.jdbc.export.Prepare;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.Codec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.BigDecimalCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.BlobCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.BooleanCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.ByteArrayCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.ByteCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.ClobCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.DateCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.DoubleCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.FloatCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.IntCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.LongCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.ReaderCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.ShortCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.StreamCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.StringCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.TimeCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.plugin.codec.TimestampCodec;
import fr.xephi.authme.libs.org.mariadb.jdbc.util.ClientParser;
import fr.xephi.authme.libs.org.mariadb.jdbc.util.ParameterList;
import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLType;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.concurrent.locks.ReentrantLock;

public abstract class BasePreparedStatement extends Statement implements PreparedStatement {
   protected final String sql;
   protected Parameters parameters;
   protected List<Parameters> batchParameters;
   protected Prepare prepareResult = null;
   protected Boolean isCommandInsert = null;

   public BasePreparedStatement(String sql, Connection con, ReentrantLock lock, boolean canUseServerTimeout, boolean canUseServerMaxRows, int autoGeneratedKeys, int resultSetType, int resultSetConcurrency, int defaultFetchSize) {
      super(con, lock, canUseServerTimeout, canUseServerMaxRows, autoGeneratedKeys, resultSetType, resultSetConcurrency, defaultFetchSize);
      this.sql = sql;
   }

   public String toString() {
      StringBuilder sb = new StringBuilder("sql:'" + this.sql + "'");
      sb.append(", parameters:[");

      for(int i = 0; i < this.parameters.size(); ++i) {
         Parameter param = this.parameters.get(i);
         if (param == null) {
            sb.append("null");
         } else {
            sb.append(param.bestEffortStringValue(this.con.getContext()));
         }

         if (i != this.parameters.size() - 1) {
            sb.append(",");
         }
      }

      sb.append("]");
      return sb.toString();
   }

   protected void checkIfInsertCommand() {
      if (this.isCommandInsert == null) {
         if (this.sql == null) {
            this.isCommandInsert = false;
         } else {
            ClientParser parser = ClientParser.parameterParts(this.sql, (this.con.getContext().getServerStatus() & 512) > 0);
            this.isInsertDuplicate = parser.isInsertDuplicate();
            this.isCommandInsert = parser.isInsert() && !this.isInsertDuplicate;
         }
      }

   }

   public String getLastSql() {
      return this.sql;
   }

   public void setPrepareResult(Prepare prepareResult) {
      this.prepareResult = prepareResult;
   }

   public ColumnDecoder[] getMeta() {
      return this.prepareResult.getColumns();
   }

   public void updateMeta(ColumnDecoder[] ci) {
      this.prepareResult.setColumns(ci);
   }

   public abstract boolean execute() throws SQLException;

   public abstract ResultSet executeQuery() throws SQLException;

   public abstract int executeUpdate() throws SQLException;

   public abstract long executeLargeUpdate() throws SQLException;

   public abstract void addBatch() throws SQLException;

   public abstract ResultSetMetaData getMetaData() throws SQLException;

   public abstract java.sql.ParameterMetaData getParameterMetaData() throws SQLException;

   public void setParameters(Parameters parameters) {
      this.parameters = parameters;
   }

   public void setParameter(int index, Parameter param) {
      this.parameters.set(index, param);
   }

   public abstract int[] executeBatch() throws SQLException;

   public abstract long[] executeLargeBatch() throws SQLException;

   public void addBatch(String sql) throws SQLException {
      throw this.exceptionFactory().create("addBatch(String sql) cannot be called on preparedStatement");
   }

   public boolean execute(String sql) throws SQLException {
      throw this.exceptionFactory().create("execute(String sql) cannot be called on preparedStatement");
   }

   public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
      throw this.exceptionFactory().create("execute(String sql, int autoGeneratedKeys) cannot be called on preparedStatement");
   }

   public boolean execute(String sql, int[] columnIndexes) throws SQLException {
      throw this.exceptionFactory().create("execute(String sql, int[] columnIndexes) cannot be called on preparedStatement");
   }

   public boolean execute(String sql, String[] columnNames) throws SQLException {
      throw this.exceptionFactory().create("execute(String sql, String[] columnNames) cannot be called on preparedStatement");
   }

   public ResultSet executeQuery(String sql) throws SQLException {
      throw this.exceptionFactory().create("executeQuery(String sql) cannot be called on preparedStatement");
   }

   public int executeUpdate(String sql) throws SQLException {
      throw this.exceptionFactory().create("executeUpdate(String sql) cannot be called on preparedStatement");
   }

   public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
      throw this.exceptionFactory().create("executeUpdate(String sql, int autoGeneratedKeys) cannot be called on preparedStatement");
   }

   public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
      throw this.exceptionFactory().create("executeUpdate(String sql, int[] columnIndexes) cannot be called on preparedStatement");
   }

   public int executeUpdate(String sql, String[] columnNames) throws SQLException {
      throw this.exceptionFactory().create("executeUpdate(String sql, String[] columnNames) cannot be called on preparedStatement");
   }

   public long executeLargeUpdate(String sql) throws SQLException {
      throw this.exceptionFactory().create("executeLargeUpdate(String sql) cannot be called on preparedStatement");
   }

   public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
      throw this.exceptionFactory().create("executeLargeUpdate(String sql, int autoGeneratedKeys) cannot be called on preparedStatement");
   }

   public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
      throw this.exceptionFactory().create("executeLargeUpdate(String sql, int[] columnIndexes) cannot be called on preparedStatement");
   }

   public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
      throw this.exceptionFactory().create("executeLargeUpdate(String sql, String[] columnNames) cannot be called on preparedStatement");
   }

   private void checkIndex(int index) throws SQLException {
      if (index <= 0) {
         throw this.exceptionFactory().create(String.format("wrong parameter index %s", index));
      }
   }

   public void setNull(int parameterIndex, int sqlType) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter.NULL_PARAMETER);
   }

   public void setBoolean(int parameterIndex, boolean x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(BooleanCodec.INSTANCE, x));
   }

   public void setByte(int parameterIndex, byte x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(ByteCodec.INSTANCE, x));
   }

   public void setShort(int parameterIndex, short x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(ShortCodec.INSTANCE, x));
   }

   public void setInt(int parameterIndex, int x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(IntCodec.INSTANCE, x));
   }

   public void setLong(int parameterIndex, long x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(LongCodec.INSTANCE, x));
   }

   public void setFloat(int parameterIndex, float x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(FloatCodec.INSTANCE, x));
   }

   public void setDouble(int parameterIndex, double x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(DoubleCodec.INSTANCE, x));
   }

   public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(BigDecimalCodec.INSTANCE, x));
   }

   public void setString(int parameterIndex, String x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StringCodec.INSTANCE, x));
   }

   public void setBytes(int parameterIndex, byte[] x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ByteArrayCodec.INSTANCE, x));
   }

   public void setDate(int parameterIndex, Date x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(DateCodec.INSTANCE, x));
   }

   public void setTime(int parameterIndex, Time x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(TimeCodec.INSTANCE, x));
   }

   public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(TimestampCodec.INSTANCE, x));
   }

   public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, x, (long)length));
   }

   /** @deprecated */
   @Deprecated
   public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, x, (long)length));
   }

   public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, x, (long)length));
   }

   public void clearParameters() throws SQLException {
      this.checkNotClosed();
      this.parameters = new ParameterList();
   }

   public void clearBatch() throws SQLException {
      this.batchParameters = new ArrayList();
      super.clearBatch();
   }

   public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
      this.setInternalObject(parameterIndex, x, targetSqlType, (Long)null);
   }

   public void setObject(int parameterIndex, Object x) throws SQLException {
      this.setInternalObject(parameterIndex, x, (Integer)null, (Long)null);
   }

   public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, reader, (long)length));
   }

   public void setRef(int parameterIndex, Ref x) throws SQLException {
      throw this.exceptionFactory().notSupported("REF parameter are not supported");
   }

   public void setBlob(int parameterIndex, Blob x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(BlobCodec.INSTANCE, x));
   }

   public void setClob(int parameterIndex, Clob x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ClobCodec.INSTANCE, x));
   }

   public void setArray(int parameterIndex, Array x) throws SQLException {
      throw this.exceptionFactory().notSupported("Array parameter are not supported");
   }

   public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new ParameterWithCal(DateCodec.INSTANCE, x, cal));
   }

   public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new ParameterWithCal(TimeCodec.INSTANCE, x, cal));
   }

   public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new ParameterWithCal(TimestampCodec.INSTANCE, x, cal));
   }

   public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter.NULL_PARAMETER);
   }

   public void setURL(int parameterIndex, URL x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StringCodec.INSTANCE, x == null ? null : x.toString()));
   }

   public void setRowId(int parameterIndex, RowId x) throws SQLException {
      throw this.exceptionFactory().notSupported("RowId parameter are not supported");
   }

   public void setNString(int parameterIndex, String value) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StringCodec.INSTANCE, value));
   }

   public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, value, length));
   }

   public void setNClob(int parameterIndex, NClob value) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ClobCodec.INSTANCE, value));
   }

   public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, reader, length));
   }

   public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, inputStream, length));
   }

   public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, reader, length));
   }

   public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
      throw this.exceptionFactory().notSupported("SQLXML parameter are not supported");
   }

   private ExceptionFactory exceptionFactory() {
      return this.con.getExceptionFactory().of(this);
   }

   public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
      this.setInternalObject(parameterIndex, x, targetSqlType, (long)scaleOrLength);
   }

   private void setInternalObject(int parameterIndex, Object obj, Integer targetSqlType, Long scaleOrLength) throws SQLException {
      this.checkIndex(parameterIndex);
      if (obj == null) {
         this.parameters.set(parameterIndex - 1, fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter.NULL_PARAMETER);
      } else {
         if (targetSqlType != null) {
            switch(targetSqlType) {
            case -8:
            case 70:
            case 2000:
            case 2002:
            case 2003:
            case 2006:
            case 2009:
               throw this.exceptionFactory().notSupported("Type not supported");
            default:
               label182: {
                  if (!(obj instanceof String) && !(obj instanceof Character)) {
                     if (obj instanceof Number) {
                        Number bd = (Number)obj;
                        switch(targetSqlType) {
                        case -7:
                           this.setBoolean(parameterIndex, bd.shortValue() != 0);
                           return;
                        case -6:
                           this.setByte(parameterIndex, bd.byteValue());
                           return;
                        case -5:
                           this.setLong(parameterIndex, bd.longValue());
                           return;
                        case -4:
                        case -3:
                        case -2:
                        case -1:
                        case 0:
                        case 9:
                        case 10:
                        case 11:
                        default:
                           throw this.exceptionFactory().create(String.format("Could not convert [%s] to %s", bd, targetSqlType));
                        case 1:
                        case 12:
                           this.setString(parameterIndex, bd.toString());
                           return;
                        case 2:
                        case 3:
                           if (obj instanceof BigDecimal) {
                              this.setBigDecimal(parameterIndex, (BigDecimal)obj);
                           } else if (!(obj instanceof Double) && !(obj instanceof Float)) {
                              this.setLong(parameterIndex, bd.longValue());
                           } else {
                              this.setDouble(parameterIndex, bd.doubleValue());
                           }

                           return;
                        case 4:
                           this.setInt(parameterIndex, bd.intValue());
                           return;
                        case 5:
                           this.setShort(parameterIndex, bd.shortValue());
                           return;
                        case 6:
                        case 8:
                           this.setDouble(parameterIndex, bd.doubleValue());
                           return;
                        case 7:
                           this.setFloat(parameterIndex, bd.floatValue());
                           return;
                        }
                     }

                     if (!(obj instanceof byte[])) {
                        break label182;
                     }

                     if (targetSqlType != -2 && targetSqlType != -3 && targetSqlType != -4) {
                        if (targetSqlType != 2004) {
                           throw this.exceptionFactory().create("Can only convert a byte[] to BINARY, VARBINARY, LONGVARBINARY or BLOB type");
                        }

                        this.setBlob(parameterIndex, (Blob)(new MariaDbBlob((byte[])obj)));
                        break label182;
                     }

                     this.setBytes(parameterIndex, (byte[])obj);
                     return;
                  }

                  if (targetSqlType == 2004) {
                     throw this.exceptionFactory().create(String.format("Cannot convert a %s to a Blob", obj instanceof String ? "string" : "character"));
                  }

                  String str = obj instanceof String ? (String)obj : ((Character)obj).toString();

                  try {
                     switch(targetSqlType) {
                     case -16:
                     case -15:
                     case -9:
                     case -1:
                     case 1:
                     case 12:
                     case 2005:
                     case 2011:
                        this.setString(parameterIndex, str);
                        return;
                     case -7:
                     case 16:
                        this.setBoolean(parameterIndex, !"false".equalsIgnoreCase(str) && !"0".equals(str));
                        return;
                     case -6:
                        this.setByte(parameterIndex, Byte.parseByte(str));
                        return;
                     case -5:
                        this.setLong(parameterIndex, Long.parseLong(str));
                        return;
                     case 2:
                     case 3:
                        this.setBigDecimal(parameterIndex, new BigDecimal(str));
                        return;
                     case 4:
                        this.setInt(parameterIndex, Integer.parseInt(str));
                        return;
                     case 5:
                        this.setShort(parameterIndex, Short.parseShort(str));
                        return;
                     case 6:
                     case 8:
                        this.setDouble(parameterIndex, Double.parseDouble(str));
                        return;
                     case 7:
                        this.setFloat(parameterIndex, Float.parseFloat(str));
                        return;
                     case 92:
                        this.setTime(parameterIndex, Time.valueOf(str));
                        return;
                     case 93:
                        if (str.startsWith("0000-00-00")) {
                           this.setTimestamp(parameterIndex, (Timestamp)null);
                        } else {
                           this.setTimestamp(parameterIndex, Timestamp.valueOf(str));
                        }

                        return;
                     default:
                        throw this.exceptionFactory().create(String.format("Could not convert [%s] to %s", str, targetSqlType));
                     }
                  } catch (IllegalArgumentException var10) {
                     throw this.exceptionFactory().create(String.format("Could not convert [%s] to java.sql.Type %s", str, targetSqlType), "HY000", var10);
                  }
               }
            }
         }

         Codec[] var11 = this.con.getContext().getConf().codecs();
         int var6 = var11.length;

         for(int var7 = 0; var7 < var6; ++var7) {
            Codec<?> codec = var11[var7];
            if (codec.canEncode(obj)) {
               fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter p = new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(codec, obj, scaleOrLength);
               this.parameters.set(parameterIndex - 1, p);
               return;
            }
         }

         throw new SQLException(String.format("Type %s not supported type", obj.getClass().getName()));
      }
   }

   public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, x, length));
   }

   public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, x, length));
   }

   public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, reader, length));
   }

   public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, x));
   }

   public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, x));
   }

   public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, reader));
   }

   public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, value));
   }

   public void setClob(int parameterIndex, Reader reader) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, reader));
   }

   public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(StreamCodec.INSTANCE, inputStream));
   }

   public void setNClob(int parameterIndex, Reader reader) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new fr.xephi.authme.libs.org.mariadb.jdbc.codec.Parameter(ReaderCodec.INSTANCE, reader));
   }

   public void setObject(int parameterIndex, Object x, SQLType targetSqlType, int scaleOrLength) throws SQLException {
      this.setInternalObject(parameterIndex, x, targetSqlType == null ? null : targetSqlType.getVendorTypeNumber(), (long)scaleOrLength);
   }

   public void setObject(int parameterIndex, Object x, SQLType targetSqlType) throws SQLException {
      this.setInternalObject(parameterIndex, x, targetSqlType == null ? null : targetSqlType.getVendorTypeNumber(), (Long)null);
   }
}
