package fr.xephi.authme.libs.org.mariadb.jdbc;

import fr.xephi.authme.libs.org.mariadb.jdbc.client.ColumnDecoder;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.Completion;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.result.CompleteResult;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.result.Result;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.util.Parameters;
import fr.xephi.authme.libs.org.mariadb.jdbc.export.ExceptionFactory;
import fr.xephi.authme.libs.org.mariadb.jdbc.export.Prepare;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.ClientMessage;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.client.BulkExecutePacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.client.PreparePacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.client.QueryWithParametersPacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.server.OkPacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.server.PrepareResultPacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.util.ClientParser;
import fr.xephi.authme.libs.org.mariadb.jdbc.util.ParameterList;
import java.io.InputStream;
import java.sql.BatchUpdateException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.locks.ReentrantLock;

public class ClientPreparedStatement extends BasePreparedStatement {
   private final ClientParser parser;

   public ClientPreparedStatement(String sql, Connection con, ReentrantLock lock, boolean canUseServerTimeout, boolean canUseServerMaxRows, int autoGeneratedKeys, int resultSetType, int resultSetConcurrency, int defaultFetchSize) {
      super(sql, con, lock, canUseServerTimeout, canUseServerMaxRows, autoGeneratedKeys, resultSetType, resultSetConcurrency, defaultFetchSize);
      boolean noBackslashEscapes = (con.getContext().getServerStatus() & 512) > 0;
      this.parser = ClientParser.parameterParts(sql, noBackslashEscapes);
      this.isInsertDuplicate = this.parser.isInsertDuplicate();
      this.isCommandInsert = this.parser.isInsert() && !this.isInsertDuplicate;
      this.parameters = new ParameterList(this.parser.getParamCount());
   }

   protected String preSqlCmd() {
      return this.queryTimeout != 0 && this.canUseServerTimeout ? "SET STATEMENT max_statement_time=" + this.queryTimeout + " FOR " : null;
   }

   private void executeInternal() throws SQLException {
      this.checkNotClosed();
      this.validParameters();
      this.lock.lock();

      try {
         QueryWithParametersPacket query = new QueryWithParametersPacket(this.preSqlCmd(), this.parser, this.parameters, this.localInfileInputStream);
         this.results = this.con.getClient().execute(query, this, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion, false);
      } catch (SQLException var5) {
         this.results = null;
         this.currResult = null;
         throw var5;
      } finally {
         this.localInfileInputStream = null;
         this.lock.unlock();
      }

   }

   private boolean executeInternalPreparedBatch() throws SQLException {
      this.checkNotClosed();
      this.checkIfInsertCommand();
      Configuration conf = this.con.getContext().getConf();
      if (this.con.getContext().hasServerCapability(17179869184L) && (this.isCommandInsert && (conf.useBulkStmts() || conf.useBulkStmtsForInserts()) || !this.isCommandInsert && conf.useBulkStmts()) && this.batchParameters.size() > 1 && this.autoGeneratedKeys != 1) {
         this.executeBatchBulk();
         return this.isCommandInsert;
      } else {
         boolean possibleLoadLocal = this.con.getContext().hasClientCapability(128L);
         if (possibleLoadLocal) {
            String sqlUpper = this.sql.toUpperCase(Locale.ROOT);
            possibleLoadLocal = sqlUpper.contains(" LOCAL ") && sqlUpper.contains("LOAD") && sqlUpper.contains(" INFILE");
         }

         if (possibleLoadLocal) {
            this.executeBatchStd();
         } else {
            this.executeBatchPipeline();
         }

         return false;
      }
   }

   private void executeBatchBulk() throws SQLException {
      String cmd = this.escapeTimeout(this.sql);

      try {
         if (this.prepareResult == null) {
            ClientMessage[] packets = new ClientMessage[]{new PreparePacket(cmd), new BulkExecutePacket((Prepare)null, this.batchParameters, cmd, (ServerPreparedStatement)null)};
            List<Completion> res = this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
            if (res.get(0) instanceof PrepareResultPacket) {
               this.results = res.subList(1, res.size());
            } else {
               this.results = res;
            }
         } else {
            this.results = this.con.getClient().execute(new BulkExecutePacket(this.prepareResult, this.batchParameters, cmd, (ServerPreparedStatement)null), this, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion, false);
         }

      } catch (SQLException var4) {
         this.results = null;
         throw this.exceptionFactory().createBatchUpdate(Collections.emptyList(), this.batchParameters.size(), var4);
      }
   }

   private void executeBatchPipeline() throws SQLException {
      ClientMessage[] packets = new ClientMessage[this.batchParameters.size()];

      for(int i = 0; i < this.batchParameters.size(); ++i) {
         packets[i] = new QueryWithParametersPacket(this.preSqlCmd(), this.parser, (Parameters)this.batchParameters.get(i), (InputStream)null);
      }

      try {
         this.results = this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
      } catch (SQLException var3) {
         this.results = null;
         throw var3;
      }
   }

   private void executeBatchStd() throws SQLException {
      int i = 0;

      try {
         for(this.results = new ArrayList(); i < this.batchParameters.size(); ++i) {
            this.results.addAll(this.con.getClient().execute(new QueryWithParametersPacket(this.preSqlCmd(), this.parser, (Parameters)this.batchParameters.get(i), this.localInfileInputStream), this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false));
         }

      } catch (SQLException var4) {
         BatchUpdateException exception = this.exceptionFactory().createBatchUpdate(this.results, this.batchParameters.size(), var4);
         this.results = null;
         this.localInfileInputStream = null;
         throw exception;
      }
   }

   public boolean execute() throws SQLException {
      this.executeInternal();
      this.currResult = (Completion)this.results.remove(0);
      return this.currResult instanceof Result;
   }

   public ResultSet executeQuery() throws SQLException {
      this.executeInternal();
      this.currResult = (Completion)this.results.remove(0);
      return (ResultSet)(this.currResult instanceof Result ? (Result)this.currResult : new CompleteResult(new ColumnDecoder[0], new byte[0][], this.con.getContext(), this.resultSetType));
   }

   public int executeUpdate() throws SQLException {
      return (int)this.executeLargeUpdate();
   }

   public long executeLargeUpdate() throws SQLException {
      this.executeInternal();
      this.currResult = (Completion)this.results.remove(0);
      if (this.currResult instanceof Result) {
         throw this.exceptionFactory().create("the given SQL statement produces an unexpected ResultSet object", "HY000");
      } else {
         return ((OkPacket)this.currResult).getAffectedRows();
      }
   }

   private ExceptionFactory exceptionFactory() {
      return this.con.getExceptionFactory().of(this);
   }

   public void addBatch() throws SQLException {
      this.validParameters();
      if (this.batchParameters == null) {
         this.batchParameters = new ArrayList();
      }

      this.batchParameters.add(this.parameters);
      this.parameters = this.parameters.clone();
   }

   protected void validParameters() throws SQLException {
      for(int i = 0; i < this.parser.getParamCount(); ++i) {
         if (!this.parameters.containsKey(i)) {
            throw this.exceptionFactory().create("Parameter at position " + (i + 1) + " is not set", "07004");
         }
      }

   }

   public void setQueryTimeout(int seconds) throws SQLException {
      super.setQueryTimeout(seconds);
      if (this.canUseServerTimeout && this.prepareResult != null) {
         this.prepareResult.close(this.con.getClient());
         this.prepareResult = null;
      }

   }

   public void setMaxRows(int max) throws SQLException {
      super.setMaxRows(max);
      if (this.canUseServerMaxRows && this.prepareResult != null) {
         this.prepareResult.close(this.con.getClient());
         this.prepareResult = null;
      }

   }

   public void setLargeMaxRows(long max) throws SQLException {
      super.setLargeMaxRows(max);
      if (this.canUseServerMaxRows && this.prepareResult != null) {
         this.prepareResult.close(this.con.getClient());
         this.prepareResult = null;
      }

   }

   public ResultSetMetaData getMetaData() throws SQLException {
      if (this.prepareResult == null) {
         this.con.getClient().execute(new PreparePacket(this.escapeTimeout(this.sql)), this, true);
      }

      return new fr.xephi.authme.libs.org.mariadb.jdbc.client.result.ResultSetMetaData(this.exceptionFactory(), this.prepareResult.getColumns(), this.con.getContext().getConf(), false);
   }

   public java.sql.ParameterMetaData getParameterMetaData() throws SQLException {
      if (this.prepareResult == null) {
         try {
            this.con.getClient().execute(new PreparePacket(this.escapeTimeout(this.sql)), this, true);
         } catch (SQLException var2) {
            return new SimpleParameterMetaData(this.exceptionFactory(), this.parser.getParamCount());
         }
      }

      return new ParameterMetaData(this.exceptionFactory(), this.prepareResult.getParameters());
   }

   public int[] executeBatch() throws SQLException {
      this.checkNotClosed();
      if (this.batchParameters != null && !this.batchParameters.isEmpty()) {
         this.lock.lock();

         int[] var11;
         try {
            boolean wasBulkInsert = this.executeInternalPreparedBatch();
            int[] updates = new int[this.batchParameters.size()];
            int i;
            if (wasBulkInsert) {
               i = 0;
               int i = 0;

               while(true) {
                  if (i >= this.results.size()) {
                     if (i == updates.length) {
                        Arrays.fill(updates, 1);
                        this.currResult = (Completion)this.results.remove(0);
                        int[] var10 = updates;
                        return var10;
                     }
                     break;
                  }

                  i += (int)((OkPacket)this.results.get(i)).getAffectedRows();
                  ++i;
               }
            }

            if (this.results.size() != this.batchParameters.size()) {
               for(i = 0; i < this.batchParameters.size(); ++i) {
                  updates[i] = -2;
               }
            } else {
               for(i = 0; i < updates.length; ++i) {
                  if (this.results.get(i) instanceof OkPacket) {
                     updates[i] = (int)((OkPacket)this.results.get(i)).getAffectedRows();
                  } else {
                     updates[i] = -2;
                  }
               }
            }

            this.currResult = (Completion)this.results.remove(0);
            var11 = updates;
         } catch (SQLException var8) {
            this.results = null;
            this.currResult = null;
            throw var8;
         } finally {
            this.batchParameters.clear();
            this.lock.unlock();
         }

         return var11;
      } else {
         return new int[0];
      }
   }

   public long[] executeLargeBatch() throws SQLException {
      this.checkNotClosed();
      if (this.batchParameters != null && !this.batchParameters.isEmpty()) {
         this.lock.lock();

         try {
            boolean wasBulkInsert = this.executeInternalPreparedBatch();
            long[] updates = new long[this.results.size()];
            int numberOfResult;
            if (wasBulkInsert) {
               numberOfResult = 0;
               int i = 0;

               while(true) {
                  if (i >= this.results.size()) {
                     if (numberOfResult == updates.length) {
                        Arrays.fill(updates, 1L);
                        this.currResult = (Completion)this.results.remove(0);
                        long[] var11 = updates;
                        return var11;
                     }
                     break;
                  }

                  numberOfResult += (int)((OkPacket)this.results.get(i)).getAffectedRows();
                  ++i;
               }
            }

            for(numberOfResult = 0; numberOfResult < this.results.size(); ++numberOfResult) {
               updates[numberOfResult] = ((OkPacket)this.results.get(numberOfResult)).getAffectedRows();
            }

            this.currResult = (Completion)this.results.remove(0);
            long[] var10 = updates;
            return var10;
         } catch (SQLException var8) {
            this.results = null;
            this.currResult = null;
            throw var8;
         } finally {
            this.batchParameters.clear();
            this.lock.unlock();
         }
      } else {
         return new long[0];
      }
   }

   public void close() throws SQLException {
      if (this.prepareResult != null) {
         this.lock.lock();

         try {
            this.prepareResult.close(this.con.getClient());
         } finally {
            this.lock.unlock();
         }
      }

      this.con.fireStatementClosed(this);
      super.close();
   }

   public String toString() {
      return "ClientPreparedStatement{" + super.toString() + '}';
   }
}
