package fr.xephi.authme.libs.org.mariadb.jdbc;

import fr.xephi.authme.libs.org.mariadb.jdbc.client.ColumnDecoder;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.Completion;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.result.CompleteResult;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.result.Result;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.util.Parameters;
import fr.xephi.authme.libs.org.mariadb.jdbc.export.ExceptionFactory;
import fr.xephi.authme.libs.org.mariadb.jdbc.export.Prepare;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.ClientMessage;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.client.BulkExecutePacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.client.ExecutePacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.client.PrepareExecutePacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.client.PreparePacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.server.OkPacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.server.PrepareResultPacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.util.ParameterList;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.locks.ReentrantLock;
import java.util.regex.Pattern;

public class ServerPreparedStatement extends BasePreparedStatement {
   private static final Pattern PREPARABLE_STATEMENT_PATTERN = Pattern.compile("^(SELECT|UPDATE|INSERT|DELETE|REPLACE|DO|CALL)", 2);
   private final boolean canCachePrepStmts;

   public ServerPreparedStatement(String sql, Connection con, ReentrantLock lock, boolean canUseServerTimeout, boolean canUseServerMaxRows, boolean canCachePrepStmts, int autoGeneratedKeys, int resultSetType, int resultSetConcurrency, int defaultFetchSize) throws SQLException {
      super(sql, con, lock, canUseServerTimeout, canUseServerMaxRows, autoGeneratedKeys, resultSetType, resultSetConcurrency, defaultFetchSize);
      this.canCachePrepStmts = canCachePrepStmts;
      this.prepareResult = canCachePrepStmts ? con.getContext().getPrepareCache().get(sql, this) : null;
      if (this.prepareResult == null && !PREPARABLE_STATEMENT_PATTERN.matcher(sql).find()) {
         con.getClient().execute(new PreparePacket(sql), this, true);
      }

      this.parameters = new ParameterList();
   }

   protected void executeInternal() throws SQLException {
      this.checkNotClosed();
      this.validParameters();
      this.lock.lock();
      String cmd = this.escapeTimeout(this.sql);
      if (this.prepareResult == null && this.canCachePrepStmts) {
         this.prepareResult = this.con.getContext().getPrepareCache().get(cmd, this);
      }

      try {
         if (this.prepareResult == null && this.con.getContext().permitPipeline()) {
            this.executePipeline(cmd);
         } else {
            this.executeStandard(cmd);
         }
      } catch (SQLException var6) {
         this.results = null;
         this.currResult = null;
         throw var6;
      } finally {
         this.localInfileInputStream = null;
         this.lock.unlock();
      }

   }

   private void executePipeline(String cmd) throws SQLException {
      try {
         List<Completion> res = this.con.getClient().execute(new PrepareExecutePacket(cmd, this.parameters, this, this.localInfileInputStream), this, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion, false);
         this.results = res.subList(1, res.size());
      } catch (SQLException var3) {
         this.results = null;
         throw var3;
      }
   }

   private void executeStandard(String cmd) throws SQLException {
      if (this.prepareResult == null) {
         if (this.canCachePrepStmts) {
            this.prepareResult = this.con.getContext().getPrepareCache().get(cmd, this);
         }

         if (this.prepareResult == null) {
            this.con.getClient().execute(new PreparePacket(cmd), this, true);
         }
      }

      this.validParameters();
      ExecutePacket execute = new ExecutePacket(this.prepareResult, this.parameters, cmd, this, this.localInfileInputStream);
      this.results = this.con.getClient().execute(execute, this, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion, false);
   }

   private boolean executeInternalPreparedBatch() throws SQLException {
      this.checkNotClosed();
      String cmd = this.escapeTimeout(this.sql);
      if (this.batchParameters.size() > 1 && this.con.getContext().hasServerCapability(17179869184L)) {
         boolean possibleLoadLocal = this.con.getContext().hasClientCapability(128L);
         if (possibleLoadLocal) {
            String sqlUpper = this.sql.toUpperCase(Locale.ROOT);
            possibleLoadLocal = sqlUpper.contains(" LOCAL ") && sqlUpper.contains("LOAD") && sqlUpper.contains(" INFILE");
         }

         if (!possibleLoadLocal) {
            Configuration conf = this.con.getContext().getConf();
            this.checkIfInsertCommand();
            if ((this.isCommandInsert && (conf.useBulkStmts() || conf.useBulkStmtsForInserts()) || !this.isCommandInsert && conf.useBulkStmts()) && this.autoGeneratedKeys != 1) {
               this.executeBatchBulk(cmd);
               return this.isCommandInsert;
            }

            this.executeBatchPipeline(cmd);
            return false;
         }
      }

      this.executeBatchStandard(cmd);
      return false;
   }

   private void executeBatchBulk(String cmd) throws SQLException {
      if (this.prepareResult == null && this.canCachePrepStmts) {
         this.prepareResult = this.con.getContext().getPrepareCache().get(cmd, this);
      }

      try {
         if (this.prepareResult == null) {
            ClientMessage[] packets = new ClientMessage[]{new PreparePacket(cmd), new BulkExecutePacket((Prepare)null, this.batchParameters, cmd, this)};
            List<Completion> res = this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
            if (res.get(0) instanceof PrepareResultPacket) {
               this.results = res.subList(1, res.size());
            } else {
               this.results = res;
            }
         } else {
            this.results = this.con.getClient().execute(new BulkExecutePacket(this.prepareResult, this.batchParameters, cmd, this), this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
         }

      } catch (SQLException var4) {
         this.results = null;
         throw this.exceptionFactory().createBatchUpdate(Collections.emptyList(), this.batchParameters.size(), var4);
      }
   }

   private void executeBatchPipeline(String cmd) throws SQLException {
      if (this.prepareResult == null && this.canCachePrepStmts) {
         this.prepareResult = this.con.getContext().getPrepareCache().get(cmd, this);
      }

      int maxCmd = 250;
      ArrayList res = new ArrayList();

      try {
         int index = 0;
         if (this.prepareResult == null) {
            res.addAll(this.executeBunchPrepare(cmd, index, maxCmd));
            index += maxCmd;
         }

         while(index < this.batchParameters.size()) {
            res.addAll(this.executeBunch(cmd, index, maxCmd));
            index += maxCmd;
         }

         this.results = res;
      } catch (SQLException var5) {
         this.results = null;
         throw this.exceptionFactory().createBatchUpdate(res, this.batchParameters.size(), var5);
      }
   }

   private List<Completion> executeBunch(String cmd, int index, int maxCmd) throws SQLException {
      int maxCmdToSend = Math.min(this.batchParameters.size() - index, maxCmd);
      ClientMessage[] packets = new ClientMessage[maxCmdToSend];

      for(int i = index; i < index + maxCmdToSend; ++i) {
         packets[i - index] = new ExecutePacket(this.prepareResult, (Parameters)this.batchParameters.get(i), cmd, this, this.localInfileInputStream);
      }

      return this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
   }

   private List<Completion> executeBunchPrepare(String cmd, int index, int maxCmd) throws SQLException {
      int maxCmdToSend = Math.min(this.batchParameters.size() - index, maxCmd);
      ClientMessage[] packets = new ClientMessage[maxCmdToSend + 1];
      packets[0] = new PreparePacket(cmd);

      for(int i = index; i < index + maxCmdToSend; ++i) {
         packets[i + 1 - index] = new ExecutePacket((Prepare)null, (Parameters)this.batchParameters.get(i), cmd, this, this.localInfileInputStream);
      }

      List<Completion> res = this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
      return res.get(0) instanceof PrepareResultPacket ? res.subList(1, res.size()) : res;
   }

   private void executeBatchStandard(String cmd) throws SQLException {
      List<Completion> tmpResults = new ArrayList();
      SQLException error = null;
      Iterator var4 = this.batchParameters.iterator();

      while(var4.hasNext()) {
         Parameters batchParameter = (Parameters)var4.next();
         if (this.prepareResult == null) {
            if (this.canCachePrepStmts) {
               this.prepareResult = this.con.getContext().getPrepareCache().get(cmd, this);
            }

            if (this.prepareResult == null) {
               this.con.getClient().execute(new PreparePacket(cmd), this, false);
            }
         }

         try {
            ExecutePacket execute = new ExecutePacket(this.prepareResult, batchParameter, cmd, this, this.localInfileInputStream);
            tmpResults.addAll(this.con.getClient().execute(execute, this, false));
         } catch (SQLException var7) {
            if (error == null) {
               error = var7;
            }
         }
      }

      if (error != null) {
         throw this.exceptionFactory().createBatchUpdate(tmpResults, this.batchParameters.size(), error);
      } else {
         this.results = tmpResults;
      }
   }

   public boolean execute() throws SQLException {
      this.executeInternal();
      this.handleParameterOutput();
      if (this.results.size() > 0) {
         this.currResult = (Completion)this.results.remove(0);
         return this.currResult instanceof Result;
      } else {
         return false;
      }
   }

   public void setMaxRows(int max) throws SQLException {
      super.setMaxRows(max);
      if (this.canUseServerMaxRows && this.prepareResult != null) {
         this.prepareResult.decrementUse(this.con.getClient(), this);
         this.prepareResult = null;
      }

   }

   public void setLargeMaxRows(long max) throws SQLException {
      super.setLargeMaxRows(max);
      if (this.canUseServerMaxRows && this.prepareResult != null) {
         this.prepareResult.decrementUse(this.con.getClient(), this);
         this.prepareResult = null;
      }

   }

   public void setQueryTimeout(int seconds) throws SQLException {
      super.setQueryTimeout(seconds);
      if (this.canUseServerTimeout && this.prepareResult != null) {
         this.prepareResult.decrementUse(this.con.getClient(), this);
         this.prepareResult = null;
      }

   }

   public ResultSet executeQuery() throws SQLException {
      this.executeInternal();
      this.handleParameterOutput();
      if (this.results.size() > 0) {
         this.currResult = (Completion)this.results.remove(0);
         if (this.currResult instanceof Result) {
            return (Result)this.currResult;
         }
      }

      return new CompleteResult(new ColumnDecoder[0], new byte[0][], this.con.getContext(), this.resultSetType);
   }

   public int executeUpdate() throws SQLException {
      return (int)this.executeLargeUpdate();
   }

   public long executeLargeUpdate() throws SQLException {
      this.executeInternal();
      this.handleParameterOutput();
      this.currResult = (Completion)this.results.remove(0);
      if (this.currResult instanceof Result) {
         throw this.exceptionFactory().create("the given SQL statement produces an unexpected ResultSet object", "HY000");
      } else {
         return ((OkPacket)this.currResult).getAffectedRows();
      }
   }

   protected void handleParameterOutput() throws SQLException {
   }

   public void addBatch() throws SQLException {
      this.validParameters();
      if (this.batchParameters == null) {
         this.batchParameters = new ArrayList();
      }

      this.batchParameters.add(this.parameters);
      this.parameters = this.parameters.clone();
   }

   protected void validParameters() throws SQLException {
      int i;
      if (this.prepareResult != null) {
         for(i = 0; i < this.prepareResult.getParameters().length; ++i) {
            if (!this.parameters.containsKey(i)) {
               throw this.exceptionFactory().create("Parameter at position " + (i + 1) + " is not set", "07004");
            }
         }
      } else {
         if (this.batchParameters != null && !this.batchParameters.isEmpty() && this.parameters.size() < ((Parameters)this.batchParameters.get(0)).size()) {
            throw this.exceptionFactory().create("batch set of parameters differ from previous set. All parameters must be set", "07004");
         }

         for(i = 0; i < this.parameters.size(); ++i) {
            if (!this.parameters.containsKey(i)) {
               throw this.exceptionFactory().create("Parameter at position " + (i + 1) + " is not set", "07004");
            }
         }
      }

   }

   public ResultSetMetaData getMetaData() throws SQLException {
      if (this.prepareResult == null) {
         this.con.getClient().execute(new PreparePacket(this.escapeTimeout(this.sql)), this, true);
      }

      return new fr.xephi.authme.libs.org.mariadb.jdbc.client.result.ResultSetMetaData(this.exceptionFactory(), this.prepareResult.getColumns(), this.con.getContext().getConf(), false);
   }

   public java.sql.ParameterMetaData getParameterMetaData() throws SQLException {
      if (this.prepareResult == null) {
         this.con.getClient().execute(new PreparePacket(this.escapeTimeout(this.sql)), this, true);
      }

      return new ParameterMetaData(this.exceptionFactory(), this.prepareResult.getParameters());
   }

   public int[] executeBatch() throws SQLException {
      this.checkNotClosed();
      if (this.batchParameters != null && !this.batchParameters.isEmpty()) {
         this.lock.lock();

         try {
            boolean wasBulkInsert = this.executeInternalPreparedBatch();
            int[] updates = new int[this.batchParameters.size()];
            int i;
            if (wasBulkInsert) {
               i = 0;
               int i = 0;

               while(true) {
                  if (i >= this.results.size()) {
                     if (i == updates.length) {
                        Arrays.fill(updates, 1);
                        this.currResult = (Completion)this.results.remove(0);
                        int[] var10 = updates;
                        return var10;
                     }
                     break;
                  }

                  i += (int)((OkPacket)this.results.get(i)).getAffectedRows();
                  ++i;
               }
            }

            if (this.results.size() != updates.length) {
               for(i = 0; i < updates.length; ++i) {
                  updates[i] = -2;
               }
            } else {
               for(i = 0; i < updates.length; ++i) {
                  if (this.results.get(i) instanceof OkPacket) {
                     updates[i] = (int)((OkPacket)this.results.get(i)).getAffectedRows();
                  } else {
                     updates[i] = -2;
                  }
               }
            }

            this.currResult = (Completion)this.results.remove(0);
            int[] var11 = updates;
            return var11;
         } catch (SQLException var8) {
            this.results = null;
            this.currResult = null;
            throw var8;
         } finally {
            this.localInfileInputStream = null;
            this.batchParameters.clear();
            this.lock.unlock();
         }
      } else {
         return new int[0];
      }
   }

   public long[] executeLargeBatch() throws SQLException {
      this.checkNotClosed();
      if (this.batchParameters != null && !this.batchParameters.isEmpty()) {
         this.lock.lock();

         long[] var11;
         try {
            boolean wasBulkInsert = this.executeInternalPreparedBatch();
            long[] updates = new long[this.batchParameters.size()];
            int i;
            if (wasBulkInsert) {
               i = 0;
               int i = 0;

               while(true) {
                  if (i >= this.results.size()) {
                     if (i == updates.length) {
                        Arrays.fill(updates, 1L);
                        this.currResult = (Completion)this.results.remove(0);
                        long[] var10 = updates;
                        return var10;
                     }
                     break;
                  }

                  i += (int)((OkPacket)this.results.get(i)).getAffectedRows();
                  ++i;
               }
            }

            if (this.results.size() != updates.length) {
               for(i = 0; i < updates.length; ++i) {
                  updates[i] = -2L;
               }
            } else {
               for(i = 0; i < updates.length; ++i) {
                  if (this.results.get(i) instanceof OkPacket) {
                     updates[i] = ((OkPacket)this.results.get(i)).getAffectedRows();
                  } else {
                     updates[i] = -2L;
                  }
               }
            }

            this.currResult = (Completion)this.results.remove(0);
            var11 = updates;
         } catch (SQLException var8) {
            this.results = null;
            this.currResult = null;
            throw var8;
         } finally {
            this.batchParameters.clear();
            this.lock.unlock();
         }

         return var11;
      } else {
         return new long[0];
      }
   }

   private ExceptionFactory exceptionFactory() {
      return this.con.getExceptionFactory().of(this);
   }

   public void close() throws SQLException {
      if (this.prepareResult != null) {
         this.prepareResult.decrementUse(this.con.getClient(), this);
         this.prepareResult = null;
      }

      this.con.fireStatementClosed(this);
      super.close();
   }

   public void reset() {
      this.lock.lock();

      try {
         this.prepareResult = null;
      } finally {
         this.lock.unlock();
      }

   }

   public String toString() {
      return "ServerPreparedStatement{" + super.toString() + '}';
   }
}
