package fr.xephi.authme.libs.org.mariadb.jdbc;

import fr.xephi.authme.libs.org.mariadb.jdbc.client.ColumnDecoder;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.Completion;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.DataType;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.result.CompleteResult;
import fr.xephi.authme.libs.org.mariadb.jdbc.client.result.Result;
import fr.xephi.authme.libs.org.mariadb.jdbc.export.ExceptionFactory;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.client.QueryPacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.message.server.OkPacket;
import fr.xephi.authme.libs.org.mariadb.jdbc.util.ClientParser;
import fr.xephi.authme.libs.org.mariadb.jdbc.util.NativeSql;
import java.io.InputStream;
import java.sql.BatchUpdateException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.locks.ReentrantLock;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Statement implements java.sql.Statement {
   private static final Pattern identifierPattern = Pattern.compile("[0-9a-zA-Z$_\\u0080-\\uFFFF]*", 192);
   private static final Pattern escapePattern = Pattern.compile("[\u0000'\"\b\n\r\t\u001a\\\\]");
   private static final Map<String, String> mapper = new HashMap();
   protected final int resultSetType;
   protected final int resultSetConcurrency;
   protected final ReentrantLock lock;
   protected final boolean canUseServerTimeout;
   protected final boolean canUseServerMaxRows;
   protected final Connection con;
   protected Boolean isInsertDuplicate = null;
   protected int queryTimeout;
   protected long maxRows;
   protected String lastSql;
   protected int fetchSize;
   protected int autoGeneratedKeys;
   protected boolean closeOnCompletion;
   protected boolean closed;
   protected boolean escape;
   protected List<Completion> results;
   protected Completion currResult;
   protected InputStream localInfileInputStream;
   private List<String> batchQueries;

   public Statement(Connection con, ReentrantLock lock, boolean canUseServerTimeout, boolean canUseServerMaxRows, int autoGeneratedKeys, int resultSetType, int resultSetConcurrency, int defaultFetchSize) {
      this.con = con;
      this.lock = lock;
      this.resultSetConcurrency = resultSetConcurrency;
      this.resultSetType = resultSetType;
      this.autoGeneratedKeys = autoGeneratedKeys;
      this.canUseServerTimeout = canUseServerTimeout;
      this.canUseServerMaxRows = canUseServerMaxRows;
      this.fetchSize = defaultFetchSize;
   }

   private ExceptionFactory exceptionFactory() {
      return this.con.getExceptionFactory().of(this);
   }

   public void setLocalInfileInputStream(InputStream inputStream) throws SQLException {
      this.checkNotClosed();
      this.localInfileInputStream = inputStream;
   }

   public ResultSet executeQuery(String sql) throws SQLException {
      this.executeInternal(sql, 2);
      this.currResult = (Completion)this.results.remove(0);
      return (ResultSet)(this.currResult instanceof Result ? (Result)this.currResult : new CompleteResult(new ColumnDecoder[0], new byte[0][], this.con.getContext(), this.resultSetType));
   }

   public int executeUpdate(String sql) throws SQLException {
      return this.executeUpdate(sql, 2);
   }

   public void close() throws SQLException {
      if (!this.closed) {
         this.closed = true;
         if (this.currResult != null && this.currResult instanceof Result) {
            ((Result)this.currResult).closeFromStmtClose(this.lock);
         }

         if (this.results != null && !this.results.isEmpty()) {
            Iterator var1 = this.results.iterator();

            while(var1.hasNext()) {
               Completion completion = (Completion)var1.next();
               if (completion instanceof Result) {
                  ((Result)completion).closeFromStmtClose(this.lock);
               }
            }
         }
      }

   }

   public void abort() {
      this.lock.lock();

      try {
         if (!this.closed) {
            this.closed = true;
            if (this.currResult != null && this.currResult instanceof Result) {
               ((Result)this.currResult).abort();
            }

            if (this.results != null) {
               Iterator var1 = this.results.iterator();

               while(var1.hasNext()) {
                  Completion completion = (Completion)var1.next();
                  if (completion instanceof Result) {
                     ((Result)completion).abort();
                  }
               }
            }
         }
      } finally {
         this.lock.unlock();
      }

   }

   public int getMaxFieldSize() {
      return 0;
   }

   public void setMaxFieldSize(int max) {
   }

   public int getMaxRows() throws SQLException {
      this.checkNotClosed();
      return (int)this.maxRows;
   }

   public void setMaxRows(int max) throws SQLException {
      this.checkNotClosed();
      if (max < 0) {
         throw this.exceptionFactory().create("max rows cannot be negative : asked for " + max, "42000");
      } else {
         this.maxRows = (long)max;
      }
   }

   public void setEscapeProcessing(boolean enable) throws SQLException {
      this.checkNotClosed();
      this.escape = enable;
   }

   public int getQueryTimeout() throws SQLException {
      this.checkNotClosed();
      return this.queryTimeout;
   }

   public void setQueryTimeout(int seconds) throws SQLException {
      if (seconds < 0) {
         throw this.exceptionFactory().create("Query timeout cannot be negative : asked for " + seconds, "42000");
      } else {
         this.queryTimeout = seconds;
      }
   }

   public void cancel() throws SQLException {
      this.checkNotClosed();
      boolean locked = this.lock.tryLock();
      if (!locked) {
         this.con.cancelCurrentQuery();
      } else {
         this.lock.unlock();
      }

   }

   public SQLWarning getWarnings() throws SQLException {
      return this.con.getWarnings();
   }

   public void clearWarnings() {
      this.con.getContext().setWarning(0);
   }

   public void setCursorName(String name) throws SQLException {
      throw this.exceptionFactory().notSupported("Cursors are not supported");
   }

   public boolean execute(String sql) throws SQLException {
      return this.execute(sql, 2);
   }

   public ResultSet getResultSet() throws SQLException {
      this.checkNotClosed();
      return this.currResult instanceof Result ? (Result)this.currResult : null;
   }

   public int getUpdateCount() throws SQLException {
      this.checkNotClosed();
      return this.currResult instanceof OkPacket ? (int)((OkPacket)this.currResult).getAffectedRows() : -1;
   }

   public boolean getMoreResults() throws SQLException {
      return this.getMoreResults(1);
   }

   public int getFetchDirection() {
      return 1000;
   }

   public void setFetchDirection(int direction) {
   }

   public int getFetchSize() throws SQLException {
      this.checkNotClosed();
      return this.fetchSize;
   }

   public void setFetchSize(int rows) throws SQLException {
      if (rows < 0) {
         throw this.exceptionFactory().create("invalid fetch size");
      } else {
         this.fetchSize = rows;
      }
   }

   public int getResultSetConcurrency() throws SQLException {
      this.checkNotClosed();
      return this.resultSetConcurrency;
   }

   public int getResultSetType() {
      return this.resultSetType;
   }

   public void addBatch(String sql) throws SQLException {
      if (sql == null) {
         throw this.exceptionFactory().create("null cannot be set to addBatch(String sql)");
      } else {
         if (this.batchQueries == null) {
            this.batchQueries = new ArrayList();
         }

         this.batchQueries.add(this.escape ? NativeSql.parse(sql, this.con.getContext()) : sql);
      }
   }

   public void clearBatch() throws SQLException {
      this.checkNotClosed();
      if (this.batchQueries == null) {
         this.batchQueries = new ArrayList();
      } else {
         this.batchQueries.clear();
      }

   }

   public int[] executeBatch() throws SQLException {
      this.checkNotClosed();
      if (this.batchQueries != null && !this.batchQueries.isEmpty()) {
         this.lock.lock();

         int[] var13;
         try {
            this.lastSql = (String)this.batchQueries.get(0);
            this.autoGeneratedKeys = 1;
            boolean possibleLoadLocal = this.con.getContext().hasClientCapability(128L);
            if (possibleLoadLocal) {
               possibleLoadLocal = false;
               Iterator var2 = this.batchQueries.iterator();

               while(var2.hasNext()) {
                  String batchQuery = (String)var2.next();
                  String sql = batchQuery.toUpperCase(Locale.ROOT);
                  if (sql.contains(" LOCAL ") && sql.contains("LOAD") && sql.contains(" INFILE")) {
                     possibleLoadLocal = true;
                     break;
                  }
               }
            }

            List<Completion> res = possibleLoadLocal ? this.executeInternalBatchStandard() : this.executeInternalBatchPipeline();
            this.results = res;
            int[] updates = new int[res.size()];

            for(int i = 0; i < res.size(); ++i) {
               if (res.get(i) instanceof OkPacket) {
                  updates[i] = (int)((OkPacket)res.get(i)).getAffectedRows();
               } else {
                  updates[i] = -2;
               }
            }

            this.currResult = (Completion)this.results.remove(0);
            var13 = updates;
         } catch (SQLException var8) {
            this.results = null;
            this.currResult = null;
            throw var8;
         } finally {
            this.batchQueries.clear();
            this.lock.unlock();
         }

         return var13;
      } else {
         return new int[0];
      }
   }

   public Connection getConnection() throws SQLException {
      this.checkNotClosed();
      return this.con;
   }

   public boolean getMoreResults(int current) throws SQLException {
      this.checkNotClosed();
      if (this.currResult instanceof ResultSet) {
         this.lock.lock();

         try {
            Result result = (Result)this.currResult;
            if (current == 1) {
               result.close();
            } else {
               result.fetchRemaining();
            }

            if (result.streaming() && (this.con.getContext().getServerStatus() & 8) > 0) {
               this.con.getClient().readStreamingResults(this.results, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion);
            }
         } finally {
            this.lock.unlock();
         }
      }

      if (this.results.size() > 0) {
         this.currResult = (Completion)this.results.remove(0);
         return this.currResult instanceof Result;
      } else {
         this.currResult = null;
         return false;
      }
   }

   public void fetchRemaining() throws SQLException {
      if (this.currResult != null && this.currResult instanceof ResultSet) {
         Result result = (Result)this.currResult;
         result.fetchRemaining();
         if (result.streaming() && (this.con.getContext().getServerStatus() & 8) > 0) {
            this.con.getClient().readStreamingResults(this.results, 0, 0L, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion);
         }
      }

   }

   public ResultSet getGeneratedKeys() throws SQLException {
      this.checkNotClosed();
      if (this.autoGeneratedKeys != 1) {
         throw new SQLException("Cannot return generated keys: query was not set with Statement.RETURN_GENERATED_KEYS");
      } else {
         List<String[]> insertIds = new ArrayList();
         if (this.con.getContext().getConf().returnMultiValuesGeneratedIds() && !this.checkIfInsertDuplicateCommand(this.getLastSql())) {
            long autoIncrement = this.con.getContext().getAutoIncrement();
            if (this.currResult instanceof OkPacket) {
               OkPacket ok = (OkPacket)this.currResult;
               if (ok.getLastInsertId() != 0L) {
                  insertIds.add(new String[]{String.valueOf(ok.getLastInsertId())});
                  if (ok.getAffectedRows() > 1L) {
                     for(int i = 1; (long)i < ok.getAffectedRows(); ++i) {
                        insertIds.add(new String[]{String.valueOf(ok.getLastInsertId() + (long)i * autoIncrement)});
                     }
                  }
               }
            }

            if (this.results != null) {
               Iterator var10 = this.results.iterator();

               label72:
               while(true) {
                  OkPacket ok;
                  do {
                     do {
                        Completion result;
                        do {
                           if (!var10.hasNext()) {
                              break label72;
                           }

                           result = (Completion)var10.next();
                        } while(!(result instanceof OkPacket));

                        ok = (OkPacket)result;
                     } while(ok.getLastInsertId() == 0L);

                     insertIds.add(new String[]{String.valueOf(ok.getLastInsertId())});
                  } while(ok.getAffectedRows() <= 1L);

                  for(int i = 1; (long)i < ok.getAffectedRows(); ++i) {
                     insertIds.add(new String[]{String.valueOf(ok.getLastInsertId() + (long)i * autoIncrement)});
                  }
               }
            }
         } else {
            if (this.currResult instanceof OkPacket && ((OkPacket)this.currResult).getLastInsertId() != 0L) {
               insertIds.add(new String[]{String.valueOf(((OkPacket)this.currResult).getLastInsertId())});
            }

            if (this.results != null) {
               Iterator var2 = this.results.iterator();

               while(var2.hasNext()) {
                  Completion result = (Completion)var2.next();
                  if (result instanceof OkPacket && ((OkPacket)result).getLastInsertId() != 0L) {
                     insertIds.add(new String[]{String.valueOf(((OkPacket)result).getLastInsertId())});
                  }
               }
            }
         }

         if (insertIds.isEmpty()) {
            return new CompleteResult(new ColumnDecoder[0], new byte[0][], this.con.getContext(), this.resultSetType);
         } else {
            String[][] ids = (String[][])insertIds.toArray(new String[0][]);
            return CompleteResult.createResultSet((String)"insert_id", (DataType)DataType.BIGINT, ids, this.con.getContext(), 544, this.resultSetType);
         }
      }
   }

   protected boolean checkIfInsertDuplicateCommand(String sql) {
      if (this.isInsertDuplicate == null) {
         if (sql == null) {
            this.isInsertDuplicate = false;
         } else {
            ClientParser parser = ClientParser.parameterParts(sql, (this.con.getContext().getServerStatus() & 512) > 0);
            this.isInsertDuplicate = parser.isInsertDuplicate();
         }
      }

      return this.isInsertDuplicate;
   }

   public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
      this.executeInternal(sql, autoGeneratedKeys);
      this.currResult = (Completion)this.results.remove(0);
      if (this.currResult instanceof Result) {
         throw this.exceptionFactory().create("the given SQL statement produces an unexpected ResultSet object", "HY000");
      } else {
         return (int)((OkPacket)this.currResult).getAffectedRows();
      }
   }

   private void executeInternal(String sql, int autoGeneratedKeys) throws SQLException {
      this.checkNotClosed();
      this.lock.lock();

      try {
         this.lastSql = sql;
         this.autoGeneratedKeys = autoGeneratedKeys;
         String cmd = this.escapeTimeout(sql);
         this.results = this.con.getClient().execute(new QueryPacket(cmd, this.localInfileInputStream), this, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion, false);
      } catch (SQLException var7) {
         this.results = null;
         this.currResult = null;
         throw var7;
      } finally {
         this.localInfileInputStream = null;
         this.lock.unlock();
      }

   }

   public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
      return this.executeUpdate(sql, 1);
   }

   public int executeUpdate(String sql, String[] columnNames) throws SQLException {
      return this.executeUpdate(sql, 1);
   }

   public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
      this.executeInternal(sql, autoGeneratedKeys);
      this.currResult = (Completion)this.results.remove(0);
      return this.currResult instanceof Result;
   }

   protected String escapeTimeout(String sql) throws SQLException {
      String escapedSql = this.escape ? NativeSql.parse(sql, this.con.getContext()) : sql;
      if (this.queryTimeout != 0 && this.canUseServerTimeout) {
         return this.canUseServerMaxRows && this.maxRows > 0L ? "SET STATEMENT max_statement_time=" + this.queryTimeout + ", SQL_SELECT_LIMIT=" + this.maxRows + " FOR " + escapedSql : "SET STATEMENT max_statement_time=" + this.queryTimeout + " FOR " + escapedSql;
      } else {
         return this.canUseServerMaxRows && this.maxRows > 0L ? "SET STATEMENT SQL_SELECT_LIMIT=" + this.maxRows + " FOR " + escapedSql : escapedSql;
      }
   }

   public boolean execute(String sql, int[] columnIndexes) throws SQLException {
      return this.execute(sql, 1);
   }

   public boolean execute(String sql, String[] columnNames) throws SQLException {
      return this.execute(sql, 1);
   }

   public int getResultSetHoldability() {
      return 1;
   }

   public boolean isClosed() {
      return this.closed;
   }

   public boolean isPoolable() throws SQLException {
      this.checkNotClosed();
      return false;
   }

   public void setPoolable(boolean poolable) throws SQLException {
      this.checkNotClosed();
   }

   public void closeOnCompletion() throws SQLException {
      this.checkNotClosed();
      this.closeOnCompletion = true;
      if (this.results != null && this.results.size() > 0) {
         for(int i = this.results.size(); i > 0; --i) {
            Completion completion = (Completion)this.results.get(i - 1);
            if (completion instanceof Result) {
               ((Result)completion).closeOnCompletion();
               return;
            }
         }
      } else if (this.currResult != null && this.currResult instanceof ResultSet) {
         Result res = (Result)this.currResult;
         if (res.streaming() || res.loaded()) {
            res.closeOnCompletion();
         }
      }

   }

   public boolean isCloseOnCompletion() throws SQLException {
      this.checkNotClosed();
      return this.closeOnCompletion;
   }

   public <T> T unwrap(Class<T> iface) throws SQLException {
      if (this.isWrapperFor(iface)) {
         return this;
      } else {
         throw this.exceptionFactory().create("The receiver is not a wrapper and does not implement the interface", "42000");
      }
   }

   public boolean isWrapperFor(Class<?> iface) {
      return iface == null ? false : iface.isInstance(this);
   }

   protected void checkNotClosed() throws SQLException {
      if (this.closed) {
         throw this.exceptionFactory().create("Cannot do an operation on a closed statement");
      }
   }

   public long executeLargeUpdate(String sql) throws SQLException {
      return this.executeLargeUpdate(sql, 2);
   }

   public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
      this.executeInternal(sql, autoGeneratedKeys);
      this.currResult = (Completion)this.results.remove(0);
      if (this.currResult instanceof Result) {
         throw this.exceptionFactory().create("the given SQL statement produces an unexpected ResultSet object", "HY000");
      } else {
         return ((OkPacket)this.currResult).getAffectedRows();
      }
   }

   public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
      return this.executeLargeUpdate(sql, 1);
   }

   public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
      return this.executeLargeUpdate(sql, 1);
   }

   public long getLargeMaxRows() throws SQLException {
      this.checkNotClosed();
      return this.maxRows;
   }

   public void setLargeMaxRows(long max) throws SQLException {
      this.checkNotClosed();
      if (max < 0L) {
         throw this.exceptionFactory().create("max rows cannot be negative : asked for " + max, "42000");
      } else {
         this.maxRows = max;
      }
   }

   public long getLargeUpdateCount() throws SQLException {
      this.checkNotClosed();
      return this.currResult instanceof OkPacket ? (long)((int)((OkPacket)this.currResult).getAffectedRows()) : -1L;
   }

   public long[] executeLargeBatch() throws SQLException {
      this.checkNotClosed();
      if (this.batchQueries != null && !this.batchQueries.isEmpty()) {
         this.lock.lock();

         try {
            this.lastSql = (String)this.batchQueries.get(0);
            this.autoGeneratedKeys = 1;
            boolean possibleLoadLocal = this.con.getContext().hasClientCapability(128L);
            if (possibleLoadLocal) {
               possibleLoadLocal = false;
               Iterator var2 = this.batchQueries.iterator();

               while(var2.hasNext()) {
                  String batchQuery = (String)var2.next();
                  String sql = batchQuery.toUpperCase(Locale.ROOT);
                  if (sql.contains(" LOCAL ") && sql.contains("LOAD") && sql.contains(" INFILE")) {
                     possibleLoadLocal = true;
                     break;
                  }
               }
            }

            List<Completion> res = possibleLoadLocal ? this.executeInternalBatchStandard() : this.executeInternalBatchPipeline();
            this.results = res;
            long[] updates = new long[res.size()];

            for(int i = 0; i < res.size(); ++i) {
               updates[i] = ((OkPacket)res.get(i)).getAffectedRows();
            }

            this.currResult = (Completion)this.results.remove(0);
            long[] var13 = updates;
            return var13;
         } catch (SQLException var8) {
            this.results = null;
            this.currResult = null;
            throw var8;
         } finally {
            this.batchQueries.clear();
            this.lock.unlock();
         }
      } else {
         return new long[0];
      }
   }

   public List<Completion> executeInternalBatchPipeline() throws SQLException {
      QueryPacket[] packets = new QueryPacket[this.batchQueries.size()];

      for(int i = 0; i < this.batchQueries.size(); ++i) {
         String sql = (String)this.batchQueries.get(i);
         packets[i] = new QueryPacket(sql);
      }

      return this.con.getClient().executePipeline(packets, this, 0, 0L, 1007, 1003, this.closeOnCompletion, false);
   }

   public List<Completion> executeInternalBatchStandard() throws SQLException {
      ArrayList results = new ArrayList();

      try {
         Iterator var2 = this.batchQueries.iterator();

         while(var2.hasNext()) {
            String batchQuery = (String)var2.next();
            results.addAll(this.con.getClient().execute(new QueryPacket(batchQuery, this.localInfileInputStream), this, 0, 0L, 1007, 1003, this.closeOnCompletion, false));
         }

         ArrayList var11 = results;
         return var11;
      } catch (SQLException var9) {
         int[] updateCounts = new int[this.batchQueries.size()];

         for(int i = 0; i < Math.min(results.size(), updateCounts.length); ++i) {
            Completion completion = (Completion)results.get(i);
            updateCounts[i] = completion instanceof OkPacket ? (int)((OkPacket)completion).getAffectedRows() : 0;
         }

         throw new BatchUpdateException(var9.getMessage(), var9.getSQLState(), var9.getErrorCode(), updateCounts, var9);
      } finally {
         this.localInfileInputStream = null;
      }
   }

   public String enquoteLiteral(String val) {
      Matcher matcher = escapePattern.matcher(val);
      StringBuffer escapedVal = new StringBuffer("'");

      while(matcher.find()) {
         matcher.appendReplacement(escapedVal, (String)mapper.get(matcher.group()));
      }

      matcher.appendTail(escapedVal);
      escapedVal.append("'");
      return escapedVal.toString();
   }

   public String enquoteIdentifier(String identifier, boolean alwaysQuote) throws SQLException {
      if (this.isSimpleIdentifier(identifier)) {
         return alwaysQuote ? "`" + identifier + "`" : identifier;
      } else if (identifier.contains("\u0000")) {
         throw this.exceptionFactory().create("Invalid name - containing u0000 character", "42000");
      } else {
         if (identifier.matches("^`.+`$")) {
            identifier = identifier.substring(1, identifier.length() - 1);
         }

         return "`" + identifier.replace("`", "``") + "`";
      }
   }

   public boolean isSimpleIdentifier(String identifier) {
      return identifier != null && !identifier.isEmpty() && identifierPattern.matcher(identifier).matches();
   }

   public String getLastSql() {
      return this.lastSql;
   }

   public String enquoteNCharLiteral(String val) {
      return "N'" + val.replace("'", "''") + "'";
   }

   static {
      mapper.put("\u0000", "\\0");
      mapper.put("'", "\\\\'");
      mapper.put("\"", "\\\\\"");
      mapper.put("\b", "\\\\b");
      mapper.put("\n", "\\\\n");
      mapper.put("\r", "\\\\r");
      mapper.put("\t", "\\\\t");
      mapper.put("\u001a", "\\\\Z");
      mapper.put("\\", "\\\\");
   }
}
