package tntrun.utils;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import tntrun.TNTRun;

public class ShopFiles {
   private final TNTRun plugin;

   public ShopFiles(TNTRun plugin) {
      this.plugin = plugin;
   }

   public File getShopFile() {
      return new File(this.plugin.getDataFolder(), "shop.yml");
   }

   public FileConfiguration getShopConfiguration() {
      return YamlConfiguration.loadConfiguration(this.getShopFile());
   }

   public void setShopItems() {
      if (!this.getShopFile().exists()) {
         FileConfiguration cfg = this.getShopConfiguration();
         cfg.options().copyDefaults(true);
         cfg.addDefault("1.name", "&fDouble Jump");
         cfg.addDefault("1.cost", 100);
         cfg.addDefault("1.material", "FEATHER");
         cfg.addDefault("1.amount", 1);
         cfg.addDefault("1.permission", "tntrun.shop.1");
         List<String> lore = new ArrayList();
         lore.add("Double Jump");
         lore.add("Cost&6 100 &5coins");
         cfg.addDefault("1.lore", lore);
         cfg.addDefault("1.items.1.material", "");
         cfg.addDefault("1.items.1.amount", 1);
         cfg.addDefault("1.items.1.displayname", "&cDouble jump");
         List<String> iLore = new ArrayList();
         iLore.add("Basic kit - double jump");
         cfg.addDefault("1.items.1.lore", iLore);
         List<String> iEnch = new ArrayList();
         iEnch.add("null");
         cfg.addDefault("1.items.1.enchantments", iEnch);
         cfg.addDefault("2.name", "&fSwordsman");
         cfg.addDefault("2.cost", 250);
         cfg.addDefault("2.material", "IRON_SWORD");
         cfg.addDefault("2.glow", false);
         cfg.addDefault("2.amount", 1);
         cfg.addDefault("2.permission", "tntrun.shop.2");
         lore = new ArrayList();
         lore.add("Sword + Knockback#1");
         lore.add("Cost&6 250 &5coins");
         cfg.addDefault("2.lore", lore);
         cfg.addDefault("2.items.1.material", "IRON_SWORD");
         cfg.addDefault("2.items.1.amount", 1);
         cfg.addDefault("2.items.1.displayname", "&cSword + Knockback1");
         iLore = new ArrayList();
         iLore.add("Sword + Knockback#1");
         cfg.addDefault("2.items.1.lore", iLore);
         iEnch = new ArrayList();
         iEnch.add("KNOCKBACK#2");
         iEnch.add("SWEEPING#1");
         cfg.addDefault("2.items.1.enchantments", iEnch);
         cfg.addDefault("3.name", "&fProtection Plus");
         cfg.addDefault("3.cost", 300);
         cfg.addDefault("3.material", "GOLDEN_CHESTPLATE");
         cfg.addDefault("3.glow", false);
         cfg.addDefault("3.amount", 1);
         cfg.addDefault("3.permission", "tntrun.shop.3");
         lore = new ArrayList();
         lore.add("Chestplate + Thorns#1");
         lore.add("Cost&6 300 &5coins");
         cfg.addDefault("3.lore", lore);
         cfg.addDefault("3.items.1.material", "GOLDEN_CHESTPLATE");
         cfg.addDefault("3.items.1.amount", 1);
         cfg.addDefault("3.items.1.displayname", "&cChestplate + Thorns1");
         iLore = new ArrayList();
         iLore.add("Chestplate + Thorns#1");
         cfg.addDefault("3.items.1.lore", iLore);
         iEnch = new ArrayList();
         iEnch.add("THORNS#1");
         cfg.addDefault("3.items.1.enchantments", iEnch);
         cfg.addDefault("4.name", "&fSword and Helmet");
         cfg.addDefault("4.cost", 300);
         cfg.addDefault("4.material", "GOLDEN_SWORD");
         cfg.addDefault("4.glow", false);
         cfg.addDefault("4.amount", 1);
         cfg.addDefault("4.permission", "tntrun.shop.4");
         lore = new ArrayList();
         lore.add("Golden Sword and Helmet");
         lore.add("Cost&6 300 &5coins");
         cfg.addDefault("4.lore", lore);
         cfg.addDefault("4.items.1.material", "GOLDEN_SWORD");
         cfg.addDefault("4.items.1.amount", 1);
         cfg.addDefault("4.items.1.displayname", "&cGolden Sword");
         iLore = new ArrayList();
         iLore.add("Golden Sword");
         cfg.addDefault("4.items.1.lore", iLore);
         iEnch = new ArrayList();
         iEnch.add((Object)null);
         cfg.addDefault("4.items.1.enchantments", iEnch);
         cfg.addDefault("4.items.2.material", "GOLDEN_HELMET");
         cfg.addDefault("4.items.2.amount", 1);
         cfg.addDefault("4.items.2.displayname", "&cGolden Helmet");
         iLore = new ArrayList();
         iLore.add("Golden Helmet");
         cfg.addDefault("4.items.2.lore", iLore);
         iEnch = new ArrayList();
         iEnch.add("PROTECTION#1");
         cfg.addDefault("4.items.2.enchantments", iEnch);
         cfg.addDefault("5.name", "&fSnowballs x 20");
         cfg.addDefault("5.cost", 50);
         cfg.addDefault("5.material", "SNOWBALL");
         cfg.addDefault("5.glow", false);
         cfg.addDefault("5.amount", 20);
         cfg.addDefault("5.permission", "tntrun.shop.5");
         lore = new ArrayList();
         lore.add("Snowballs + Knockback2");
         lore.add("Cost&6 50 &5coins");
         cfg.addDefault("5.lore", lore);
         cfg.addDefault("5.items.1.material", "SNOWBALL");
         cfg.addDefault("5.items.1.amount", 20);
         cfg.addDefault("5.items.1.displayname", "&cSnowballs");
         iLore = new ArrayList();
         iLore.add("Snowballs");
         cfg.addDefault("5.items.1.lore", iLore);
         iEnch = new ArrayList();
         iEnch.add("KNOCKBACK#2");
         cfg.addDefault("5.items.1.enchantments", iEnch);
         cfg.addDefault("6.name", "&fSpeed Potion");
         cfg.addDefault("6.cost", 50);
         cfg.addDefault("6.material", "POTION");
         cfg.addDefault("6.amount", 1);
         cfg.addDefault("6.permission", "tntrun.shop.6");
         lore = new ArrayList();
         lore.add("Add&6 SPEED &5(1:00)");
         lore.add("Cost&6 50 &5coins");
         cfg.addDefault("6.lore", lore);
         cfg.addDefault("6.items.1.material", "POTION");
         cfg.addDefault("6.items.1.amount", 1);
         iEnch = new ArrayList();
         iEnch.add("SPEED#60");
         cfg.addDefault("6.items.1.enchantments", iEnch);
         cfg.addDefault("7.name", "&fJump Potion");
         cfg.addDefault("7.cost", 50);
         cfg.addDefault("7.material", "POTION");
         cfg.addDefault("7.amount", 1);
         cfg.addDefault("7.permission", "tntrun.shop.7");
         lore = new ArrayList();
         lore.add("Add&6 JUMP &5boost (0:45)");
         lore.add("Cost&6 50 &5coins");
         cfg.addDefault("7.lore", lore);
         cfg.addDefault("7.items.1.material", "POTION");
         cfg.addDefault("7.items.1.amount", 1);
         iEnch = new ArrayList();
         iEnch.add("JUMP_BOOST#45");
         cfg.addDefault("7.items.1.enchantments", iEnch);
         cfg.addDefault("8.name", "&fNight Vision Potion");
         cfg.addDefault("8.cost", 50);
         cfg.addDefault("8.material", "POTION");
         cfg.addDefault("8.amount", 1);
         cfg.addDefault("8.permission", "tntrun.shop.8");
         lore = new ArrayList();
         lore.add("Add&6 NIGHT_VISION &5(2:00)");
         lore.add("Cost&6 50 &5coins");
         cfg.addDefault("8.lore", lore);
         cfg.addDefault("8.items.1.material", "POTION");
         cfg.addDefault("8.items.1.amount", 1);
         iEnch = new ArrayList();
         iEnch.add("NIGHT_VISION#120");
         cfg.addDefault("8.items.1.enchantments", iEnch);
         cfg.addDefault("9.name", "&fInvisibility Potion");
         cfg.addDefault("9.cost", 50);
         cfg.addDefault("9.material", "POTION");
         cfg.addDefault("9.amount", 1);
         cfg.addDefault("9.permission", "tntrun.shop.9");
         lore = new ArrayList();
         lore.add("Add&6 INVISIBILITY &5(1:00)");
         lore.add("Cost&6 50 &5coins");
         cfg.addDefault("9.lore", lore);
         cfg.addDefault("9.items.1.material", "POTION");
         cfg.addDefault("9.items.1.amount", 1);
         iEnch = new ArrayList();
         iEnch.add("INVISIBILITY#60");
         cfg.addDefault("9.items.1.enchantments", iEnch);
         cfg.addDefault("10.name", "&fSplash Potion of Slowness");
         cfg.addDefault("10.cost", 50);
         cfg.addDefault("10.material", "SPLASH_POTION");
         cfg.addDefault("10.amount", 1);
         cfg.addDefault("10.permission", "tntrun.shop.10");
         lore = new ArrayList();
         lore.add("Add&6 SLOWNESS &5(0:30)");
         lore.add("Cost&6 50 &5coins");
         cfg.addDefault("10.lore", lore);
         cfg.addDefault("10.items.1.material", "SPLASH_POTION");
         cfg.addDefault("10.items.1.amount", 1);
         cfg.addDefault("10.items.1.displayname", "&cSplash Potion of Slowness");
         iLore = new ArrayList();
         iLore.add("Slowness");
         cfg.addDefault("10.items.1.lore", iLore);
         iEnch = new ArrayList();
         iEnch.add("SLOWNESS#30");
         cfg.addDefault("10.items.1.enchantments", iEnch);
         cfg.addDefault("11.name", "&fSplash Potion of Confusion");
         cfg.addDefault("11.cost", 50);
         cfg.addDefault("11.material", "SPLASH_POTION");
         cfg.addDefault("11.amount", 1);
         cfg.addDefault("11.permission", "tntrun.shop.11");
         lore = new ArrayList();
         lore.add("Add&6 CONFUSION &5(0:30)");
         lore.add("Cost&6 50 &5coins");
         cfg.addDefault("11.lore", lore);
         cfg.addDefault("11.items.1.material", "SPLASH_POTION");
         cfg.addDefault("11.items.1.amount", 1);
         cfg.addDefault("11.items.1.displayname", "&cSplash Potion of Confusion");
         iLore = new ArrayList();
         iLore.add("Confusion");
         cfg.addDefault("11.items.1.lore", iLore);
         iEnch = new ArrayList();
         iEnch.add("NAUSEA#30");
         cfg.addDefault("11.items.1.enchantments", iEnch);
         cfg.addDefault("12.name", "&fSplash Potion of Blindness");
         cfg.addDefault("12.cost", 50);
         cfg.addDefault("12.material", "SPLASH_POTION");
         cfg.addDefault("12.amount", 1);
         cfg.addDefault("12.permission", "tntrun.shop.12");
         lore = new ArrayList();
         lore.add("Add&6 BLINDNESS &5(1:30)");
         lore.add("Cost&6 100 &5coins");
         cfg.addDefault("12.lore", lore);
         cfg.addDefault("12.items.1.material", "SPLASH_POTION");
         cfg.addDefault("12.items.1.amount", 1);
         cfg.addDefault("12.items.1.displayname", "&cSplash Potion of Blindness");
         iLore = new ArrayList();
         iLore.add("Blindness");
         cfg.addDefault("12.items.1.lore", iLore);
         iEnch = new ArrayList();
         iEnch.add("BLINDNESS#90");
         cfg.addDefault("12.items.1.enchantments", iEnch);
         cfg.addDefault("13.name", "&fCommand");
         cfg.addDefault("13.cost", 50);
         cfg.addDefault("13.material", "COMMAND_BLOCK");
         cfg.addDefault("13.amount", 1);
         cfg.addDefault("13.permission", "tntrun.shop.13");
         lore = new ArrayList();
         lore.add("&6give %PLAYER% GOLD_NUGGET 1");
         lore.add("Cost&6 50 &5coins");
         cfg.addDefault("13.lore", lore);
         cfg.addDefault("13.items.1.material", "COMMAND");
         cfg.addDefault("13.items.1.amount", 1);
         iEnch = new ArrayList();
         iEnch.add("null");
         cfg.addDefault("13.items.1.enchantments", iEnch);

         try {
            cfg.save(this.getShopFile());
         } catch (IOException var6) {
            var6.printStackTrace();
         }

      }
   }
}
