package github.nighter.smartspawner.libs.mariadb;

import github.nighter.smartspawner.libs.mariadb.client.ColumnDecoder;
import github.nighter.smartspawner.libs.mariadb.client.Completion;
import github.nighter.smartspawner.libs.mariadb.client.DataType;
import github.nighter.smartspawner.libs.mariadb.client.result.CompleteResult;
import github.nighter.smartspawner.libs.mariadb.client.result.Result;
import github.nighter.smartspawner.libs.mariadb.client.util.ClosableLock;
import github.nighter.smartspawner.libs.mariadb.client.util.Parameter;
import github.nighter.smartspawner.libs.mariadb.client.util.Parameters;
import github.nighter.smartspawner.libs.mariadb.codec.NonNullParameter;
import github.nighter.smartspawner.libs.mariadb.codec.ParameterWithCal;
import github.nighter.smartspawner.libs.mariadb.export.ExceptionFactory;
import github.nighter.smartspawner.libs.mariadb.export.Prepare;
import github.nighter.smartspawner.libs.mariadb.message.ClientMessage;
import github.nighter.smartspawner.libs.mariadb.message.client.BulkExecutePacket;
import github.nighter.smartspawner.libs.mariadb.message.client.PreparePacket;
import github.nighter.smartspawner.libs.mariadb.message.server.OkPacket;
import github.nighter.smartspawner.libs.mariadb.message.server.PrepareResultPacket;
import github.nighter.smartspawner.libs.mariadb.plugin.Codec;
import github.nighter.smartspawner.libs.mariadb.plugin.array.FloatArray;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.BigDecimalCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.BlobCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.BooleanCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.ByteArrayCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.ByteCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.ClobCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.DateCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.DoubleCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.FloatArrayCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.FloatCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.FloatObjectArrayCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.IntCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.LongCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.ReaderCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.ShortCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.StreamCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.StringCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.TimeCodec;
import github.nighter.smartspawner.libs.mariadb.plugin.codec.TimestampCodec;
import github.nighter.smartspawner.libs.mariadb.util.ParameterList;
import github.nighter.smartspawner.libs.mariadb.util.timeout.QueryTimeoutHandler;
import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLType;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

public abstract class BasePreparedStatement extends Statement implements PreparedStatement {
   protected final String sql;
   protected Parameters parameters;
   protected List<Parameters> batchParameters;
   protected Prepare prepareResult = null;

   public BasePreparedStatement(String sql, Connection con, ClosableLock lock, int autoGeneratedKeys, int resultSetType, int resultSetConcurrency, int defaultFetchSize) {
      super(con, lock, autoGeneratedKeys, resultSetType, resultSetConcurrency, defaultFetchSize);
      this.sql = sql;
   }

   public String toString() {
      StringBuilder sb = new StringBuilder("sql:'" + this.sql + "'");
      sb.append(", parameters:[");

      for(int i = 0; i < this.parameters.size(); ++i) {
         Parameter param = this.parameters.get(i);
         if (param == null) {
            sb.append("null");
         } else {
            sb.append(param.bestEffortStringValue(this.con.getContext()));
         }

         if (i != this.parameters.size() - 1) {
            sb.append(",");
         }
      }

      sb.append("]");
      return sb.toString();
   }

   public String getLastSql() {
      return this.sql;
   }

   public void setPrepareResult(Prepare prepareResult) {
      this.prepareResult = prepareResult;
   }

   public ColumnDecoder[] getMeta() {
      return this.prepareResult.getColumns();
   }

   public void updateMeta(ColumnDecoder[] ci) {
      this.prepareResult.setColumns(ci);
   }

   public abstract boolean execute() throws SQLException;

   public abstract ResultSet executeQuery() throws SQLException;

   public abstract int executeUpdate() throws SQLException;

   public abstract long executeLargeUpdate() throws SQLException;

   public abstract void addBatch() throws SQLException;

   public abstract ResultSetMetaData getMetaData() throws SQLException;

   public abstract java.sql.ParameterMetaData getParameterMetaData() throws SQLException;

   public void setParameter(int index, Parameter param) {
      this.parameters.set(index, param);
   }

   public void addBatch(String sql) throws SQLException {
      throw this.exceptionFactory().create("addBatch(String sql) cannot be called on preparedStatement");
   }

   public boolean execute(String sql) throws SQLException {
      throw this.exceptionFactory().create("execute(String sql) cannot be called on preparedStatement");
   }

   public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
      throw this.exceptionFactory().create("execute(String sql, int autoGeneratedKeys) cannot be called on preparedStatement");
   }

   public boolean execute(String sql, int[] columnIndexes) throws SQLException {
      throw this.exceptionFactory().create("execute(String sql, int[] columnIndexes) cannot be called on preparedStatement");
   }

   public boolean execute(String sql, String[] columnNames) throws SQLException {
      throw this.exceptionFactory().create("execute(String sql, String[] columnNames) cannot be called on preparedStatement");
   }

   public ResultSet executeQuery(String sql) throws SQLException {
      throw this.exceptionFactory().create("executeQuery(String sql) cannot be called on preparedStatement");
   }

   public int executeUpdate(String sql) throws SQLException {
      throw this.exceptionFactory().create("executeUpdate(String sql) cannot be called on preparedStatement");
   }

   public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
      throw this.exceptionFactory().create("executeUpdate(String sql, int autoGeneratedKeys) cannot be called on preparedStatement");
   }

   public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
      throw this.exceptionFactory().create("executeUpdate(String sql, int[] columnIndexes) cannot be called on preparedStatement");
   }

   public int executeUpdate(String sql, String[] columnNames) throws SQLException {
      throw this.exceptionFactory().create("executeUpdate(String sql, String[] columnNames) cannot be called on preparedStatement");
   }

   public long executeLargeUpdate(String sql) throws SQLException {
      throw this.exceptionFactory().create("executeLargeUpdate(String sql) cannot be called on preparedStatement");
   }

   public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
      throw this.exceptionFactory().create("executeLargeUpdate(String sql, int autoGeneratedKeys) cannot be called on preparedStatement");
   }

   public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
      throw this.exceptionFactory().create("executeLargeUpdate(String sql, int[] columnIndexes) cannot be called on preparedStatement");
   }

   public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
      throw this.exceptionFactory().create("executeLargeUpdate(String sql, String[] columnNames) cannot be called on preparedStatement");
   }

   private void checkIndex(int index) throws SQLException {
      if (index <= 0) {
         throw this.exceptionFactory().create(String.format("wrong parameter index %s", index));
      }
   }

   public void setNull(int parameterIndex, int sqlType) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, github.nighter.smartspawner.libs.mariadb.codec.Parameter.NULL_PARAMETER);
   }

   public void setBoolean(int parameterIndex, boolean x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(BooleanCodec.INSTANCE, x));
   }

   public void setByte(int parameterIndex, byte x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(ByteCodec.INSTANCE, x));
   }

   public void setShort(int parameterIndex, short x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(ShortCodec.INSTANCE, x));
   }

   public void setInt(int parameterIndex, int x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(IntCodec.INSTANCE, x));
   }

   public void setLong(int parameterIndex, long x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(LongCodec.INSTANCE, x));
   }

   public void setFloat(int parameterIndex, float x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(FloatCodec.INSTANCE, x));
   }

   public void setDouble(int parameterIndex, double x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new NonNullParameter(DoubleCodec.INSTANCE, x));
   }

   public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(BigDecimalCodec.INSTANCE, x));
   }

   public void setString(int parameterIndex, String x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StringCodec.INSTANCE, x));
   }

   public void setBytes(int parameterIndex, byte[] x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ByteArrayCodec.INSTANCE, x));
   }

   public void setDate(int parameterIndex, Date x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(DateCodec.INSTANCE, x));
   }

   public void setTime(int parameterIndex, Time x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(TimeCodec.INSTANCE, x));
   }

   public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(TimestampCodec.INSTANCE, x));
   }

   public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, x, (long)length));
   }

   /** @deprecated */
   @Deprecated
   public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, x, (long)length));
   }

   public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, x, (long)length));
   }

   public void clearParameters() throws SQLException {
      this.checkNotClosed();
      this.parameters = new ParameterList();
   }

   public void clearBatch() throws SQLException {
      this.batchParameters = new ArrayList();
      super.clearBatch();
   }

   public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
      this.setInternalObject(parameterIndex, x, targetSqlType, (Long)null);
   }

   public void setObject(int parameterIndex, Object x) throws SQLException {
      this.setInternalObject(parameterIndex, x, (Integer)null, (Long)null);
   }

   public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, reader, (long)length));
   }

   public void setRef(int parameterIndex, Ref x) throws SQLException {
      throw this.exceptionFactory().notSupported("REF parameter are not supported");
   }

   public void setBlob(int parameterIndex, Blob x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(BlobCodec.INSTANCE, x));
   }

   public void setClob(int parameterIndex, Clob x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ClobCodec.INSTANCE, x));
   }

   public void setArray(int parameterIndex, Array x) throws SQLException {
      this.checkIndex(parameterIndex);
      if (x == null) {
         this.parameters.set(parameterIndex - 1, github.nighter.smartspawner.libs.mariadb.codec.Parameter.NULL_PARAMETER);
      } else if (x instanceof FloatArray) {
         this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(FloatArrayCodec.INSTANCE, (float[])x.getArray()));
      } else {
         throw this.exceptionFactory().notSupported(String.format("this type of Array parameter %s is not supported", x.getClass()));
      }
   }

   public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new ParameterWithCal(DateCodec.INSTANCE, x, cal));
   }

   public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new ParameterWithCal(TimeCodec.INSTANCE, x, cal));
   }

   public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new ParameterWithCal(TimestampCodec.INSTANCE, x, cal));
   }

   public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, github.nighter.smartspawner.libs.mariadb.codec.Parameter.NULL_PARAMETER);
   }

   public void setURL(int parameterIndex, URL x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StringCodec.INSTANCE, x == null ? null : x.toString()));
   }

   public void setRowId(int parameterIndex, RowId x) throws SQLException {
      throw this.exceptionFactory().notSupported("RowId parameter are not supported");
   }

   public void setNString(int parameterIndex, String value) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StringCodec.INSTANCE, value));
   }

   public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, value, length));
   }

   public void setNClob(int parameterIndex, NClob value) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ClobCodec.INSTANCE, value));
   }

   public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, reader, length));
   }

   public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, inputStream, length));
   }

   public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, reader, length));
   }

   public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
      throw this.exceptionFactory().notSupported("SQLXML parameter are not supported");
   }

   private ExceptionFactory exceptionFactory() {
      return this.con.getExceptionFactory().of(this);
   }

   public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
      this.setInternalObject(parameterIndex, x, targetSqlType, (long)scaleOrLength);
   }

   private void setInternalObject(int parameterIndex, Object obj, Integer targetSqlType, Long scaleOrLength) throws SQLException {
      this.checkIndex(parameterIndex);
      if (obj == null) {
         this.parameters.set(parameterIndex - 1, github.nighter.smartspawner.libs.mariadb.codec.Parameter.NULL_PARAMETER);
      } else {
         if (targetSqlType != null) {
            if (this.trySetArrayType(parameterIndex, obj, targetSqlType)) {
               return;
            }

            this.checkUnsupportedTypes(targetSqlType);
            if (this.trySetStringOrCharacter(parameterIndex, obj, targetSqlType)) {
               return;
            }

            if (this.trySetNumber(parameterIndex, obj, targetSqlType)) {
               return;
            }

            if (this.trySetByteArray(parameterIndex, obj, targetSqlType, scaleOrLength)) {
               return;
            }
         }

         this.trySetWithCodec(parameterIndex, obj, scaleOrLength);
      }
   }

   private boolean trySetArrayType(int parameterIndex, Object obj, Integer targetSqlType) throws SQLException {
      if (targetSqlType != 2003) {
         return false;
      } else if (obj instanceof float[]) {
         this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(FloatArrayCodec.INSTANCE, (float[])obj));
         return true;
      } else if (obj instanceof Float[]) {
         this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(FloatObjectArrayCodec.INSTANCE, (Float[])obj));
         return true;
      } else if (obj instanceof FloatArray) {
         this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(FloatArrayCodec.INSTANCE, (float[])((FloatArray)obj).getArray()));
         return true;
      } else {
         throw this.exceptionFactory().notSupported(String.format("ARRAY Type not supported for %s", obj.getClass().getName()));
      }
   }

   private void checkUnsupportedTypes(Integer targetSqlType) throws SQLException {
      switch(targetSqlType) {
      case -8:
      case 70:
      case 2000:
      case 2002:
      case 2006:
      case 2009:
         throw this.exceptionFactory().notSupported("Type not supported");
      default:
      }
   }

   private boolean trySetStringOrCharacter(int parameterIndex, Object obj, Integer targetSqlType) throws SQLException {
      if (!(obj instanceof String) && !(obj instanceof Character)) {
         return false;
      } else if (targetSqlType == 2004) {
         throw this.exceptionFactory().create(String.format("Cannot convert a %s to a Blob", obj instanceof String ? "string" : "character"));
      } else {
         String str = obj instanceof String ? (String)obj : ((Character)obj).toString();
         return this.handleStringConversion(parameterIndex, str, targetSqlType);
      }
   }

   private boolean handleStringConversion(int parameterIndex, String str, Integer targetSqlType) throws SQLException {
      try {
         switch(targetSqlType) {
         case -16:
         case -15:
         case -9:
         case -1:
         case 1:
         case 12:
         case 2005:
         case 2011:
            this.setString(parameterIndex, str);
            return true;
         case -7:
         case 16:
            this.setBoolean(parameterIndex, !"false".equalsIgnoreCase(str) && !"0".equals(str));
            return true;
         case -6:
            this.setByte(parameterIndex, Byte.parseByte(str));
            return true;
         case -5:
            this.setLong(parameterIndex, Long.parseLong(str));
            return true;
         case 2:
         case 3:
            this.setBigDecimal(parameterIndex, new BigDecimal(str));
            return true;
         case 4:
            this.setInt(parameterIndex, Integer.parseInt(str));
            return true;
         case 5:
            this.setShort(parameterIndex, Short.parseShort(str));
            return true;
         case 6:
         case 8:
            this.setDouble(parameterIndex, Double.parseDouble(str));
            return true;
         case 7:
            this.setFloat(parameterIndex, Float.parseFloat(str));
            return true;
         case 92:
            this.setTime(parameterIndex, Time.valueOf(str));
            return true;
         case 93:
            this.handleTimestampString(parameterIndex, str);
            return true;
         }
      } catch (IllegalArgumentException var5) {
         throw this.exceptionFactory().create(String.format("Could not convert [%s] to java.sql.Type %s", str, targetSqlType), "HY000", var5);
      }

      throw this.exceptionFactory().create(String.format("Could not convert [%s] to %s", str, targetSqlType));
   }

   private void handleTimestampString(int parameterIndex, String str) throws SQLException {
      if (str.startsWith("0000-00-00")) {
         this.setTimestamp(parameterIndex, (Timestamp)null);
      } else {
         this.setTimestamp(parameterIndex, Timestamp.valueOf(str));
      }

   }

   private boolean trySetNumber(int parameterIndex, Object obj, Integer targetSqlType) throws SQLException {
      if (!(obj instanceof Number)) {
         return false;
      } else {
         Number bd = (Number)obj;
         switch(targetSqlType) {
         case -7:
            this.setBoolean(parameterIndex, bd.shortValue() != 0);
            return true;
         case -6:
            this.setByte(parameterIndex, bd.byteValue());
            return true;
         case -5:
            this.setLong(parameterIndex, bd.longValue());
            return true;
         case -4:
         case -3:
         case -2:
         case -1:
         case 0:
         case 9:
         case 10:
         case 11:
         default:
            throw this.exceptionFactory().create(String.format("Could not convert [%s] to %s", bd, targetSqlType));
         case 1:
         case 12:
            this.setString(parameterIndex, bd.toString());
            return true;
         case 2:
         case 3:
            this.handleNumericType(parameterIndex, obj, bd);
            return true;
         case 4:
            this.setInt(parameterIndex, bd.intValue());
            return true;
         case 5:
            this.setShort(parameterIndex, bd.shortValue());
            return true;
         case 6:
         case 8:
            this.setDouble(parameterIndex, bd.doubleValue());
            return true;
         case 7:
            this.setFloat(parameterIndex, bd.floatValue());
            return true;
         }
      }
   }

   private void handleNumericType(int parameterIndex, Object obj, Number bd) throws SQLException {
      if (obj instanceof BigDecimal) {
         this.setBigDecimal(parameterIndex, (BigDecimal)obj);
      } else if (!(obj instanceof Double) && !(obj instanceof Float)) {
         this.setLong(parameterIndex, bd.longValue());
      } else {
         this.setDouble(parameterIndex, bd.doubleValue());
      }

   }

   private boolean trySetByteArray(int parameterIndex, Object obj, Integer targetSqlType, Long scaleOrLength) throws SQLException {
      if (!(obj instanceof byte[])) {
         return false;
      } else {
         byte[] bytes = (byte[])obj;
         switch(targetSqlType) {
         case -4:
         case -3:
         case -2:
            if (scaleOrLength != null) {
               this.setBytes(parameterIndex, Arrays.copyOfRange(bytes, 0, scaleOrLength.intValue()));
            } else {
               this.setBytes(parameterIndex, bytes);
            }

            return true;
         case 2004:
            if (scaleOrLength != null) {
               this.setBlob(parameterIndex, (Blob)(new MariaDbBlob(bytes, 0, scaleOrLength.intValue())));
            } else {
               this.setBlob(parameterIndex, (Blob)(new MariaDbBlob(bytes)));
            }

            return true;
         default:
            throw this.exceptionFactory().create("Can only convert a byte[] to BINARY, VARBINARY, LONGVARBINARY or BLOB type");
         }
      }
   }

   private void trySetWithCodec(int parameterIndex, Object obj, Long scaleOrLength) throws SQLException {
      Codec[] var4 = this.con.getContext().getConf().codecs();
      int var5 = var4.length;

      for(int var6 = 0; var6 < var5; ++var6) {
         Codec<?> codec = var4[var6];
         if (codec.canEncode(obj)) {
            github.nighter.smartspawner.libs.mariadb.codec.Parameter p = new github.nighter.smartspawner.libs.mariadb.codec.Parameter(codec, obj, scaleOrLength);
            this.parameters.set(parameterIndex - 1, p);
            return;
         }
      }

      throw new SQLException(String.format("Type %s not supported type", obj.getClass().getName()));
   }

   public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, x, length));
   }

   public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, x, length));
   }

   public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, reader, length));
   }

   public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, x));
   }

   public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, x));
   }

   public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, reader));
   }

   public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, value));
   }

   public void setClob(int parameterIndex, Reader reader) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, reader));
   }

   public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(StreamCodec.INSTANCE, inputStream));
   }

   public void setNClob(int parameterIndex, Reader reader) throws SQLException {
      this.checkIndex(parameterIndex);
      this.parameters.set(parameterIndex - 1, new github.nighter.smartspawner.libs.mariadb.codec.Parameter(ReaderCodec.INSTANCE, reader));
   }

   public void setObject(int parameterIndex, Object x, SQLType targetSqlType, int scaleOrLength) throws SQLException {
      this.setInternalObject(parameterIndex, x, targetSqlType == null ? null : targetSqlType.getVendorTypeNumber(), (long)scaleOrLength);
   }

   public void setObject(int parameterIndex, Object x, SQLType targetSqlType) throws SQLException {
      this.setInternalObject(parameterIndex, x, targetSqlType == null ? null : targetSqlType.getVendorTypeNumber(), (Long)null);
   }

   protected abstract BasePreparedStatement.BatchTypeState executeInternalPreparedBatch() throws SQLException;

   public int[] executeBatch() throws SQLException {
      this.checkNotClosed();
      if (this.isBatchEmpty()) {
         return new int[0];
      } else {
         int[] var3;
         try {
            ClosableLock ignore = this.lock.closeableLock();

            try {
               QueryTimeoutHandler ignore2 = this.con.handleTimeout(this.queryTimeout);

               try {
                  var3 = this.executeBatchInternal();
               } catch (Throwable var14) {
                  if (ignore2 != null) {
                     try {
                        ignore2.close();
                     } catch (Throwable var13) {
                        var14.addSuppressed(var13);
                     }
                  }

                  throw var14;
               }

               if (ignore2 != null) {
                  ignore2.close();
               }
            } catch (Throwable var15) {
               if (ignore != null) {
                  try {
                     ignore.close();
                  } catch (Throwable var12) {
                     var15.addSuppressed(var12);
                  }
               }

               throw var15;
            }

            if (ignore != null) {
               ignore.close();
            }
         } catch (SQLException var16) {
            this.handleExecutionError(var16);
            throw var16;
         } finally {
            this.cleanupResources();
         }

         return var3;
      }
   }

   private boolean isBatchEmpty() {
      return this.batchParameters == null || this.batchParameters.isEmpty();
   }

   private int[] executeBatchInternal() throws SQLException {
      BasePreparedStatement.BatchTypeState batchTypeState = this.executeInternalPreparedBatch();
      int[] updates = new int[this.batchParameters.size()];
      if (this.shouldHandleBulkUnitResults(batchTypeState == BasePreparedStatement.BatchTypeState.Bulk)) {
         return this.handleBulkUnitResults(updates);
      } else {
         if (this.shouldHandleBulkInsert(batchTypeState == BasePreparedStatement.BatchTypeState.Bulk || batchTypeState == BasePreparedStatement.BatchTypeState.Rewrite)) {
            int[] bulkInsertUpdates = this.handleBulkInsert(updates);
            if (bulkInsertUpdates != null) {
               return bulkInsertUpdates;
            }
         }

         return this.handleStandardResults(updates);
      }
   }

   private boolean shouldHandleBulkUnitResults(boolean wasBulk) {
      return wasBulk && this.con.getContext().hasClientCapability(137438953472L);
   }

   private int[] handleBulkUnitResults(int[] updates) throws SQLException {
      int updateIdx = 0;
      Arrays.fill(updates, -2);
      Iterator var3 = this.results.iterator();

      while(var3.hasNext()) {
         Completion completion = (Completion)var3.next();
         if (completion instanceof CompleteResult) {
            CompleteResult completeResult = (CompleteResult)completion;
            if (completeResult.isBulkResult()) {
               updateIdx = this.processBulkResult(updates, updateIdx, completeResult);
            }
         }
      }

      this.currResult = (Completion)this.results.remove(0);
      return updates;
   }

   private long[] handleLongBulkUnitResults(long[] updates) throws SQLException {
      int updateIdx = 0;
      Arrays.fill(updates, -2L);
      Iterator var3 = this.results.iterator();

      while(var3.hasNext()) {
         Completion completion = (Completion)var3.next();
         if (completion instanceof CompleteResult) {
            CompleteResult completeResult = (CompleteResult)completion;
            if (completeResult.isBulkResult()) {
               updateIdx = this.processLongBulkResult(updates, updateIdx, completeResult);
            }
         }
      }

      this.currResult = (Completion)this.results.remove(0);
      return updates;
   }

   private int processBulkResult(int[] updates, int updateIdx, Result unitaryResults) throws SQLException {
      if (!unitaryResults.isBulkResult()) {
         return updateIdx;
      } else {
         unitaryResults.beforeFirst();

         while(unitaryResults.next()) {
            updates[updateIdx++] = unitaryResults.getInt(2);
         }

         return updateIdx;
      }
   }

   private int processLongBulkResult(long[] updates, int updateIdx, Result unitaryResults) throws SQLException {
      if (!unitaryResults.isBulkResult()) {
         return updateIdx;
      } else {
         unitaryResults.beforeFirst();

         while(unitaryResults.next()) {
            updates[updateIdx++] = (long)unitaryResults.getInt(2);
         }

         return updateIdx;
      }
   }

   private boolean shouldHandleBulkInsert(boolean wasBulk) {
      return wasBulk && this.clientParser.isInsert() && !this.clientParser.isInsertDuplicate();
   }

   private int[] handleBulkInsert(int[] updates) {
      int totalAffectedRows = this.calculateTotalAffectedRows();
      if (totalAffectedRows == updates.length) {
         Arrays.fill(updates, 1);
         this.currResult = (Completion)this.results.remove(0);
         return updates;
      } else {
         return null;
      }
   }

   private long[] handleLongBulkInsert(long[] updates) {
      int totalAffectedRows = this.calculateTotalAffectedRows();
      if (totalAffectedRows == updates.length) {
         Arrays.fill(updates, 1L);
         this.currResult = (Completion)this.results.remove(0);
         return updates;
      } else {
         return null;
      }
   }

   private int calculateTotalAffectedRows() {
      return this.results.stream().mapToInt((result) -> {
         return (int)((OkPacket)result).getAffectedRows();
      }).sum();
   }

   private int[] handleStandardResults(int[] updates) {
      if (this.results.size() != updates.length) {
         Arrays.fill(updates, -2);
      } else {
         this.processIndividualResults(updates);
      }

      this.currResult = (Completion)this.results.remove(0);
      return updates;
   }

   private long[] handleStandardLongResults(long[] updates) {
      if (this.results.size() != updates.length) {
         Arrays.fill(updates, -2L);
      } else {
         this.processIndividualLongResults(updates);
      }

      this.currResult = (Completion)this.results.remove(0);
      return updates;
   }

   private void processIndividualResults(int[] updates) {
      for(int i = 0; i < updates.length; ++i) {
         updates[i] = this.results.get(i) instanceof OkPacket ? (int)((OkPacket)this.results.get(i)).getAffectedRows() : -2;
      }

   }

   private void processIndividualLongResults(long[] updates) {
      for(int i = 0; i < updates.length; ++i) {
         updates[i] = this.results.get(i) instanceof OkPacket ? (long)((int)((OkPacket)this.results.get(i)).getAffectedRows()) : -2L;
      }

   }

   private void handleExecutionError(SQLException e) {
      this.results = null;
      this.currResult = null;
   }

   private void cleanupResources() {
      this.localInfileInputStream = null;
      this.batchParameters.clear();
   }

   private long[] executeLongBatchInternal() throws SQLException {
      BasePreparedStatement.BatchTypeState batchTypeState = this.executeInternalPreparedBatch();
      long[] updates = new long[this.batchParameters.size()];
      if (this.shouldHandleBulkUnitResults(batchTypeState == BasePreparedStatement.BatchTypeState.Bulk)) {
         return this.handleLongBulkUnitResults(updates);
      } else {
         if (this.shouldHandleBulkInsert(batchTypeState == BasePreparedStatement.BatchTypeState.Bulk || batchTypeState == BasePreparedStatement.BatchTypeState.Rewrite)) {
            long[] bulkInsertUpdates = this.handleLongBulkInsert(updates);
            if (bulkInsertUpdates != null) {
               return bulkInsertUpdates;
            }
         }

         return this.handleStandardLongResults(updates);
      }
   }

   public long[] executeLargeBatch() throws SQLException {
      this.checkNotClosed();
      if (this.isBatchEmpty()) {
         return new long[0];
      } else {
         long[] var3;
         try {
            ClosableLock ignore = this.lock.closeableLock();

            try {
               QueryTimeoutHandler timeoutHandler = this.con.handleTimeout(this.queryTimeout);

               try {
                  var3 = this.executeLongBatchInternal();
               } catch (Throwable var14) {
                  if (timeoutHandler != null) {
                     try {
                        timeoutHandler.close();
                     } catch (Throwable var13) {
                        var14.addSuppressed(var13);
                     }
                  }

                  throw var14;
               }

               if (timeoutHandler != null) {
                  timeoutHandler.close();
               }
            } catch (Throwable var15) {
               if (ignore != null) {
                  try {
                     ignore.close();
                  } catch (Throwable var12) {
                     var15.addSuppressed(var12);
                  }
               }

               throw var15;
            }

            if (ignore != null) {
               ignore.close();
            }
         } catch (SQLException var16) {
            this.handleExecutionError(var16);
            throw var16;
         } finally {
            this.cleanupResources();
         }

         return var3;
      }
   }

   protected void executeBatchBulk(String cmd) throws SQLException {
      if (this.prepareResult == null && this.con.cachePrepStmts()) {
         this.prepareResult = this.con.getContext().getPrepareCacheCmd(cmd, this);
      }

      try {
         if (this.prepareResult == null) {
            ClientMessage[] packets = new ClientMessage[]{new PreparePacket(cmd), new BulkExecutePacket((Prepare)null, this.batchParameters, cmd, this)};
            List<Completion> res = this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
            if (res.get(0) instanceof PrepareResultPacket) {
               this.results = res.subList(1, res.size());
            } else {
               this.results = res;
            }
         } else {
            this.results = this.con.getClient().execute(new BulkExecutePacket(this.prepareResult, this.batchParameters, cmd, this), this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
         }

      } catch (SQLException var4) {
         this.results = null;
         throw this.exceptionFactory().createBatchUpdate(Collections.emptyList(), this.batchParameters.size(), var4);
      }
   }

   public void reset() {
      this.lock.lock();

      try {
         this.prepareResult = null;
      } finally {
         this.lock.unlock();
      }

   }

   public ResultSet getGeneratedKeys() throws SQLException {
      this.checkNotClosed();
      this.validateGeneratedKeysSupport();
      List<String[]> insertIds = this.extractInsertIds();
      return !insertIds.isEmpty() ? this.createGeneratedKeysResultSet(insertIds) : super.getGeneratedKeys();
   }

   private void validateGeneratedKeysSupport() throws SQLException {
      if (this.autoGeneratedKeys != 1) {
         throw new SQLException("Cannot return generated keys: query was not set with Statement.RETURN_GENERATED_KEYS");
      }
   }

   private List<String[]> extractInsertIds() throws SQLException {
      if (this.currResult == null) {
         return Collections.emptyList();
      } else {
         List<String[]> insertIds = new ArrayList(this.results.size() + 1);
         List<Completion> allResults = this.getAllResults();
         Iterator var3 = allResults.iterator();

         while(var3.hasNext()) {
            Completion completion = (Completion)var3.next();
            if (this.isValidBulkResult(completion)) {
               this.processUnitaryResults((CompleteResult)completion, insertIds);
            }
         }

         return insertIds;
      }
   }

   private List<Completion> getAllResults() {
      List<Completion> allResults = new ArrayList(this.results);
      allResults.add(this.currResult);
      return allResults;
   }

   private boolean isValidBulkResult(Completion completion) {
      return completion instanceof CompleteResult && ((CompleteResult)completion).isBulkResult();
   }

   private void processUnitaryResults(CompleteResult unitaryResults, List<String[]> insertIds) throws SQLException {
      unitaryResults.beforeFirst();

      while(unitaryResults.next()) {
         this.addAutoGeneratedIdIfPresent(unitaryResults, insertIds);
      }

   }

   private void addAutoGeneratedIdIfPresent(Result unitaryResults, List<String[]> insertIds) throws SQLException {
      int autoGeneratedId = unitaryResults.getInt(1);
      if (autoGeneratedId != 0) {
         insertIds.add(new String[]{String.valueOf(autoGeneratedId)});
      }

   }

   private ResultSet createGeneratedKeysResultSet(List<String[]> insertIds) {
      String[][] ids = (String[][])insertIds.toArray(new String[0][]);
      return CompleteResult.createResultSet((String)"insert_id", (DataType)DataType.BIGINT, ids, this.con.getContext(), 544, this.resultSetType);
   }

   protected static enum BatchTypeState {
      Normal,
      Bulk,
      Rewrite;

      // $FF: synthetic method
      private static BasePreparedStatement.BatchTypeState[] $values() {
         return new BasePreparedStatement.BatchTypeState[]{Normal, Bulk, Rewrite};
      }
   }
}
