package github.nighter.smartspawner.libs.mariadb;

import github.nighter.smartspawner.libs.mariadb.client.ColumnDecoder;
import github.nighter.smartspawner.libs.mariadb.client.Completion;
import github.nighter.smartspawner.libs.mariadb.client.result.CompleteResult;
import github.nighter.smartspawner.libs.mariadb.client.result.Result;
import github.nighter.smartspawner.libs.mariadb.client.util.ClosableLock;
import github.nighter.smartspawner.libs.mariadb.client.util.Parameters;
import github.nighter.smartspawner.libs.mariadb.export.ExceptionFactory;
import github.nighter.smartspawner.libs.mariadb.message.ClientMessage;
import github.nighter.smartspawner.libs.mariadb.message.client.PreparePacket;
import github.nighter.smartspawner.libs.mariadb.message.client.QueryWithParametersPacket;
import github.nighter.smartspawner.libs.mariadb.message.client.QueryWithParametersRewritePacket;
import github.nighter.smartspawner.libs.mariadb.message.server.OkPacket;
import github.nighter.smartspawner.libs.mariadb.util.ClientParser;
import github.nighter.smartspawner.libs.mariadb.util.ParameterList;
import github.nighter.smartspawner.libs.mariadb.util.timeout.QueryTimeoutHandler;
import java.io.InputStream;
import java.sql.BatchUpdateException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Locale;

public class ClientPreparedStatement extends BasePreparedStatement {
   private final ClientParser parser;

   public ClientPreparedStatement(String sql, Connection con, ClosableLock lock, int autoGeneratedKeys, int resultSetType, int resultSetConcurrency, int defaultFetchSize) {
      super(sql, con, lock, autoGeneratedKeys, resultSetType, resultSetConcurrency, defaultFetchSize);
      boolean noBackslashEscapes = (con.getContext().getServerStatus() & 512) > 0;
      if (con.getContext().getConf().rewriteBatchedStatements()) {
         this.parser = ClientParser.rewritableParts(sql, noBackslashEscapes);
      } else {
         this.parser = ClientParser.parameterParts(sql, noBackslashEscapes);
      }

      this.parameters = new ParameterList(this.parser.getParamCount());
   }

   protected String preSqlCmd() {
      if (this.queryTimeout != 0 && this.con.useServerTimeout()) {
         return this.con.useServerMaxRows() && this.maxRows > 0L ? "SET STATEMENT max_statement_time=" + this.queryTimeout + ", SQL_SELECT_LIMIT=" + this.maxRows + " FOR " : "SET STATEMENT max_statement_time=" + this.queryTimeout + " FOR ";
      } else {
         return this.con.useServerMaxRows() && this.maxRows > 0L ? "SET STATEMENT SQL_SELECT_LIMIT=" + this.maxRows + " FOR " : null;
      }
   }

   private void executeInternal() throws SQLException {
      this.checkNotClosed();
      this.validParameters();

      try {
         ClosableLock ignore = this.lock.closeableLock();

         try {
            QueryTimeoutHandler ignore2 = this.con.handleTimeout(this.queryTimeout);

            try {
               QueryWithParametersPacket query = new QueryWithParametersPacket(this.preSqlCmd(), this.parser, this.parameters, this.localInfileInputStream);
               this.results = this.con.getClient().execute(query, this, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion, false);
            } catch (Throwable var14) {
               if (ignore2 != null) {
                  try {
                     ignore2.close();
                  } catch (Throwable var13) {
                     var14.addSuppressed(var13);
                  }
               }

               throw var14;
            }

            if (ignore2 != null) {
               ignore2.close();
            }
         } catch (Throwable var15) {
            if (ignore != null) {
               try {
                  ignore.close();
               } catch (Throwable var12) {
                  var15.addSuppressed(var12);
               }
            }

            throw var15;
         }

         if (ignore != null) {
            ignore.close();
         }
      } catch (SQLException var16) {
         this.results = null;
         this.currResult = null;
         throw var16;
      } finally {
         this.localInfileInputStream = null;
      }

   }

   protected BasePreparedStatement.BatchTypeState executeInternalPreparedBatch() throws SQLException {
      this.checkNotClosed();
      this.parseCommandIfNeeded(this.sql);
      Configuration conf = this.con.getContext().getConf();
      boolean possibleLoadLocal = this.con.getContext().hasClientCapability(128L);
      if (possibleLoadLocal) {
         String sqlUpper = this.sql.toUpperCase(Locale.ROOT);
         possibleLoadLocal = sqlUpper.contains(" LOCAL ") && sqlUpper.contains("LOAD") && sqlUpper.contains(" INFILE");
      }

      if (possibleLoadLocal) {
         this.executeBatchStd();
      } else {
         boolean canUseBulk = this.con.getContext().hasServerCapability(17179869184L) && (this.clientParser.isInsert() && (conf.useBulkStmts() || conf.useBulkStmtsForInserts()) && (this.con.getContext().hasClientCapability(137438953472L) || !this.clientParser.isInsertDuplicate()) || !this.clientParser.isInsert() && conf.useBulkStmts()) && (this.con.getContext().hasClientCapability(137438953472L) || this.autoGeneratedKeys != 1);
         if (canUseBulk && this.batchParameters.size() > 1 && !this.clientParser.isMultiQuery() && ((Parameters)this.batchParameters.get(0)).size() > 0) {
            this.executeBatchBulk(this.escapeTimeout(this.sql));
            return BasePreparedStatement.BatchTypeState.Bulk;
         }

         if (conf.rewriteBatchedStatements() && !this.parser.getParamPositions().isEmpty() && this.parser.getValuesBracketPositions() != null && this.autoGeneratedKeys == 2 && this.batchParameters.size() > 1) {
            this.executeBatchRewrite();
            return BasePreparedStatement.BatchTypeState.Rewrite;
         }

         this.executeBatchPipeline();
      }

      return BasePreparedStatement.BatchTypeState.Normal;
   }

   private void executeBatchPipeline() throws SQLException {
      ClientMessage[] packets = new ClientMessage[this.batchParameters.size()];

      for(int i = 0; i < this.batchParameters.size(); ++i) {
         packets[i] = new QueryWithParametersPacket(this.preSqlCmd(), this.parser, (Parameters)this.batchParameters.get(i), (InputStream)null);
      }

      try {
         this.results = this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
      } catch (SQLException var3) {
         this.results = null;
         throw var3;
      }
   }

   private void executeBatchRewrite() throws SQLException {
      try {
         this.results = this.con.getClient().execute(new QueryWithParametersRewritePacket(this.preSqlCmd(), this.parser, this.batchParameters), this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
      } catch (SQLException var2) {
         this.results = null;
         throw this.exceptionFactory().createBatchUpdate(Collections.emptyList(), this.batchParameters.size(), var2);
      }
   }

   private void executeBatchStd() throws SQLException {
      int i = 0;

      try {
         for(this.results = new ArrayList(); i < this.batchParameters.size(); ++i) {
            this.results.addAll(this.con.getClient().execute(new QueryWithParametersPacket(this.preSqlCmd(), this.parser, (Parameters)this.batchParameters.get(i), this.localInfileInputStream), this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false));
         }

      } catch (SQLException var4) {
         BatchUpdateException exception = this.exceptionFactory().createBatchUpdate(this.results, this.batchParameters.size(), var4);
         this.results = null;
         this.localInfileInputStream = null;
         throw exception;
      }
   }

   public boolean execute() throws SQLException {
      this.executeInternal();
      this.currResult = (Completion)this.results.remove(0);
      return this.currResult instanceof Result;
   }

   public ResultSet executeQuery() throws SQLException {
      this.executeInternal();
      this.currResult = (Completion)this.results.remove(0);
      if (this.currResult instanceof Result) {
         return (Result)this.currResult;
      } else if (this.con.getContext().getConf().permitNoResults()) {
         return new CompleteResult(new ColumnDecoder[0], new byte[0][], this.con.getContext(), this.resultSetType);
      } else {
         throw new SQLException("PrepareStatement.executeQuery() command does NOT return a result-set as expected. Either use PrepareStatement.execute(), PrepareStatement.executeUpdate(), or correct command");
      }
   }

   public int executeUpdate() throws SQLException {
      return (int)this.executeLargeUpdate();
   }

   public long executeLargeUpdate() throws SQLException {
      this.executeInternal();
      this.currResult = (Completion)this.results.remove(0);
      if (this.currResult instanceof Result) {
         throw this.exceptionFactory().create("the given SQL statement produces an unexpected ResultSet object", "HY000");
      } else {
         return ((OkPacket)this.currResult).getAffectedRows();
      }
   }

   private ExceptionFactory exceptionFactory() {
      return this.con.getExceptionFactory().of(this);
   }

   public void addBatch() throws SQLException {
      this.validParameters();
      if (this.batchParameters == null) {
         this.batchParameters = new ArrayList();
      }

      this.batchParameters.add(this.parameters);
      this.parameters = this.parameters.clone();
   }

   protected void validParameters() throws SQLException {
      for(int i = 0; i < this.parser.getParamCount(); ++i) {
         if (!this.parameters.containsKey(i)) {
            throw this.exceptionFactory().create("Parameter at position " + (i + 1) + " is not set", "07004");
         }
      }

   }

   public void setQueryTimeout(int seconds) throws SQLException {
      super.setQueryTimeout(seconds);
      if (this.con.useServerTimeout() && this.prepareResult != null) {
         this.prepareResult.close(this.con.getClient());
         this.prepareResult = null;
      }

   }

   public void setMaxRows(int max) throws SQLException {
      super.setMaxRows(max);
      if (this.con.useServerMaxRows() && this.prepareResult != null) {
         this.prepareResult.close(this.con.getClient());
         this.prepareResult = null;
      }

   }

   public void setLargeMaxRows(long max) throws SQLException {
      super.setLargeMaxRows(max);
      if (this.con.useServerMaxRows() && this.prepareResult != null) {
         this.prepareResult.close(this.con.getClient());
         this.prepareResult = null;
      }

   }

   public ResultSetMetaData getMetaData() throws SQLException {
      if (this.prepareResult == null) {
         this.con.getClient().execute(new PreparePacket(this.escapeTimeout(this.sql)), this, true);
      }

      return new github.nighter.smartspawner.libs.mariadb.client.result.ResultSetMetaData(this.exceptionFactory(), this.prepareResult.getColumns(), this.con.getContext().getConf(), false);
   }

   public java.sql.ParameterMetaData getParameterMetaData() throws SQLException {
      if (this.prepareResult == null) {
         try {
            this.con.getClient().execute(new PreparePacket(this.escapeTimeout(this.sql)), this, true);
         } catch (SQLException var2) {
            return new SimpleParameterMetaData(this.exceptionFactory(), this.parser.getParamCount());
         }
      }

      return new ParameterMetaData(this.exceptionFactory(), this.prepareResult.getParameters());
   }

   public void close() throws SQLException {
      if (this.prepareResult != null) {
         ClosableLock ignore = this.lock.closeableLock();

         try {
            this.prepareResult.close(this.con.getClient());
         } catch (Throwable var5) {
            if (ignore != null) {
               try {
                  ignore.close();
               } catch (Throwable var4) {
                  var5.addSuppressed(var4);
               }
            }

            throw var5;
         }

         if (ignore != null) {
            ignore.close();
         }
      }

      this.con.fireStatementClosed(this);
      super.close();
   }

   public String toString() {
      return "ClientPreparedStatement{" + super.toString() + '}';
   }
}
