package github.nighter.smartspawner.libs.mariadb;

import github.nighter.smartspawner.libs.mariadb.client.ColumnDecoder;
import github.nighter.smartspawner.libs.mariadb.client.Completion;
import github.nighter.smartspawner.libs.mariadb.client.result.CompleteResult;
import github.nighter.smartspawner.libs.mariadb.client.result.Result;
import github.nighter.smartspawner.libs.mariadb.client.util.ClosableLock;
import github.nighter.smartspawner.libs.mariadb.client.util.Parameters;
import github.nighter.smartspawner.libs.mariadb.export.ExceptionFactory;
import github.nighter.smartspawner.libs.mariadb.export.Prepare;
import github.nighter.smartspawner.libs.mariadb.export.SQLPrepareException;
import github.nighter.smartspawner.libs.mariadb.message.ClientMessage;
import github.nighter.smartspawner.libs.mariadb.message.client.ExecutePacket;
import github.nighter.smartspawner.libs.mariadb.message.client.PrepareExecutePacket;
import github.nighter.smartspawner.libs.mariadb.message.client.PreparePacket;
import github.nighter.smartspawner.libs.mariadb.message.server.OkPacket;
import github.nighter.smartspawner.libs.mariadb.message.server.PrepareResultPacket;
import github.nighter.smartspawner.libs.mariadb.util.ParameterList;
import github.nighter.smartspawner.libs.mariadb.util.timeout.QueryTimeoutHandler;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;

public class ServerPreparedStatement extends BasePreparedStatement {
   public ServerPreparedStatement(String sql, Connection con, ClosableLock lock, int autoGeneratedKeys, int resultSetType, int resultSetConcurrency, int defaultFetchSize) throws SQLException {
      super(sql, con, lock, autoGeneratedKeys, resultSetType, resultSetConcurrency, defaultFetchSize);
      this.parameters = new ParameterList();
   }

   protected void executeInternal() throws SQLException {
      this.checkNotClosed();
      this.validParameters();
      if (this.parameters.size() > 66560) {
         this.clientFailover();
      } else {
         try {
            ClosableLock ignore = this.lock.closeableLock();

            try {
               QueryTimeoutHandler ignore2 = this.con.handleTimeout(this.queryTimeout);

               try {
                  String cmd = this.escapeTimeout(this.sql);
                  if (this.prepareResult == null && this.con.cachePrepStmts()) {
                     this.prepareResult = this.con.getContext().getPrepareCacheCmd(cmd, this);
                  }

                  if (this.prepareResult == null && this.con.getContext().permitPipeline()) {
                     this.executePipeline(cmd);
                  } else {
                     this.executeStandard(cmd);
                  }
               } catch (Throwable var15) {
                  if (ignore2 != null) {
                     try {
                        ignore2.close();
                     } catch (Throwable var14) {
                        var15.addSuppressed(var14);
                     }
                  }

                  throw var15;
               }

               if (ignore2 != null) {
                  ignore2.close();
               }
            } catch (Throwable var16) {
               if (ignore != null) {
                  try {
                     ignore.close();
                  } catch (Throwable var13) {
                     var16.addSuppressed(var13);
                  }
               }

               throw var16;
            }

            if (ignore != null) {
               ignore.close();
            }
         } catch (SQLPrepareException var17) {
            this.clientFailover();
         } catch (SQLException var18) {
            this.results = null;
            this.currResult = null;
            throw var18;
         } finally {
            this.localInfileInputStream = null;
         }

      }
   }

   private void clientFailover() throws SQLException {
      ClientPreparedStatement clientPreparedStatement = new ClientPreparedStatement(this.sql, this.con, this.lock, this.autoGeneratedKeys, this.resultSetType, this.resultSetConcurrency, this.fetchSize);
      clientPreparedStatement.parameters = this.parameters;
      clientPreparedStatement.localInfileInputStream = this.localInfileInputStream;

      try {
         clientPreparedStatement.execute();
         this.results = clientPreparedStatement.results;
         this.results.add(0, clientPreparedStatement.currResult);
         this.currResult = null;
      } catch (SQLException var6) {
         this.results = null;
         this.currResult = null;
         throw var6;
      } finally {
         this.localInfileInputStream = null;
      }

   }

   private void executePipeline(String cmd) throws SQLException {
      try {
         List<Completion> res = this.con.getClient().execute(new PrepareExecutePacket(cmd, this.parameters, this, this.localInfileInputStream), this, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion, false);
         this.results = res.subList(1, res.size());
      } catch (SQLException var3) {
         this.results = null;
         throw var3;
      }
   }

   private void executeStandard(String cmd) throws SQLException {
      if (this.prepareResult == null) {
         if (this.con.cachePrepStmts()) {
            this.prepareResult = this.con.getContext().getPrepareCacheCmd(cmd, this);
         }

         if (this.prepareResult == null) {
            this.con.getClient().execute(new PreparePacket(cmd), this, true);
         }
      }

      this.validParameters();
      ExecutePacket execute = new ExecutePacket(this.prepareResult, this.parameters, cmd, this, this.localInfileInputStream);
      this.results = this.con.getClient().execute(execute, this, this.fetchSize, this.maxRows, this.resultSetConcurrency, this.resultSetType, this.closeOnCompletion, false);
   }

   protected BasePreparedStatement.BatchTypeState executeInternalPreparedBatch() throws SQLException {
      this.checkNotClosed();
      String cmd = this.escapeTimeout(this.sql);
      boolean possibleLoadLocal = this.con.getContext().hasClientCapability(128L);
      if (possibleLoadLocal) {
         String sqlUpper = this.sql.toUpperCase(Locale.ROOT);
         possibleLoadLocal = sqlUpper.contains(" LOCAL ") && sqlUpper.contains("LOAD") && sqlUpper.contains(" INFILE");
      }

      if (possibleLoadLocal) {
         this.executeBatchStandard(cmd);
         return BasePreparedStatement.BatchTypeState.Normal;
      } else {
         Configuration conf = this.con.getContext().getConf();
         this.parseCommandIfNeeded(this.sql);
         boolean canUseBulk = this.con.getContext().hasServerCapability(17179869184L) && (this.clientParser.isInsert() && (conf.useBulkStmts() || conf.useBulkStmtsForInserts()) && (this.con.getContext().hasClientCapability(137438953472L) || !this.clientParser.isInsertDuplicate()) || !this.clientParser.isInsert() && conf.useBulkStmts()) && (this.con.getContext().hasClientCapability(137438953472L) || this.autoGeneratedKeys != 1);
         if (canUseBulk && this.batchParameters.size() > 1 && ((Parameters)this.batchParameters.get(0)).size() > 0) {
            this.executeBatchBulk(cmd);
            return BasePreparedStatement.BatchTypeState.Bulk;
         } else {
            this.executeBatchPipeline(cmd);
            return BasePreparedStatement.BatchTypeState.Normal;
         }
      }
   }

   private void executeBatchPipeline(String cmd) throws SQLException {
      if (this.prepareResult == null && this.con.cachePrepStmts()) {
         this.prepareResult = this.con.getContext().getPrepareCacheCmd(cmd, this);
      }

      if (!this.con.getContext().hasServerCapability(17179869184L)) {
         this.con.getClient().execute(new PreparePacket(cmd), this, false);
      }

      int maxCmd = 250;
      ArrayList res = new ArrayList();

      try {
         int index = 0;
         if (this.prepareResult == null) {
            res.addAll(this.executeBunchPrepare(cmd, index, maxCmd));
            index += maxCmd;
         }

         while(index < this.batchParameters.size()) {
            res.addAll(this.executeBunch(cmd, index, maxCmd));
            index += maxCmd;
         }

         this.results = res;
      } catch (SQLException var5) {
         this.results = null;
         throw this.exceptionFactory().createBatchUpdate(res, this.batchParameters.size(), var5);
      }
   }

   private List<Completion> executeBunch(String cmd, int index, int maxCmd) throws SQLException {
      int maxCmdToSend = Math.min(this.batchParameters.size() - index, maxCmd);
      ClientMessage[] packets = new ClientMessage[maxCmdToSend];

      for(int i = index; i < index + maxCmdToSend; ++i) {
         packets[i - index] = new ExecutePacket(this.prepareResult, (Parameters)this.batchParameters.get(i), cmd, this, this.localInfileInputStream);
      }

      return this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
   }

   private List<Completion> executeBunchPrepare(String cmd, int index, int maxCmd) throws SQLException {
      int maxCmdToSend = Math.min(this.batchParameters.size() - index, maxCmd);
      ClientMessage[] packets = new ClientMessage[maxCmdToSend + 1];
      packets[0] = new PreparePacket(cmd);

      for(int i = index; i < index + maxCmdToSend; ++i) {
         packets[i + 1 - index] = new ExecutePacket((Prepare)null, (Parameters)this.batchParameters.get(i), cmd, this, this.localInfileInputStream);
      }

      List<Completion> res = this.con.getClient().executePipeline(packets, this, 0, this.maxRows, 1007, 1003, this.closeOnCompletion, false);
      return res.get(0) instanceof PrepareResultPacket ? res.subList(1, res.size()) : res;
   }

   private void executeBatchStandard(String cmd) throws SQLException {
      List<Completion> tmpResults = new ArrayList();
      SQLException error = null;
      Iterator var4 = this.batchParameters.iterator();

      while(var4.hasNext()) {
         Parameters batchParameter = (Parameters)var4.next();
         if (this.prepareResult == null) {
            if (this.con.cachePrepStmts()) {
               this.prepareResult = this.con.getContext().getPrepareCacheCmd(cmd, this);
            }

            if (this.prepareResult == null) {
               this.con.getClient().execute(new PreparePacket(cmd), this, false);
            }
         }

         try {
            ExecutePacket execute = new ExecutePacket(this.prepareResult, batchParameter, cmd, this, this.localInfileInputStream);
            tmpResults.addAll(this.con.getClient().execute(execute, this, false));
         } catch (SQLException var7) {
            if (error == null) {
               error = var7;
            }
         }
      }

      if (error != null) {
         throw this.exceptionFactory().createBatchUpdate(tmpResults, this.batchParameters.size(), error);
      } else {
         this.results = tmpResults;
      }
   }

   public boolean execute() throws SQLException {
      this.executeInternal();
      this.handleParameterOutput();
      return this.currResult instanceof Result;
   }

   public void setMaxRows(int max) throws SQLException {
      super.setMaxRows(max);
      if (this.con.useServerMaxRows() && this.prepareResult != null) {
         this.prepareResult.decrementUse(this.con.getClient(), this);
         this.prepareResult = null;
      }

   }

   public void setLargeMaxRows(long max) throws SQLException {
      super.setLargeMaxRows(max);
      if (this.con.useServerMaxRows() && this.prepareResult != null) {
         this.prepareResult.decrementUse(this.con.getClient(), this);
         this.prepareResult = null;
      }

   }

   public void setQueryTimeout(int seconds) throws SQLException {
      super.setQueryTimeout(seconds);
      if (this.con.useServerTimeout() && this.prepareResult != null) {
         this.prepareResult.decrementUse(this.con.getClient(), this);
         this.prepareResult = null;
      }

   }

   public ResultSet executeQuery() throws SQLException {
      this.executeInternal();
      this.handleParameterOutput();
      if (this.currResult instanceof Result) {
         return (Result)this.currResult;
      } else if (this.con.getContext().getConf().permitNoResults()) {
         return new CompleteResult(new ColumnDecoder[0], new byte[0][], this.con.getContext(), this.resultSetType);
      } else {
         throw new SQLException("PrepareStatement.executeQuery() command does NOT return a result-set as expected. Either use PrepareStatement.execute(), PrepareStatement.executeUpdate(), or correct command");
      }
   }

   public int executeUpdate() throws SQLException {
      return (int)this.executeLargeUpdate();
   }

   public long executeLargeUpdate() throws SQLException {
      this.executeInternal();
      this.handleParameterOutput();
      if (this.currResult instanceof Result) {
         throw this.exceptionFactory().create("the given SQL statement produces an unexpected ResultSet object", "HY000");
      } else {
         return ((OkPacket)this.currResult).getAffectedRows();
      }
   }

   protected void handleParameterOutput() throws SQLException {
      this.currResult = (Completion)this.results.remove(0);
   }

   public void addBatch() throws SQLException {
      this.validParameters();
      if (this.batchParameters == null) {
         this.batchParameters = new ArrayList();
      }

      this.batchParameters.add(this.parameters);
      this.parameters = this.parameters.clone();
   }

   protected void validParameters() throws SQLException {
      int i;
      if (this.prepareResult != null) {
         for(i = 0; i < this.prepareResult.getParameters().length; ++i) {
            if (!this.parameters.containsKey(i)) {
               throw this.exceptionFactory().create("Parameter at position " + (i + 1) + " is not set", "07004");
            }
         }
      } else {
         if (this.batchParameters != null && !this.batchParameters.isEmpty() && this.parameters.size() < ((Parameters)this.batchParameters.get(0)).size()) {
            throw this.exceptionFactory().create("batch set of parameters differ from previous set. All parameters must be set", "07004");
         }

         for(i = 0; i < this.parameters.size(); ++i) {
            if (!this.parameters.containsKey(i)) {
               throw this.exceptionFactory().create("Parameter at position " + (i + 1) + " is not set", "07004");
            }
         }
      }

   }

   public ResultSetMetaData getMetaData() throws SQLException {
      if (this.prepareResult == null) {
         this.con.getClient().execute(new PreparePacket(this.escapeTimeout(this.sql)), this, true);
      }

      return new github.nighter.smartspawner.libs.mariadb.client.result.ResultSetMetaData(this.exceptionFactory(), this.prepareResult.getColumns(), this.con.getContext().getConf(), false);
   }

   public java.sql.ParameterMetaData getParameterMetaData() throws SQLException {
      if (this.prepareResult == null) {
         this.con.getClient().execute(new PreparePacket(this.escapeTimeout(this.sql)), this, true);
      }

      return new ParameterMetaData(this.exceptionFactory(), this.prepareResult.getParameters());
   }

   protected ExceptionFactory exceptionFactory() {
      return this.con.getExceptionFactory().of(this);
   }

   public void close() throws SQLException {
      if (this.prepareResult != null) {
         this.prepareResult.decrementUse(this.con.getClient(), this);
         this.prepareResult = null;
      }

      this.con.fireStatementClosed(this);
      super.close();
   }

   public String toString() {
      return "ServerPreparedStatement{" + super.toString() + '}';
   }
}
