package com.sun.jna.platform.win32;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.win32.W32APIOptions;

public interface Cfgmgr32 extends Library {
   Cfgmgr32 INSTANCE = (Cfgmgr32)Native.load("Cfgmgr32", Cfgmgr32.class, W32APIOptions.DEFAULT_OPTIONS);
   int CR_SUCCESS = 0;
   int CR_DEFAULT = 1;
   int CR_OUT_OF_MEMORY = 2;
   int CR_INVALID_POINTER = 3;
   int CR_INVALID_FLAG = 4;
   int CR_INVALID_DEVNODE = 5;
   int CR_INVALID_DEVINST = 5;
   int CR_INVALID_RES_DES = 6;
   int CR_INVALID_LOG_CONF = 7;
   int CR_INVALID_ARBITRATOR = 8;
   int CR_INVALID_NODELIST = 9;
   int CR_DEVNODE_HAS_REQS = 10;
   int CR_DEVINST_HAS_REQS = 10;
   int CR_INVALID_RESOURCEID = 11;
   int CR_DLVXD_NOT_FOUND = 12;
   int CR_NO_SUCH_DEVNODE = 13;
   int CR_NO_SUCH_DEVINST = 13;
   int CR_NO_MORE_LOG_CONF = 14;
   int CR_NO_MORE_RES_DES = 15;
   int CR_ALREADY_SUCH_DEVNODE = 16;
   int CR_ALREADY_SUCH_DEVINST = 16;
   int CR_INVALID_RANGE_LIST = 17;
   int CR_INVALID_RANGE = 18;
   int CR_FAILURE = 19;
   int CR_NO_SUCH_LOGICAL_DEV = 20;
   int CR_CREATE_BLOCKED = 21;
   int CR_NOT_SYSTEM_VM = 22;
   int CR_REMOVE_VETOED = 23;
   int CR_APM_VETOED = 24;
   int CR_INVALID_LOAD_TYPE = 25;
   int CR_BUFFER_SMALL = 26;
   int CR_NO_ARBITRATOR = 27;
   int CR_NO_REGISTRY_HANDLE = 28;
   int CR_REGISTRY_ERROR = 29;
   int CR_INVALID_DEVICE_ID = 30;
   int CR_INVALID_DATA = 31;
   int CR_INVALID_API = 32;
   int CR_DEVLOADER_NOT_READY = 33;
   int CR_NEED_RESTART = 34;
   int CR_NO_MORE_HW_PROFILES = 35;
   int CR_DEVICE_NOT_THERE = 36;
   int CR_NO_SUCH_VALUE = 37;
   int CR_WRONG_TYPE = 38;
   int CR_INVALID_PRIORITY = 39;
   int CR_NOT_DISABLEABLE = 40;
   int CR_FREE_RESOURCES = 41;
   int CR_QUERY_VETOED = 42;
   int CR_CANT_SHARE_IRQ = 43;
   int CR_NO_DEPENDENT = 44;
   int CR_SAME_RESOURCES = 45;
   int CR_NO_SUCH_REGISTRY_KEY = 46;
   int CR_INVALID_MACHINENAME = 47;
   int CR_REMOTE_COMM_FAILURE = 48;
   int CR_MACHINE_UNAVAILABLE = 49;
   int CR_NO_CM_SERVICES = 50;
   int CR_ACCESS_DENIED = 51;
   int CR_CALL_NOT_IMPLEMENTED = 52;
   int CR_INVALID_PROPERTY = 53;
   int CR_DEVICE_INTERFACE_ACTIVE = 54;
   int CR_NO_SUCH_DEVICE_INTERFACE = 55;
   int CR_INVALID_REFERENCE_STRING = 56;
   int CR_INVALID_CONFLICT_LIST = 57;
   int CR_INVALID_INDEX = 58;
   int CR_INVALID_STRUCTURE_SIZE = 59;
   int NUM_CR_RESULTS = 60;
   int CM_LOCATE_DEVNODE_NORMAL = 0;
   int CM_LOCATE_DEVNODE_PHANTOM = 1;
   int CM_LOCATE_DEVNODE_CANCELREMOVE = 2;
   int CM_LOCATE_DEVNODE_NOVALIDATION = 4;
   int CM_LOCATE_DEVNODE_BITS = 7;
   int CM_DRP_DEVICEDESC = 1;
   int CM_DRP_HARDWAREID = 2;
   int CM_DRP_COMPATIBLEIDS = 3;
   int CM_DRP_SERVICE = 5;
   int CM_DRP_CLASS = 8;
   int CM_DRP_CLASSGUID = 9;
   int CM_DRP_DRIVER = 10;
   int CM_DRP_CONFIGFLAGS = 11;
   int CM_DRP_MFG = 12;
   int CM_DRP_FRIENDLYNAME = 13;
   int CM_DRP_LOCATION_INFORMATION = 14;
   int CM_DRP_PHYSICAL_DEVICE_OBJECT_NAME = 15;
   int CM_DRP_CAPABILITIES = 16;
   int CM_DRP_UI_NUMBER = 17;
   int CM_DRP_UPPERFILTERS = 18;
   int CM_DRP_LOWERFILTERS = 19;
   int CM_DRP_BUSTYPEGUID = 20;
   int CM_DRP_LEGACYBUSTYPE = 21;
   int CM_DRP_BUSNUMBER = 22;
   int CM_DRP_ENUMERATOR_NAME = 23;
   int CM_DRP_SECURITY = 24;
   int CM_DRP_SECURITY_SDS = 25;
   int CM_DRP_DEVTYPE = 26;
   int CM_DRP_EXCLUSIVE = 27;
   int CM_DRP_CHARACTERISTICS = 28;
   int CM_DRP_ADDRESS = 29;
   int CM_DRP_UI_NUMBER_DESC_FORMAT = 30;
   int CM_DRP_DEVICE_POWER_DATA = 31;
   int CM_DRP_REMOVAL_POLICY = 32;
   int CM_DRP_REMOVAL_POLICY_HW_DEFAULT = 33;
   int CM_DRP_REMOVAL_POLICY_OVERRIDE = 34;
   int CM_DRP_INSTALL_STATE = 35;
   int CM_DRP_LOCATION_PATHS = 36;
   int CM_DRP_BASE_CONTAINERID = 37;

   int CM_Locate_DevNode(IntByReference var1, String var2, int var3);

   int CM_Get_Parent(IntByReference var1, int var2, int var3);

   int CM_Get_Child(IntByReference var1, int var2, int var3);

   int CM_Get_Sibling(IntByReference var1, int var2, int var3);

   int CM_Get_Device_ID(int var1, Pointer var2, int var3, int var4);

   int CM_Get_Device_ID_Size(IntByReference var1, int var2, int var3);

   int CM_Get_DevNode_Registry_Property(int var1, int var2, IntByReference var3, Pointer var4, IntByReference var5, int var6);
}
