package ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.debug.path;

import org.jspecify.annotations.NullMarked;

@NullMarked
public enum DebugPathType {
   BLOCKED,
   OPEN,
   WALKABLE,
   WALKABLE_DOOR,
   TRAPDOOR,
   POWDER_SNOW,
   DANGER_POWDER_SNOW,
   FENCE,
   LAVA,
   WATER,
   WATER_BORDER,
   RAIL,
   UNPASSABLE_RAIL,
   DANGER_FIRE,
   DAMAGE_FIRE,
   DANGER_OTHER,
   DAMAGE_OTHER,
   DOOR_OPEN,
   DOOR_WOOD_CLOSED,
   DOOR_IRON_CLOSED,
   BREACH,
   LEAVES,
   STICKY_HONEY,
   COCOA,
   DAMAGE_CAUTIOUS,
   DANGER_TRAPDOOR;

   // $FF: synthetic method
   private static DebugPathType[] $values() {
      return new DebugPathType[]{BLOCKED, OPEN, WALKABLE, WALKABLE_DOOR, TRAPDOOR, POWDER_SNOW, DANGER_POWDER_SNOW, FENCE, LAVA, WATER, WATER_BORDER, RAIL, UNPASSABLE_RAIL, DANGER_FIRE, DAMAGE_FIRE, DANGER_OTHER, DAMAGE_OTHER, DOOR_OPEN, DOOR_WOOD_CLOSED, DOOR_IRON_CLOSED, BREACH, LEAVES, STICKY_HONEY, COCOA, DAMAGE_CAUTIOUS, DANGER_TRAPDOOR};
   }
}
