package me.gypopo.economyshopgui.util;

import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;
import com.google.common.cache.CacheLoader;
import com.google.common.cache.LoadingCache;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import me.gypopo.economyshopgui.methodes.SendMessage;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.Validate;
import org.apache.commons.lang.WordUtils;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.data.type.Slab;
import org.bukkit.block.data.type.Slab.Type;
import org.bukkit.inventory.ItemStack;
import org.bukkit.material.MaterialData;
import org.bukkit.material.Step;
import org.bukkit.material.WoodenStep;

public enum XMaterial {
   COPPER_NAUTILUS_ARMOR(21),
   IRON_NAUTILUS_ARMOR(21),
   DIAMOND_NAUTILUS_ARMOR(21),
   GOLDEN_NAUTILUS_ARMOR(21),
   NETHERITE_NAUTILUS_ARMOR(21),
   NETHERITE_HORSE_ARMOR(21),
   CAMEL_HUSK_SPAWN_EGG(21),
   NAUTILUS_SPAWN_EGG(21),
   PARCHED_SPAWN_EGG(21),
   ZOMBIE_NAUTILUS_SPAWN_EGG(21),
   WOODEN_SPEAR(21),
   STONE_SPEAR(21),
   COPPER_SPEAR(21),
   IRON_SPEAR(21),
   DIAMOND_SPEAR(21),
   GOLDEN_SPEAR(21),
   NETHERITE_SPEAR(21),
   COPPER_CHEST(21),
   EXPOSED_COPPER_CHEST(21),
   WEATHERED_COPPER_CHEST(21),
   OXIDIZED_COPPER_CHEST(21),
   WAXED_COPPER_CHEST(21),
   WAXED_EXPOSED_COPPER_CHEST(21),
   WAXED_WEATHERED_COPPER_CHEST(21),
   WAXED_OXIDIZED_COPPER_CHEST(21),
   OAK_SHELF(21),
   SPRUCE_SHELF(21),
   BIRCH_SHELF(21),
   JUNGLE_SHELF(21),
   ACACIA_SHELF(21),
   DARK_OAK_SHELF(21),
   MANGROVE_SHELF(21),
   CHERRY_SHELF(21),
   PALE_OAK_SHELF(21),
   BAMBOO_SHELF(21),
   CRIMSON_SHELF(21),
   WARPED_SHELF(21),
   COPPER_GOLEM_STATUE(21),
   EXPOSED_COPPER_GOLEM_STATUE(21),
   WEATHERED_COPPER_GOLEM_STATUE(21),
   OXIDIZED_COPPER_GOLEM_STATUE(21),
   WAXED_COPPER_GOLEM_STATUE(21),
   WAXED_EXPOSED_COPPER_GOLEM_STATUE(21),
   WAXED_WEATHERED_COPPER_GOLEM_STATUE(21),
   WAXED_OXIDIZED_COPPER_GOLEM_STATUE(21),
   EXPOSED_LIGHTNING_ROD(21),
   WEATHERED_LIGHTNING_ROD(21),
   OXIDIZED_LIGHTNING_ROD(21),
   WAXED_LIGHTNING_ROD(21),
   WAXED_EXPOSED_LIGHTNING_ROD(21),
   WAXED_WEATHERED_LIGHTNING_ROD(21),
   WAXED_OXIDIZED_LIGHTNING_ROD(21),
   COPPER_GOLEM_SPAWN_EGG(21),
   COPPER_SWORD(21),
   COPPER_AXE(21),
   COPPER_PICKAXE(21),
   COPPER_SHOVEL(21),
   COPPER_HOE(21),
   COPPER_HELMET(21),
   COPPER_CHESTPLATE(21),
   COPPER_LEGGINGS(21),
   COPPER_BOOTS(21),
   COPPER_HORSE_ARMOR(21),
   COPPER_NUGGET(21),
   COPPER_TORCH(21),
   COPPER_WALL_TORCH(21),
   COPPER_LANTERN(21),
   EXPOSED_COPPER_LANTERN(21),
   WEATHERED_COPPER_LANTERN(21),
   OXIDIZED_COPPER_LANTERN(21),
   WAXED_COPPER_LANTERN(21),
   WAXED_EXPOSED_COPPER_LANTERN(21),
   WAXED_WEATHERED_COPPER_LANTERN(21),
   WAXED_OXIDIZED_COPPER_LANTERN(21),
   COPPER_BARS(21),
   EXPOSED_COPPER_BARS(21),
   WEATHERED_COPPER_BARS(21),
   OXIDIZED_COPPER_BARS(21),
   WAXED_COPPER_BARS(21),
   WAXED_EXPOSED_COPPER_BARS(21),
   WAXED_WEATHERED_COPPER_BARS(21),
   WAXED_OXIDIZED_COPPER_BARS(21),
   COPPER_CHAIN(21),
   EXPOSED_COPPER_CHAIN(21),
   WEATHERED_COPPER_CHAIN(21),
   OXIDIZED_COPPER_CHAIN(21),
   WAXED_COPPER_CHAIN(21),
   WAXED_EXPOSED_COPPER_CHAIN(21),
   WAXED_WEATHERED_COPPER_CHAIN(21),
   WAXED_OXIDIZED_COPPER_CHAIN(21),
   MUSIC_DISC_LAVA_CHICKEN(21),
   WHITE_HARNESS(21),
   LIGHT_GRAY_HARNESS(21),
   GRAY_HARNESS(21),
   BLACK_HARNESS(21),
   BROWN_HARNESS(21),
   RED_HARNESS(21),
   ORANGE_HARNESS(21),
   YELLOW_HARNESS(21),
   GREEN_HARNESS(21),
   LIME_HARNESS(21),
   CYAN_HARNESS(21),
   BLUE_HARNESS(21),
   MAGENTA_HARNESS(21),
   LIGHT_BLUE_HARNESS(21),
   PURPLE_HARNESS(21),
   PINK_HARNESS(21),
   MUSIC_DISC_TEARS(21),
   HAPPY_GHAST_SPAWN_EGG(21),
   DRIED_GHAST(21),
   BLUE_EGG(21),
   BROWN_EGG(21),
   BUSH(21),
   CACTUS_FLOWER(21),
   FIREFLY_BUSH(21),
   LEAF_LITTER(21),
   SHORT_DRY_GRASS(21),
   TALL_DRY_GRASS(21),
   TEST_BLOCK(21),
   TEST_INSTANCE_BLOCK(21),
   WILDFLOWERS(21),
   CREAKING_HEART(21),
   CREAKING_SPAWN_EGG(21),
   OPEN_EYEBLOSSOM(21),
   CLOSED_EYEBLOSSOM(21),
   PALE_HANGING_MOSS(21),
   PALE_MOSS_BLOCK(21),
   PALE_MOSS_CARPET(21),
   PALE_OAK_LOG(21),
   STRIPPED_PALE_OAK_LOG(21),
   PALE_OAK_WOOD(21),
   STRIPPED_PALE_OAK_WOOD(21),
   PALE_OAK_LEAVES(21),
   PALE_OAK_SAPLING(21),
   PALE_OAK_PLANKS(21),
   PALE_OAK_SIGN(21),
   PALE_OAK_BUTTON(21),
   PALE_OAK_DOOR(21),
   PALE_OAK_FENCE(21),
   PALE_OAK_FENCE_GATE(21),
   PALE_OAK_PRESSURE_PLATE(21),
   PALE_OAK_WALL_SIGN(21),
   PALE_OAK_HANGING_SIGN(21),
   PALE_OAK_SLAB(21),
   PALE_OAK_STAIRS(21),
   PALE_OAK_TRAPDOOR(21),
   PALE_OAK_BOAT(21),
   PALE_OAK_CHEST_BOAT(21),
   RESIN_CLUMP(21),
   RESIN_BLOCK(21),
   RESIN_BRICK(21),
   RESIN_BRICKS(21),
   RESIN_BRICK_SLAB(21),
   RESIN_BRICK_STAIRS(21),
   RESIN_BRICK_WALL(21),
   CHISELED_RESIN_BRICKS(21),
   FIELD_MASONED_BANNER_PATTERN(21),
   BORDURE_INDENTED_BANNER_PATTERN(21),
   WHITE_BUNDLE(21),
   ORANGE_BUNDLE(21),
   MAGENTA_BUNDLE(21),
   LIGHT_BLUE_BUNDLE(21),
   YELLOW_BUNDLE(21),
   LIME_BUNDLE(21),
   PINK_BUNDLE(21),
   GRAY_BUNDLE(21),
   LIGHT_GRAY_BUNDLE(21),
   CYAN_BUNDLE(21),
   PURPLE_BUNDLE(21),
   BLUE_BUNDLE(21),
   BROWN_BUNDLE(21),
   GREEN_BUNDLE(21),
   RED_BUNDLE(21),
   BLACK_BUNDLE(21),
   MUSIC_DISC_CREATOR(21),
   MUSIC_DISC_CREATOR_MUSIC_BOX(21),
   MUSIC_DISC_PRECIPICE(21),
   ARMADILLO_SCUTE(20),
   ARMADILLO_SPAWN_EGG(20),
   WOLF_ARMOR(20),
   HEAVY_CORE(21),
   TRIAL_SPAWNER(21),
   VAULT(21),
   FLOW_BANNER_PATTERN(21),
   GUSTER_BANNER_PATTERN(21),
   BREEZE_ROD(21),
   MACE(21),
   OMINOUS_BOTTLE(21),
   OMINOUS_TRIAL_KEY(21),
   FLOW_POTTERY_SHERD(21),
   GUSTER_POTTERY_SHERD(21),
   SCRAPE_POTTERY_SHERD(21),
   BOLT_ARMOR_TRIM_SMITHING_TEMPLATE(21),
   FLOW_ARMOR_TRIM_SMITHING_TEMPLATE(21),
   BOGGED_SPAWN_EGG(21),
   TRIAL_CHAMBERS_MAP(21),
   WIND_CHARGE(21),
   CHISELED_COPPER(21),
   EXPOSED_CHISELED_COPPER(21),
   WEATHERED_CHISELED_COPPER(21),
   OXIDIZED_CHISELED_COPPER(21),
   WAXED_CHISELED_COPPER(21),
   WAXED_EXPOSED_CHISELED_COPPER(21),
   WAXED_WEATHERED_CHISELED_COPPER(21),
   WAXED_OXIDIZED_CHISELED_COPPER(21),
   COPPER_BULB(21),
   EXPOSED_COPPER_BULB(21),
   WEATHERED_COPPER_BULB(21),
   OXIDIZED_COPPER_BULB(21),
   WAXED_COPPER_BULB(21),
   WAXED_EXPOSED_COPPER_BULB(21),
   WAXED_WEATHERED_COPPER_BULB(21),
   WAXED_OXIDIZED_COPPER_BULB(21),
   COPPER_DOOR(21),
   EXPOSED_COPPER_DOOR(21),
   WEATHERED_COPPER_DOOR(21),
   OXIDIZED_COPPER_DOOR(21),
   WAXED_COPPER_DOOR(21),
   WAXED_EXPOSED_COPPER_DOOR(21),
   WAXED_WEATHERED_COPPER_DOOR(21),
   WAXED_OXIDIZED_COPPER_DOOR(21),
   COPPER_TRAPDOOR(21),
   EXPOSED_COPPER_TRAPDOOR(21),
   WEATHERED_COPPER_TRAPDOOR(21),
   OXIDIZED_COPPER_TRAPDOOR(21),
   WAXED_COPPER_TRAPDOOR(21),
   WAXED_EXPOSED_COPPER_TRAPDOOR(21),
   WAXED_WEATHERED_COPPER_TRAPDOOR(21),
   WAXED_OXIDIZED_COPPER_TRAPDOOR(21),
   COPPER_GRATE(21),
   EXPOSED_COPPER_GRATE(21),
   WEATHERED_COPPER_GRATE(21),
   OXIDIZED_COPPER_GRATE(21),
   WAXED_COPPER_GRATE(21),
   WAXED_EXPOSED_COPPER_GRATE(21),
   WAXED_WEATHERED_COPPER_GRATE(21),
   WAXED_OXIDIZED_COPPER_GRATE(21),
   CRAFTER(21),
   TRAIL_SPAWNER(21),
   TUFF_STAIRS(21),
   TUFF_SLAB(21),
   TUFF_WALL(21),
   CHISELED_TUFF(21),
   POLISHED_TUFF_STAIRS(21),
   POLISHED_TUFF_SLAB(21),
   POLISHED_TUFF_WALL(21),
   POLISHED_TUFF(21),
   TUFF_BRICK_STAIRS(21),
   TUFF_BRICK_SLAB(21),
   TUFF_BRICK_WALL(21),
   TUFF_BRICKS(21),
   CHISELED_TUFF_BRICKS(21),
   BREEZE_SPAWN_EGG(21),
   TRIAL_KEY(21),
   ACACIA_BOAT(new String[]{"BOAT_ACACIA"}),
   ACACIA_BUTTON(new String[]{"WOOD_BUTTON"}),
   ACACIA_CHEST_BOAT(19),
   ACACIA_DOOR(new String[]{"ACACIA_DOOR", "ACACIA_DOOR_ITEM"}),
   ACACIA_FENCE,
   ACACIA_FENCE_GATE,
   ACACIA_HANGING_SIGN(20),
   ACACIA_LEAVES(new String[]{"LEAVES_2"}),
   ACACIA_LOG(new String[]{"LOG_2"}),
   ACACIA_PLANKS(4, new String[]{"WOOD"}),
   ACACIA_PRESSURE_PLATE(new String[]{"WOOD_PLATE"}),
   ACACIA_SAPLING(4, new String[]{"SAPLING"}),
   ACACIA_SIGN(new String[]{"SIGN_POST", "SIGN"}),
   ACACIA_SLAB(4, new String[]{"WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"}),
   ACACIA_STAIRS,
   ACACIA_TRAPDOOR(new String[]{"TRAP_DOOR"}),
   ACACIA_WOOD(new String[]{"LOG_2"}),
   ACTIVATOR_RAIL,
   AIR,
   ALLAY_SPAWN_EGG(19),
   ALLIUM(2, new String[]{"RED_ROSE"}),
   AMETHYST_BLOCK,
   AMETHYST_CLUSTER,
   AMETHYST_SHARD,
   ANCIENT_DEBRIS(16),
   ANDESITE(5, new String[]{"STONE"}),
   ANDESITE_SLAB,
   ANDESITE_STAIRS,
   ANDESITE_WALL,
   ANGLER_POTTERY_SHERD(20),
   ANVIL,
   APPLE,
   ARCHER_POTTERY_SHERD(20),
   ARMOR_STAND,
   ARMS_UP_POTTERY_SHERD(20),
   ARROW,
   AXOLOTL_BUCKET,
   AXOLOTL_SPAWN_EGG,
   AZALEA,
   AZALEA_LEAVES,
   AZURE_BLUET(3, new String[]{"RED_ROSE"}),
   BAKED_POTATO,
   BAMBOO(0, 14, new String[0]),
   BAMBOO_BLOCK(20),
   BAMBOO_BUTTON(20),
   BAMBOO_CHEST_RAFT(20),
   BAMBOO_DOOR(20),
   BAMBOO_FENCE(20),
   BAMBOO_FENCE_GATE(20),
   BAMBOO_HANGING_SIGN(20),
   BAMBOO_MOSAIC(20),
   BAMBOO_MOSAIC_SLAB(20),
   BAMBOO_MOSAIC_STAIRS(20),
   BAMBOO_PLANKS(20),
   BAMBOO_PRESSURE_PLATE(20),
   BAMBOO_RAFT(20),
   BAMBOO_SIGN(20),
   BAMBOO_SLAB(20),
   BAMBOO_STAIRS(20),
   BAMBOO_TRAPDOOR(20),
   BARREL(0, 14, new String[0]),
   BARRIER,
   BASALT(16),
   BAT_SPAWN_EGG(65, new String[]{"MONSTER_EGG"}),
   BEACON,
   BEDROCK,
   BEE_NEST(15),
   BEE_SPAWN_EGG(15),
   BEEF(new String[]{"RAW_BEEF"}),
   BEEHIVE(15),
   BEETROOT(new String[]{"BEETROOTS"}),
   BEETROOT_SEEDS,
   BEETROOT_SOUP,
   BELL(14),
   BIG_DRIPLEAF,
   BIRCH_BOAT(new String[]{"BOAT_BIRCH"}),
   BIRCH_BUTTON(new String[]{"WOOD_BUTTON"}),
   BIRCH_CHEST_BOAT(19),
   BIRCH_DOOR(new String[]{"BIRCH_DOOR", "BIRCH_DOOR_ITEM"}),
   BIRCH_FENCE,
   BIRCH_FENCE_GATE,
   BIRCH_HANGING_SIGN(20),
   BIRCH_LEAVES(2, new String[]{"LEAVES"}),
   BIRCH_LOG(2, new String[]{"LOG"}),
   BIRCH_PLANKS(2, new String[]{"WOOD"}),
   BIRCH_PRESSURE_PLATE(new String[]{"WOOD_PLATE"}),
   BIRCH_SAPLING(2, new String[]{"SAPLING"}),
   BIRCH_SIGN(new String[]{"SIGN_POST", "SIGN"}),
   BIRCH_SLAB(2, new String[]{"WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"}),
   BIRCH_STAIRS(new String[]{"BIRCH_WOOD_STAIRS"}),
   BIRCH_TRAPDOOR(new String[]{"TRAP_DOOR"}),
   BIRCH_WOOD(2, new String[]{"LOG"}),
   BLACK_BANNER(new String[]{"STANDING_BANNER", "BANNER"}),
   BLACK_BED(15, new String[]{"BED"}),
   BLACK_CANDLE,
   BLACK_CARPET(15, new String[]{"CARPET"}),
   BLACK_CONCRETE(15, new String[]{"CONCRETE"}),
   BLACK_CONCRETE_POWDER(15, new String[]{"CONCRETE_POWDER"}),
   BLACK_DYE(0, 14, new String[]{"INK_SACK", "INK_SAC"}),
   BLACK_GLAZED_TERRACOTTA(15, 12, new String[0]),
   BLACK_SHULKER_BOX,
   BLACK_STAINED_GLASS(15, new String[]{"STAINED_GLASS"}),
   BLACK_STAINED_GLASS_PANE(15, new String[]{"STAINED_GLASS_PANE"}),
   BLACK_TERRACOTTA(15, new String[]{"STAINED_CLAY"}),
   BLACK_WOOL(15, new String[]{"WOOL"}),
   BLACKSTONE(16),
   BLACKSTONE_SLAB(16),
   BLACKSTONE_STAIRS(16),
   BLACKSTONE_WALL(16),
   BLADE_POTTERY_SHERD(20),
   BLAST_FURNACE(0, 14, new String[0]),
   BLAZE_POWDER,
   BLAZE_ROD,
   BLAZE_SPAWN_EGG(61, new String[]{"MONSTER_EGG"}),
   BLUE_BANNER(4, new String[]{"STANDING_BANNER", "BANNER"}),
   BLUE_BED(11, new String[]{"BED"}),
   BLUE_CANDLE,
   BLUE_CARPET(11, new String[]{"CARPET"}),
   BLUE_CONCRETE(11, new String[]{"CONCRETE"}),
   BLUE_CONCRETE_POWDER(11, new String[]{"CONCRETE_POWDER"}),
   BLUE_DYE(4, new String[]{"INK_SACK", "LAPIS_LAZULI"}),
   BLUE_GLAZED_TERRACOTTA(11, 12, new String[0]),
   BLUE_ICE(0, 13, new String[0]),
   BLUE_ORCHID(1, new String[]{"RED_ROSE"}),
   BLUE_SHULKER_BOX,
   BLUE_STAINED_GLASS(11, new String[]{"STAINED_GLASS"}),
   BLUE_STAINED_GLASS_PANE(11, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   BLUE_TERRACOTTA(11, new String[]{"STAINED_CLAY"}),
   BLUE_WOOL(11, new String[]{"WOOL"}),
   BONE,
   BONE_BLOCK,
   BONE_MEAL(15, new String[]{"INK_SACK"}),
   BOOK,
   BOOKSHELF,
   BOW,
   BOWL,
   BRAIN_CORAL(13),
   BRAIN_CORAL_BLOCK(13),
   BRAIN_CORAL_FAN(13),
   BREAD,
   BREWER_POTTERY_SHERD(20),
   BREWING_STAND(new String[]{"BREWING_STAND", "BREWING_STAND_ITEM"}),
   BRICK(new String[]{"CLAY_BRICK"}),
   BRICK_SLAB(4, new String[]{"STEP"}),
   BRICK_STAIRS,
   BRICK_WALL,
   BRICKS(new String[]{"BRICKS", "BRICK"}),
   BROWN_BANNER(3, new String[]{"STANDING_BANNER", "BANNER"}),
   BROWN_BED(12, new String[]{"BED"}),
   BROWN_CANDLE,
   BROWN_CARPET(12, new String[]{"CARPET"}),
   BROWN_CONCRETE(12, new String[]{"CONCRETE"}),
   BROWN_CONCRETE_POWDER(12, new String[]{"CONCRETE_POWDER"}),
   BROWN_DYE(3, new String[]{"INK_SACK", "DYE", "COCOA_BEANS"}),
   BROWN_GLAZED_TERRACOTTA(12, 12, new String[0]),
   BROWN_MUSHROOM,
   BROWN_MUSHROOM_BLOCK(new String[]{"BROWN_MUSHROOM", "HUGE_MUSHROOM_1"}),
   BROWN_SHULKER_BOX,
   BROWN_STAINED_GLASS(12, new String[]{"STAINED_GLASS"}),
   BROWN_STAINED_GLASS_PANE(12, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   BROWN_TERRACOTTA(12, new String[]{"STAINED_CLAY"}),
   BROWN_WOOL(12, new String[]{"WOOL"}),
   BRUSH(20),
   BUBBLE_CORAL(13),
   BUBBLE_CORAL_BLOCK(13),
   BUBBLE_CORAL_FAN(13),
   BUCKET,
   BUDDING_AMETHYST,
   BUNDLE,
   BURN_POTTERY_SHERD(20),
   CACTUS,
   CAKE(new String[]{"CAKE_BLOCK"}),
   CALCITE,
   CALIBRATED_SCULK_SENSOR(20),
   CAMEL_SPAWN_EGG(20),
   CAMPFIRE(14),
   CANDLE,
   CARROT(new String[]{"CARROT_ITEM"}),
   CARROT_ON_A_STICK(new String[]{"CARROT_STICK"}),
   CARTOGRAPHY_TABLE(0, 14, new String[0]),
   CARVED_PUMPKIN(1, 13, new String[0]),
   CAT_SPAWN_EGG,
   CAULDRON(new String[]{"CAULDRON", "CAULDRON_ITEM"}),
   CAVE_SPIDER_SPAWN_EGG(59, new String[]{"MONSTER_EGG"}),
   IRON_CHAIN(new String[]{"CHAIN"}),
   CHAIN_COMMAND_BLOCK(new String[]{"COMMAND", "COMMAND_CHAIN"}),
   CHAINMAIL_BOOTS,
   CHAINMAIL_CHESTPLATE,
   CHAINMAIL_HELMET,
   CHAINMAIL_LEGGINGS,
   CHARCOAL(1, new String[]{"COAL"}),
   CHERRY_BOAT(20),
   CHERRY_BUTTON(20),
   CHERRY_CHEST_BOAT(20),
   CHERRY_DOOR(20),
   CHERRY_FENCE(20),
   CHERRY_FENCE_GATE(20),
   CHERRY_HANGING_SIGN(20),
   CHERRY_LEAVES(20),
   CHERRY_LOG(20),
   CHERRY_PLANKS(20),
   CHERRY_PRESSURE_PLATE(20),
   CHERRY_SAPLING(20),
   CHERRY_SIGN(20),
   CHERRY_SLAB(20),
   CHERRY_STAIRS(20),
   CHERRY_TRAPDOOR(20),
   CHERRY_WOOD(20),
   CHEST(new String[]{"LOCKED_CHEST"}),
   CHEST_MINECART(new String[]{"STORAGE_MINECART"}),
   CHICKEN(new String[]{"RAW_CHICKEN"}),
   CHICKEN_SPAWN_EGG(93, new String[]{"MONSTER_EGG"}),
   CHIPPED_ANVIL(1, new String[]{"ANVIL"}),
   CHISELED_BOOKSHELF(20),
   CHISELED_DEEPSLATE,
   CHISELED_NETHER_BRICKS(1, new String[]{"NETHER_BRICKS"}),
   CHISELED_POLISHED_BLACKSTONE(0, 16, new String[]{"POLISHED_BLACKSTONE"}),
   CHISELED_QUARTZ_BLOCK(1, new String[]{"QUARTZ_BLOCK"}),
   CHISELED_RED_SANDSTONE(1, new String[]{"RED_SANDSTONE"}),
   CHISELED_SANDSTONE(1, new String[]{"SANDSTONE"}),
   CHISELED_STONE_BRICKS(3, new String[]{"SMOOTH_BRICK"}),
   CHORUS_FLOWER(0, 9, new String[0]),
   CHORUS_FRUIT(0, 9, new String[0]),
   CHORUS_PLANT(0, 9, new String[0]),
   CLAY(new String[]{"CLAY_BALL"}),
   CLAY_BALL,
   CLOCK(new String[]{"WATCH"}),
   COAL,
   COAL_BLOCK,
   COAL_ORE,
   COARSE_DIRT(1, new String[]{"DIRT"}),
   COAST_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   COBBLED_DEEPSLATE,
   COBBLED_DEEPSLATE_SLAB,
   COBBLED_DEEPSLATE_STAIRS,
   COBBLED_DEEPSLATE_WALL,
   COBBLESTONE,
   COBBLESTONE_SLAB(3, new String[]{"STEP"}),
   COBBLESTONE_STAIRS,
   COBBLESTONE_WALL(new String[]{"COBBLE_WALL"}),
   COBWEB(new String[]{"WEB"}),
   COCOA_BEANS(3, new String[]{"INK_SACK"}),
   COD(new String[]{"RAW_FISH"}),
   COD_BUCKET(0, 13, new String[0]),
   COD_SPAWN_EGG(0, 13, new String[0]),
   COMMAND_BLOCK(new String[]{"COMMAND"}),
   COMMAND_BLOCK_MINECART(new String[]{"COMMAND_MINECART"}),
   COMPARATOR(new String[]{"REDSTONE_COMPARATOR_OFF", "REDSTONE_COMPARATOR_ON", "REDSTONE_COMPARATOR"}),
   COMPASS,
   COMPOSTER(0, 14, new String[0]),
   CONDUIT(0, 13, new String[]{"BEACON"}),
   COOKED_BEEF,
   COOKED_CHICKEN,
   COOKED_COD(new String[]{"COOKED_FISH"}),
   COOKED_MUTTON,
   COOKED_PORKCHOP(new String[]{"PORK", "GRILLED_PORK"}),
   COOKED_RABBIT,
   COOKED_SALMON(1, new String[]{"COOKED_FISH"}),
   COOKIE,
   COPPER_BLOCK,
   COPPER_INGOT,
   COPPER_ORE,
   CORNFLOWER(4, 14, new String[0]),
   COW_SPAWN_EGG(92, new String[]{"MONSTER_EGG"}),
   CRACKED_DEEPSLATE_BRICKS,
   CRACKED_DEEPSLATE_TILES,
   CRACKED_NETHER_BRICKS(2, new String[]{"NETHER_BRICKS"}),
   CRACKED_POLISHED_BLACKSTONE_BRICKS(0, 16, new String[]{"POLISHED_BLACKSTONE_BRICKS"}),
   CRACKED_STONE_BRICKS(2, new String[]{"SMOOTH_BRICK"}),
   CRAFTING_TABLE(new String[]{"WORKBENCH"}),
   CREEPER_BANNER_PATTERN,
   CREEPER_HEAD(4, new String[]{"SKULL", "SKULL_ITEM"}),
   CREEPER_SPAWN_EGG(50, new String[]{"MONSTER_EGG"}),
   CRIMSON_BUTTON(16),
   CRIMSON_DOOR(16),
   CRIMSON_FENCE(16),
   CRIMSON_FENCE_GATE(16),
   CRIMSON_FUNGUS(16),
   CRIMSON_HANGING_SIGN(20),
   CRIMSON_HYPHAE(16),
   CRIMSON_NYLIUM(16),
   CRIMSON_PLANKS(16),
   CRIMSON_PRESSURE_PLATE(16),
   CRIMSON_ROOTS(16),
   CRIMSON_SIGN(16),
   CRIMSON_SLAB(16),
   CRIMSON_STAIRS(16),
   CRIMSON_STEM(16),
   CRIMSON_TRAPDOOR(16),
   CROSSBOW,
   CRYING_OBSIDIAN(16),
   CUT_COPPER,
   CUT_COPPER_SLAB,
   CUT_COPPER_STAIRS,
   CUT_RED_SANDSTONE(13),
   CUT_RED_SANDSTONE_SLAB(new String[]{"STONE_SLAB2"}),
   CUT_SANDSTONE(13),
   CUT_SANDSTONE_SLAB(1, new String[]{"STEP"}),
   CYAN_BANNER(6, new String[]{"STANDING_BANNER", "BANNER"}),
   CYAN_BED(9, new String[]{"BED"}),
   CYAN_CANDLE,
   CYAN_CARPET(9, new String[]{"CARPET"}),
   CYAN_CONCRETE(9, new String[]{"CONCRETE"}),
   CYAN_CONCRETE_POWDER(9, new String[]{"CONCRETE_POWDER"}),
   CYAN_DYE(6, new String[]{"INK_SACK"}),
   CYAN_GLAZED_TERRACOTTA(9, 12, new String[0]),
   CYAN_SHULKER_BOX,
   CYAN_STAINED_GLASS(9, new String[]{"STAINED_GLASS"}),
   CYAN_STAINED_GLASS_PANE(9, new String[]{"STAINED_GLASS_PANE"}),
   CYAN_TERRACOTTA(9, new String[]{"STAINED_CLAY"}),
   CYAN_WOOL(9, new String[]{"WOOL"}),
   DAMAGED_ANVIL(2, new String[]{"ANVIL"}),
   DANDELION(new String[]{"YELLOW_FLOWER"}),
   DANGER_POTTERY_SHERD(20),
   DARK_OAK_BOAT(new String[]{"BOAT_DARK_OAK"}),
   DARK_OAK_BUTTON(new String[]{"WOOD_BUTTON"}),
   DARK_OAK_CHEST_BOAT(19),
   DARK_OAK_DOOR(new String[]{"DARK_OAK_DOOR", "DARK_OAK_DOOR_ITEM"}),
   DARK_OAK_FENCE,
   DARK_OAK_FENCE_GATE,
   DARK_OAK_HANGING_SIGN(20),
   DARK_OAK_LEAVES(1, new String[]{"LEAVES_2"}),
   DARK_OAK_LOG(1, new String[]{"LOG_2"}),
   DARK_OAK_PLANKS(5, new String[]{"WOOD"}),
   DARK_OAK_PRESSURE_PLATE(new String[]{"WOOD_PLATE"}),
   DARK_OAK_SAPLING(5, new String[]{"SAPLING"}),
   DARK_OAK_SIGN(new String[]{"SIGN_POST", "SIGN"}),
   DARK_OAK_SLAB(5, new String[]{"WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"}),
   DARK_OAK_STAIRS,
   DARK_OAK_TRAPDOOR(new String[]{"TRAP_DOOR"}),
   DARK_OAK_WOOD(1, new String[]{"LOG_2"}),
   DARK_PRISMARINE(1, new String[]{"PRISMARINE"}),
   DARK_PRISMARINE_SLAB(13),
   DARK_PRISMARINE_STAIRS(13),
   DAYLIGHT_DETECTOR(new String[]{"DAYLIGHT_DETECTOR_INVERTED"}),
   DEAD_BRAIN_CORAL(13),
   DEAD_BRAIN_CORAL_BLOCK(13),
   DEAD_BRAIN_CORAL_FAN(13),
   DEAD_BUBBLE_CORAL(13),
   DEAD_BUBBLE_CORAL_BLOCK(13),
   DEAD_BUBBLE_CORAL_FAN(13),
   DEAD_BUSH,
   DEAD_FIRE_CORAL(13),
   DEAD_FIRE_CORAL_BLOCK(13),
   DEAD_FIRE_CORAL_FAN(13),
   DEAD_HORN_CORAL(13),
   DEAD_HORN_CORAL_BLOCK(13),
   DEAD_HORN_CORAL_FAN(13),
   DEAD_TUBE_CORAL(13),
   DEAD_TUBE_CORAL_BLOCK(13),
   DEAD_TUBE_CORAL_FAN(13),
   DECORATED_POT(20),
   DEEPSLATE,
   DEEPSLATE_BRICK_SLAB,
   DEEPSLATE_BRICK_STAIRS,
   DEEPSLATE_BRICK_WALL,
   DEEPSLATE_BRICKS,
   DEEPSLATE_COAL_ORE,
   DEEPSLATE_COPPER_ORE,
   DEEPSLATE_DIAMOND_ORE,
   DEEPSLATE_EMERALD_ORE,
   DEEPSLATE_GOLD_ORE,
   DEEPSLATE_IRON_ORE,
   DEEPSLATE_LAPIS_ORE,
   DEEPSLATE_REDSTONE_ORE,
   DEEPSLATE_TILE_SLAB,
   DEEPSLATE_TILE_STAIRS,
   DEEPSLATE_TILE_WALL,
   DEEPSLATE_TILES,
   DETECTOR_RAIL,
   DIAMOND,
   DIAMOND_AXE,
   DIAMOND_BLOCK,
   DIAMOND_BOOTS,
   DIAMOND_CHESTPLATE,
   DIAMOND_HELMET,
   DIAMOND_HOE,
   DIAMOND_HORSE_ARMOR(new String[]{"DIAMOND_BARDING"}),
   DIAMOND_LEGGINGS,
   DIAMOND_ORE,
   DIAMOND_PICKAXE,
   DIAMOND_SHOVEL(new String[]{"DIAMOND_SPADE"}),
   DIAMOND_SWORD,
   DIORITE(3, new String[]{"STONE"}),
   DIORITE_SLAB,
   DIORITE_STAIRS,
   DIORITE_WALL,
   DIRT,
   DIRT_PATH(new String[]{"GRASS_PATH"}),
   DISC_FRAGMENT_5(19, new String[]{"DISC_FRAGMENT"}),
   DISPENSER,
   DOLPHIN_SPAWN_EGG(0, 13, new String[0]),
   DONKEY_SPAWN_EGG(32, new String[]{"MONSTER_EGG"}),
   DRAGON_BREATH(new String[]{"DRAGONS_BREATH"}),
   DRAGON_EGG,
   DRAGON_HEAD(5, 9, new String[]{"SKULL", "SKULL_ITEM"}),
   DRIED_KELP(13),
   DRIED_KELP_BLOCK(13),
   DRIPSTONE_BLOCK,
   DROPPER,
   DROWNED_SPAWN_EGG(0, 13, new String[0]),
   DUNE_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   ECHO_SHARD(19),
   EGG,
   ELDER_GUARDIAN_SPAWN_EGG(4, new String[]{"MONSTER_EGG"}),
   ELYTRA,
   EMERALD,
   EMERALD_BLOCK,
   EMERALD_ORE,
   ENCHANTED_BOOK,
   ENCHANTED_GOLDEN_APPLE(1, new String[]{"GOLDEN_APPLE"}),
   ENCHANTING_TABLE(new String[]{"ENCHANTMENT_TABLE"}),
   END_CRYSTAL,
   END_PORTAL_FRAME(new String[]{"ENDER_PORTAL_FRAME"}),
   END_ROD(0, 9, new String[0]),
   END_STONE(new String[]{"ENDER_STONE"}),
   END_STONE_BRICK_SLAB(6, new String[]{"STEP"}),
   END_STONE_BRICK_STAIRS(new String[]{"SMOOTH_STAIRS"}),
   END_STONE_BRICK_WALL,
   END_STONE_BRICKS(new String[]{"END_BRICKS"}),
   ENDER_CHEST,
   ENDER_DRAGON_SPAWN_EGG(63, new String[]{"MONSTER_EGG"}),
   ENDER_EYE(new String[]{"EYE_OF_ENDER"}),
   ENDER_PEARL,
   ENDERMAN_SPAWN_EGG(58, new String[]{"MONSTER_EGG"}),
   ENDERMITE_SPAWN_EGG(67, new String[]{"MONSTER_EGG"}),
   EVOKER_SPAWN_EGG(34, new String[]{"MONSTER_EGG"}),
   EXPERIENCE_BOTTLE(new String[]{"EXP_BOTTLE"}),
   EXPLORER_POTTERY_SHERD(20),
   EXPOSED_COPPER,
   EXPOSED_CUT_COPPER,
   EXPOSED_CUT_COPPER_SLAB,
   EXPOSED_CUT_COPPER_STAIRS,
   EYE_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   FARMLAND(new String[]{"SOIL"}),
   FEATHER,
   FERMENTED_SPIDER_EYE,
   FERN(2, new String[]{"LONG_GRASS", "TALLGRASS"}),
   FILLED_MAP(new String[]{"MAP"}),
   FIRE_CHARGE(new String[]{"FIREBALL"}),
   FIRE_CORAL(13),
   FIRE_CORAL_BLOCK(13),
   FIRE_CORAL_FAN(13),
   FIREWORK_ROCKET(new String[]{"FIREWORK"}),
   FIREWORK_STAR(new String[]{"FIREWORK_CHARGE"}),
   FISHING_ROD,
   FLETCHING_TABLE(0, 14, new String[0]),
   FLINT,
   FLINT_AND_STEEL,
   FLOWER_BANNER_PATTERN,
   FLOWER_POT(new String[]{"FLOWER_POT", "FLOWER_POT_ITEM"}),
   FLOWERING_AZALEA,
   FLOWERING_AZALEA_LEAVES,
   FOX_SPAWN_EGG(14),
   FRIEND_POTTERY_SHERD(20),
   FROG_SPAWN_EGG(19),
   FROGSPAWN(19),
   FURNACE(new String[]{"BURNING_FURNACE"}),
   FURNACE_MINECART(new String[]{"POWERED_MINECART"}),
   GHAST_SPAWN_EGG(56, new String[]{"MONSTER_EGG"}),
   GHAST_TEAR,
   GILDED_BLACKSTONE(16),
   GLASS,
   GLASS_BOTTLE,
   GLASS_PANE(new String[]{"THIN_GLASS"}),
   GLISTERING_MELON_SLICE(new String[]{"SPECKLED_MELON"}),
   GLOBE_BANNER_PATTERN,
   GLOW_BERRIES,
   GLOW_INK_SAC,
   GLOW_ITEM_FRAME,
   GLOW_LICHEN,
   GLOW_SQUID_SPAWN_EGG,
   GLOWSTONE,
   GLOWSTONE_DUST,
   GOAT_HORN(19),
   GOAT_SPAWN_EGG,
   GOLD_BLOCK,
   GOLD_INGOT,
   GOLD_NUGGET,
   GOLD_ORE,
   GOLDEN_APPLE,
   GOLDEN_AXE(new String[]{"GOLD_AXE"}),
   GOLDEN_BOOTS(new String[]{"GOLD_BOOTS"}),
   GOLDEN_CARROT,
   GOLDEN_CHESTPLATE(new String[]{"GOLD_CHESTPLATE"}),
   GOLDEN_HELMET(new String[]{"GOLD_HELMET"}),
   GOLDEN_HOE(new String[]{"GOLD_HOE"}),
   GOLDEN_HORSE_ARMOR(new String[]{"GOLD_BARDING"}),
   GOLDEN_LEGGINGS(new String[]{"GOLD_LEGGINGS"}),
   GOLDEN_PICKAXE(new String[]{"GOLD_PICKAXE"}),
   GOLDEN_SHOVEL(new String[]{"GOLD_SPADE"}),
   GOLDEN_SWORD(new String[]{"GOLD_SWORD"}),
   GRANITE(1, new String[]{"STONE"}),
   GRANITE_SLAB,
   GRANITE_STAIRS,
   GRANITE_WALL,
   SHORT_GRASS(1, new String[]{"LONG_GRASS", "TALLGRASS"}),
   GRASS_BLOCK(new String[]{"GRASS"}),
   GRASS_PATH,
   GRAVEL,
   GRAY_BANNER(8, new String[]{"STANDING_BANNER", "BANNER"}),
   GRAY_BED(7, new String[]{"BED"}),
   GRAY_CANDLE,
   GRAY_CARPET(7, new String[]{"CARPET"}),
   GRAY_CONCRETE(7, new String[]{"CONCRETE"}),
   GRAY_CONCRETE_POWDER(7, new String[]{"CONCRETE_POWDER"}),
   GRAY_DYE(8, new String[]{"INK_SACK"}),
   GRAY_GLAZED_TERRACOTTA(7, 12, new String[0]),
   GRAY_SHULKER_BOX,
   GRAY_STAINED_GLASS(7, new String[]{"STAINED_GLASS"}),
   GRAY_STAINED_GLASS_PANE(7, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   GRAY_TERRACOTTA(7, new String[]{"STAINED_CLAY"}),
   GRAY_WOOL(7, new String[]{"WOOL"}),
   GREEN_BANNER(2, new String[]{"STANDING_BANNER", "BANNER"}),
   GREEN_BED(13, new String[]{"BED"}),
   GREEN_CANDLE,
   GREEN_CARPET(13, new String[]{"CARPET"}),
   GREEN_CONCRETE(13, new String[]{"CONCRETE"}),
   GREEN_CONCRETE_POWDER(13, new String[]{"CONCRETE_POWDER"}),
   GREEN_DYE(2, new String[]{"INK_SACK", "CACTUS_GREEN"}),
   GREEN_GLAZED_TERRACOTTA(13, 12, new String[0]),
   GREEN_SHULKER_BOX,
   GREEN_STAINED_GLASS(13, new String[]{"STAINED_GLASS"}),
   GREEN_STAINED_GLASS_PANE(13, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   GREEN_TERRACOTTA(13, new String[]{"STAINED_CLAY"}),
   GREEN_WOOL(13, new String[]{"WOOL"}),
   GRINDSTONE(0, 14, new String[]{"FURNACE"}),
   GUARDIAN_SPAWN_EGG(68, new String[]{"MONSTER_EGG"}),
   GUNPOWDER(new String[]{"SULPHUR"}),
   HANGING_ROOTS,
   HAY_BLOCK,
   HEART_OF_THE_SEA(13),
   HEART_POTTERY_SHERD(20),
   HEARTBREAK_POTTERY_SHERD(20),
   HEAVY_WEIGHTED_PRESSURE_PLATE(new String[]{"IRON_PLATE"}),
   HOGLIN_SPAWN_EGG(0, 16, new String[]{"MONSTER_EGG"}),
   HONEY_BLOCK(0, 15, new String[0]),
   HONEY_BOTTLE(0, 15, new String[0]),
   HONEYCOMB(15),
   HONEYCOMB_BLOCK(15),
   HOPPER,
   HOPPER_MINECART,
   HORN_CORAL(13),
   HORN_CORAL_BLOCK(13),
   HORN_CORAL_FAN(13),
   HORSE_SPAWN_EGG(100, new String[]{"MONSTER_EGG"}),
   HOST_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   HOWL_POTTERY_SHERD(20),
   HUSK_SPAWN_EGG(23, new String[]{"MONSTER_EGG"}),
   ICE,
   INFESTED_CHISELED_STONE_BRICKS(5, new String[]{"MONSTER_EGGS"}),
   INFESTED_COBBLESTONE(1, new String[]{"MONSTER_EGGS"}),
   INFESTED_CRACKED_STONE_BRICKS(4, new String[]{"MONSTER_EGGS"}),
   INFESTED_DEEPSLATE,
   INFESTED_MOSSY_STONE_BRICKS(3, new String[]{"MONSTER_EGGS"}),
   INFESTED_STONE(new String[]{"MONSTER_EGGS"}),
   INFESTED_STONE_BRICKS(2, new String[]{"MONSTER_EGGS"}),
   INK_SAC(new String[]{"INK_SACK"}),
   IRON_AXE,
   IRON_BARS(new String[]{"IRON_FENCE"}),
   IRON_BLOCK,
   IRON_BOOTS,
   IRON_CHESTPLATE,
   IRON_DOOR(new String[]{"IRON_DOOR_BLOCK"}),
   IRON_GOLEM_SPAWN_EGG(99, new String[]{"MONSTER_EGG"}),
   IRON_HELMET,
   IRON_HOE,
   IRON_HORSE_ARMOR(new String[]{"IRON_BARDING"}),
   IRON_INGOT,
   IRON_LEGGINGS,
   IRON_NUGGET,
   IRON_ORE,
   IRON_PICKAXE,
   IRON_SHOVEL(new String[]{"IRON_SPADE"}),
   IRON_SWORD,
   IRON_TRAPDOOR,
   ITEM_FRAME,
   JACK_O_LANTERN,
   JIGSAW(0, 14, new String[0]),
   JUKEBOX,
   JUNGLE_BOAT(new String[]{"BOAT_JUNGLE"}),
   JUNGLE_BUTTON(new String[]{"WOOD_BUTTON"}),
   JUNGLE_CHEST_BOAT(19),
   JUNGLE_DOOR(new String[]{"JUNGLE_DOOR", "JUNGLE_DOOR_ITEM"}),
   JUNGLE_FENCE,
   JUNGLE_FENCE_GATE,
   JUNGLE_HANGING_SIGN(20),
   JUNGLE_LEAVES(3, new String[]{"LEAVES"}),
   JUNGLE_LOG(3, new String[]{"LOG"}),
   JUNGLE_PLANKS(3, new String[]{"WOOD"}),
   JUNGLE_PRESSURE_PLATE(new String[]{"WOOD_PLATE"}),
   JUNGLE_SAPLING(3, new String[]{"SAPLING"}),
   JUNGLE_SIGN(new String[]{"SIGN_POST", "SIGN"}),
   JUNGLE_SLAB(3, new String[]{"WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"}),
   JUNGLE_STAIRS(new String[]{"JUNGLE_WOOD_STAIRS"}),
   JUNGLE_TRAPDOOR(new String[]{"TRAP_DOOR"}),
   JUNGLE_WOOD(3, new String[]{"LOG"}),
   KELP(13),
   KNOWLEDGE_BOOK(0, 12, new String[]{"BOOK"}),
   LADDER,
   LANTERN(0, 14, new String[0]),
   LAPIS_BLOCK,
   LAPIS_LAZULI(4, new String[]{"INK_SACK"}),
   LAPIS_ORE,
   LARGE_AMETHYST_BUD,
   LARGE_FERN(3, new String[]{"DOUBLE_PLANT"}),
   LAVA_BUCKET,
   LEAD(new String[]{"LEASH"}),
   LEATHER,
   LEATHER_BOOTS,
   LEATHER_CHESTPLATE,
   LEATHER_HELMET,
   LEATHER_HORSE_ARMOR(0, 14, new String[]{"IRON_HORSE_ARMOR"}),
   LEATHER_LEGGINGS,
   LECTERN(0, 14, new String[0]),
   LEVER,
   LIGHT,
   LIGHT_BLUE_BANNER(12, new String[]{"STANDING_BANNER", "BANNER"}),
   LIGHT_BLUE_BED(3, new String[]{"BED"}),
   LIGHT_BLUE_CANDLE,
   LIGHT_BLUE_CARPET(3, new String[]{"CARPET"}),
   LIGHT_BLUE_CONCRETE(3, new String[]{"CONCRETE"}),
   LIGHT_BLUE_CONCRETE_POWDER(3, new String[]{"CONCRETE_POWDER"}),
   LIGHT_BLUE_DYE(12, new String[]{"INK_SACK"}),
   LIGHT_BLUE_GLAZED_TERRACOTTA(3, 12, new String[0]),
   LIGHT_BLUE_SHULKER_BOX,
   LIGHT_BLUE_STAINED_GLASS(3, new String[]{"STAINED_GLASS"}),
   LIGHT_BLUE_STAINED_GLASS_PANE(3, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   LIGHT_BLUE_TERRACOTTA(3, new String[]{"STAINED_CLAY"}),
   LIGHT_BLUE_WOOL(3, new String[]{"WOOL"}),
   LIGHT_GRAY_BANNER(7, new String[]{"STANDING_BANNER", "BANNER"}),
   LIGHT_GRAY_BED(8, new String[]{"BED"}),
   LIGHT_GRAY_CANDLE,
   LIGHT_GRAY_CARPET(8, new String[]{"CARPET"}),
   LIGHT_GRAY_CONCRETE(8, new String[]{"CONCRETE"}),
   LIGHT_GRAY_CONCRETE_POWDER(8, new String[]{"CONCRETE_POWDER"}),
   LIGHT_GRAY_DYE(7, new String[]{"INK_SACK"}),
   LIGHT_GRAY_GLAZED_TERRACOTTA(0, 12, new String[]{"STAINED_CLAY", "LIGHT_GRAY_TERRACOTTA", "SILVER_GLAZED_TERRACOTTA"}),
   LIGHT_GRAY_SHULKER_BOX(new String[]{"SILVER_SHULKER_BOX"}),
   LIGHT_GRAY_STAINED_GLASS(8, new String[]{"STAINED_GLASS"}),
   LIGHT_GRAY_STAINED_GLASS_PANE(8, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   LIGHT_GRAY_TERRACOTTA(8, new String[]{"STAINED_CLAY"}),
   LIGHT_GRAY_WOOL(8, new String[]{"WOOL"}),
   LIGHT_WEIGHTED_PRESSURE_PLATE(new String[]{"GOLD_PLATE"}),
   LIGHTNING_ROD,
   LILAC(1, new String[]{"DOUBLE_PLANT"}),
   LILY_OF_THE_VALLEY(15, 14, new String[0]),
   LILY_PAD(new String[]{"WATER_LILY"}),
   LIME_BANNER(10, new String[]{"STANDING_BANNER", "BANNER"}),
   LIME_BED(5, new String[]{"BED"}),
   LIME_CANDLE,
   LIME_CARPET(5, new String[]{"CARPET"}),
   LIME_CONCRETE(5, new String[]{"CONCRETE"}),
   LIME_CONCRETE_POWDER(5, new String[]{"CONCRETE_POWDER"}),
   LIME_DYE(10, new String[]{"INK_SACK"}),
   LIME_GLAZED_TERRACOTTA(5, 12, new String[0]),
   LIME_SHULKER_BOX,
   LIME_STAINED_GLASS(5, new String[]{"STAINED_GLASS"}),
   LIME_STAINED_GLASS_PANE(5, new String[]{"STAINED_GLASS_PANE"}),
   LIME_TERRACOTTA(5, new String[]{"STAINED_CLAY"}),
   LIME_WOOL(5, new String[]{"WOOL"}),
   LINGERING_POTION,
   LLAMA_SPAWN_EGG(103, new String[]{"MONSTER_EGG"}),
   LODESTONE(16),
   LOOM(14),
   MAGENTA_BANNER(13, new String[]{"STANDING_BANNER", "BANNER"}),
   MAGENTA_BED(2, new String[]{"BED"}),
   MAGENTA_CANDLE,
   MAGENTA_CARPET(2, new String[]{"CARPET"}),
   MAGENTA_CONCRETE(2, new String[]{"CONCRETE"}),
   MAGENTA_CONCRETE_POWDER(2, new String[]{"CONCRETE_POWDER"}),
   MAGENTA_DYE(13, new String[]{"INK_SACK"}),
   MAGENTA_GLAZED_TERRACOTTA(2, 12, new String[0]),
   MAGENTA_SHULKER_BOX,
   MAGENTA_STAINED_GLASS(2, new String[]{"STAINED_GLASS"}),
   MAGENTA_STAINED_GLASS_PANE(2, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   MAGENTA_TERRACOTTA(2, new String[]{"STAINED_CLAY"}),
   MAGENTA_WOOL(2, new String[]{"WOOL"}),
   MAGMA_BLOCK(0, 10, new String[]{"MAGMA"}),
   MAGMA_CREAM,
   MAGMA_CUBE_SPAWN_EGG(62, new String[]{"MONSTER_EGG"}),
   MANGROVE_BOAT(19),
   MANGROVE_BUTTON(19),
   MANGROVE_CHEST_BOAT(19),
   MANGROVE_DOOR(19),
   MANGROVE_FENCE(19),
   MANGROVE_FENCE_GATE(19),
   MANGROVE_HANGING_SIGN(20),
   MANGROVE_LEAVES(19),
   MANGROVE_LOG(19),
   MANGROVE_PLANKS(19),
   MANGROVE_PRESSURE_PLATE(19),
   MANGROVE_PROPAGULE(19),
   MANGROVE_ROOTS(19),
   MANGROVE_SIGN(19),
   MANGROVE_SLAB(19),
   MANGROVE_STAIRS(19),
   MANGROVE_TRAPDOOR(19),
   MANGROVE_WOOD(19),
   MAP(new String[]{"EMPTY_MAP"}),
   MEDIUM_AMETHYST_BUD,
   MELON(new String[]{"MELON_BLOCK"}),
   MELON_SEEDS,
   MELON_SLICE(new String[]{"MELON"}),
   MILK_BUCKET,
   MINECART,
   MINER_POTTERY_SHERD(20),
   MOJANG_BANNER_PATTERN(new String[]{"PAPER"}),
   MOOSHROOM_SPAWN_EGG(96, new String[]{"MONSTER_EGG"}),
   MOSS_BLOCK,
   MOSS_CARPET,
   MOSSY_COBBLESTONE,
   MOSSY_COBBLESTONE_SLAB(3, new String[]{"STEP"}),
   MOSSY_COBBLESTONE_STAIRS,
   MOSSY_COBBLESTONE_WALL(1, new String[]{"COBBLE_WALL", "COBBLESTONE_WALL"}),
   MOSSY_STONE_BRICK_SLAB(5, new String[]{"STEP"}),
   MOSSY_STONE_BRICK_STAIRS(new String[]{"SMOOTH_STAIRS"}),
   MOSSY_STONE_BRICK_WALL,
   MOSSY_STONE_BRICKS(1, new String[]{"SMOOTH_BRICK"}),
   MOURNER_POTTERY_SHERD(20),
   MUD(19),
   MUD_BRICK_SLAB(19),
   MUD_BRICK_STAIRS(19),
   MUD_BRICK_WALL(19),
   MUD_BRICKS(19),
   MUDDY_MANGROVE_ROOTS(19),
   MULE_SPAWN_EGG(32, new String[]{"MONSTER_EGG"}),
   MUSHROOM_STEM(new String[]{"BROWN_MUSHROOM"}),
   MUSHROOM_STEW(new String[]{"MUSHROOM_SOUP"}),
   MUSIC_DISC_11(new String[]{"GOLD_RECORD"}),
   MUSIC_DISC_13(new String[]{"GREEN_RECORD"}),
   MUSIC_DISC_5(19),
   MUSIC_DISC_BLOCKS(new String[]{"RECORD_3"}),
   MUSIC_DISC_CAT(new String[]{"RECORD_4"}),
   MUSIC_DISC_CHIRP(new String[]{"RECORD_5"}),
   MUSIC_DISC_FAR(new String[]{"RECORD_6"}),
   MUSIC_DISC_MALL(new String[]{"RECORD_7"}),
   MUSIC_DISC_MELLOHI(new String[]{"RECORD_8"}),
   MUSIC_DISC_OTHERSIDE(18),
   MUSIC_DISC_PIGSTEP(16),
   MUSIC_DISC_RELIC(20),
   MUSIC_DISC_STAL(new String[]{"RECORD_9"}),
   MUSIC_DISC_STRAD(new String[]{"RECORD_10"}),
   MUSIC_DISC_WAIT(new String[]{"RECORD_11"}),
   MUSIC_DISC_WARD(new String[]{"RECORD_12"}),
   MUTTON,
   MYCELIUM(new String[]{"MYCEL"}),
   NAME_TAG,
   NAUTILUS_SHELL(13),
   NETHER_BRICK(new String[]{"NETHER_BRICK_ITEM"}),
   NETHER_BRICK_FENCE(new String[]{"NETHER_FENCE"}),
   NETHER_BRICK_SLAB(6, new String[]{"STEP"}),
   NETHER_BRICK_STAIRS,
   NETHER_BRICK_WALL,
   NETHER_BRICKS(new String[]{"NETHER_BRICK"}),
   NETHER_GOLD_ORE(16),
   NETHER_QUARTZ_ORE(new String[]{"QUARTZ_ORE"}),
   NETHER_SPROUTS(16),
   NETHER_STAR,
   NETHER_WART(new String[]{"NETHER_WARTS", "NETHER_STALK"}),
   NETHER_WART_BLOCK,
   NETHERITE_AXE(16),
   NETHERITE_BLOCK(16),
   NETHERITE_BOOTS(16),
   NETHERITE_CHESTPLATE(16),
   NETHERITE_HELMET(16),
   NETHERITE_HOE(16),
   NETHERITE_INGOT(16),
   NETHERITE_LEGGINGS(16),
   NETHERITE_PICKAXE(16),
   NETHERITE_SCRAP(16),
   NETHERITE_SHOVEL(16),
   NETHERITE_SWORD(16),
   NETHERITE_UPGRADE_SMITHING_TEMPLATE(20),
   NETHERRACK,
   NOTE_BLOCK,
   OAK_BOAT(new String[]{"BOAT"}),
   OAK_BUTTON(new String[]{"WOOD_BUTTON"}),
   OAK_CHEST_BOAT(19),
   OAK_DOOR(new String[]{"WOODEN_DOOR", "WOOD_DOOR"}),
   OAK_FENCE(new String[]{"FENCE"}),
   OAK_FENCE_GATE(new String[]{"FENCE_GATE"}),
   OAK_HANGING_SIGN(20),
   OAK_LEAVES(new String[]{"LEAVES"}),
   OAK_LOG(new String[]{"LOG"}),
   OAK_PLANKS(new String[]{"WOOD"}),
   OAK_PRESSURE_PLATE(new String[]{"WOOD_PLATE"}),
   OAK_SAPLING(new String[]{"SAPLING"}),
   OAK_SIGN(new String[]{"SIGN_POST", "SIGN"}),
   OAK_SLAB(new String[]{"WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"}),
   OAK_STAIRS(new String[]{"WOOD_STAIRS"}),
   OAK_TRAPDOOR(new String[]{"TRAP_DOOR"}),
   OAK_WOOD(new String[]{"LOG"}),
   OBSERVER,
   OBSIDIAN,
   OCELOT_SPAWN_EGG(98, new String[]{"MONSTER_EGG"}),
   OCHRE_FROGLIGHT(19),
   ORANGE_BANNER(14, new String[]{"STANDING_BANNER", "BANNER"}),
   ORANGE_BED(new String[]{"BED"}),
   ORANGE_CANDLE,
   ORANGE_CARPET(1, new String[]{"CARPET"}),
   ORANGE_CONCRETE(1, new String[]{"CONCRETE"}),
   ORANGE_CONCRETE_POWDER(1, new String[]{"CONCRETE_POWDER"}),
   ORANGE_DYE(14, new String[]{"INK_SACK"}),
   ORANGE_GLAZED_TERRACOTTA(1, 12, new String[0]),
   ORANGE_SHULKER_BOX,
   ORANGE_STAINED_GLASS(1, new String[]{"STAINED_GLASS"}),
   ORANGE_STAINED_GLASS_PANE(1, new String[]{"STAINED_GLASS_PANE"}),
   ORANGE_TERRACOTTA(1, new String[]{"STAINED_CLAY"}),
   ORANGE_TULIP(5, new String[]{"RED_ROSE"}),
   ORANGE_WOOL(1, new String[]{"WOOL"}),
   OXEYE_DAISY(8, new String[]{"RED_ROSE"}),
   OXIDIZED_COPPER,
   OXIDIZED_CUT_COPPER,
   OXIDIZED_CUT_COPPER_SLAB,
   OXIDIZED_CUT_COPPER_STAIRS,
   PACKED_ICE,
   PACKED_MUD,
   PAINTING,
   PANDA_SPAWN_EGG(14),
   PAPER,
   PARROT_SPAWN_EGG(105, new String[]{"MONSTER_EGG"}),
   PEARLESCENT_FROGLIGHT(19),
   PEONY(5, new String[]{"DOUBLE_PLANT"}),
   PETRIFIED_OAK_SLAB(new String[]{"WOOD_STEP"}),
   PHANTOM_MEMBRANE(13),
   PHANTOM_SPAWN_EGG(0, 13, new String[0]),
   PIG_SPAWN_EGG(90, new String[]{"MONSTER_EGG"}),
   PIGLIN_BANNER_PATTERN(16),
   PIGLIN_BRUTE_SPAWN_EGG(16),
   PIGLIN_HEAD(20),
   PIGLIN_SPAWN_EGG(57, new String[]{"MONSTER_EGG"}),
   PILLAGER_SPAWN_EGG(14),
   PINK_BANNER(9, new String[]{"STANDING_BANNER", "BANNER"}),
   PINK_BED(new String[]{"BED"}),
   PINK_CANDLE,
   PINK_CARPET(6, new String[]{"CARPET"}),
   PINK_CONCRETE(6, new String[]{"CONCRETE"}),
   PINK_CONCRETE_POWDER(6, new String[]{"CONCRETE_POWDER"}),
   PINK_DYE(9, new String[]{"INK_SACK"}),
   PINK_GLAZED_TERRACOTTA(6, 12, new String[0]),
   PINK_PETALS(20),
   PINK_SHULKER_BOX,
   PINK_STAINED_GLASS(6, new String[]{"STAINED_GLASS"}),
   PINK_STAINED_GLASS_PANE(6, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   PINK_TERRACOTTA(6, new String[]{"STAINED_CLAY"}),
   PINK_TULIP(7, new String[]{"RED_ROSE"}),
   PINK_WOOL(6, new String[]{"WOOL"}),
   PISTON(new String[]{"PISTON_BASE"}),
   PITCHER_PLANT(20),
   PITCHER_POD(20),
   PLAYER_HEAD(3, new String[]{"SKULL", "SKULL_ITEM"}),
   PLENTY_POTTERY_SHERD(20),
   PODZOL(2, new String[]{"DIRT"}),
   POINTED_DRIPSTONE,
   POISONOUS_POTATO,
   POLAR_BEAR_SPAWN_EGG(102, new String[]{"MONSTER_EGG"}),
   POLISHED_ANDESITE(6, new String[]{"STONE"}),
   POLISHED_ANDESITE_SLAB,
   POLISHED_ANDESITE_STAIRS,
   POLISHED_BASALT(16),
   POLISHED_BLACKSTONE(16),
   POLISHED_BLACKSTONE_BRICK_SLAB(16),
   POLISHED_BLACKSTONE_BRICK_STAIRS(16),
   POLISHED_BLACKSTONE_BRICK_WALL(16),
   POLISHED_BLACKSTONE_BRICKS(16),
   POLISHED_BLACKSTONE_BUTTON(16),
   POLISHED_BLACKSTONE_PRESSURE_PLATE(16),
   POLISHED_BLACKSTONE_SLAB(16),
   POLISHED_BLACKSTONE_STAIRS(16),
   POLISHED_BLACKSTONE_WALL(16),
   POLISHED_DEEPSLATE,
   POLISHED_DEEPSLATE_SLAB,
   POLISHED_DEEPSLATE_STAIRS,
   POLISHED_DEEPSLATE_WALL,
   POLISHED_DIORITE(4, new String[]{"STONE"}),
   POLISHED_DIORITE_SLAB,
   POLISHED_DIORITE_STAIRS,
   POLISHED_GRANITE(2, new String[]{"STONE"}),
   POLISHED_GRANITE_SLAB,
   POLISHED_GRANITE_STAIRS,
   POPPED_CHORUS_FRUIT(new String[]{"CHORUS_FRUIT_POPPED"}),
   POPPY(new String[]{"RED_ROSE"}),
   PORKCHOP(new String[]{"PORK"}),
   POTATO(new String[]{"POTATO_ITEM"}),
   POTION,
   POTTED_ACACIA_SAPLING(4, new String[]{"SAPLING", "FLOWER_POT"}),
   POTTED_ALLIUM(2, new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_AZALEA_BUSH,
   POTTED_AZURE_BLUET(3, new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_BAMBOO,
   POTTED_BIRCH_SAPLING(2, new String[]{"SAPLING", "FLOWER_POT"}),
   POTTED_BLUE_ORCHID(1, new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_BROWN_MUSHROOM(new String[]{"FLOWER_POT"}),
   POTTED_CACTUS(new String[]{"FLOWER_POT"}),
   POTTED_CORNFLOWER,
   POTTED_CRIMSON_FUNGUS(16),
   POTTED_CRIMSON_ROOTS(16),
   POTTED_DANDELION(new String[]{"YELLOW_FLOWER", "FLOWER_POT"}),
   POTTED_DARK_OAK_SAPLING(5, new String[]{"SAPLING", "FLOWER_POT"}),
   POTTED_DEAD_BUSH(new String[]{"FLOWER_POT"}),
   POTTED_FERN(2, new String[]{"LONG_GRASS", "FLOWER_POT"}),
   POTTED_FLOWERING_AZALEA_BUSH,
   POTTED_JUNGLE_SAPLING(3, new String[]{"SAPLING", "FLOWER_POT"}),
   POTTED_LILY_OF_THE_VALLEY,
   POTTED_MANGROVE_PROPAGULE(19),
   POTTED_OAK_SAPLING(new String[]{"SAPLING", "FLOWER_POT"}),
   POTTED_ORANGE_TULIP(5, new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_OXEYE_DAISY(8, new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_PINK_TULIP(7, new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_POPPY(new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_RED_MUSHROOM(new String[]{"FLOWER_POT"}),
   POTTED_RED_TULIP(4, new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_SPRUCE_SAPLING(1, new String[]{"SAPLING", "FLOWER_POT"}),
   POTTED_WARPED_FUNGUS(16),
   POTTED_WARPED_ROOTS(16),
   POTTED_WHITE_TULIP(6, new String[]{"RED_ROSE", "FLOWER_POT"}),
   POTTED_WITHER_ROSE,
   POTTERY_SHARD_ARCHER(20),
   POTTERY_SHARD_ARMS_UP(20),
   POTTERY_SHARD_PRIZE(20),
   POTTERY_SHARD_SKULL(20),
   POWDER_SNOW_BUCKET,
   POWERED_RAIL,
   PRISMARINE,
   PRISMARINE_BRICK_SLAB(4, new String[]{"STEP"}),
   PRISMARINE_BRICK_STAIRS(13),
   PRISMARINE_BRICKS(2, new String[]{"PRISMARINE"}),
   PRISMARINE_CRYSTALS,
   PRISMARINE_SHARD,
   PRISMARINE_SLAB(13),
   PRISMARINE_STAIRS(13),
   PRISMARINE_WALL,
   PRIZE_POTTERY_SHERD(20),
   PUFFERFISH(3, new String[]{"RAW_FISH"}),
   PUFFERFISH_BUCKET(0, 13, new String[0]),
   PUFFERFISH_SPAWN_EGG(0, 13, new String[0]),
   PUMPKIN,
   PUMPKIN_PIE,
   PUMPKIN_SEEDS,
   PURPLE_BANNER(5, new String[]{"STANDING_BANNER", "BANNER"}),
   PURPLE_BED(new String[]{"BED"}),
   PURPLE_CANDLE,
   PURPLE_CARPET(10, new String[]{"CARPET"}),
   PURPLE_CONCRETE(10, new String[]{"CONCRETE"}),
   PURPLE_CONCRETE_POWDER(10, new String[]{"CONCRETE_POWDER"}),
   PURPLE_DYE(5, new String[]{"INK_SACK"}),
   PURPLE_GLAZED_TERRACOTTA(10, 12, new String[0]),
   PURPLE_SHULKER_BOX,
   PURPLE_STAINED_GLASS(10, new String[]{"STAINED_GLASS"}),
   PURPLE_STAINED_GLASS_PANE(10, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   PURPLE_TERRACOTTA(10, new String[]{"STAINED_CLAY"}),
   PURPLE_WOOL(10, new String[]{"WOOL"}),
   PURPUR_BLOCK,
   PURPUR_PILLAR,
   PURPUR_SLAB(new String[]{"PURPUR_DOUBLE_SLAB"}),
   PURPUR_STAIRS,
   QUARTZ,
   QUARTZ_BLOCK,
   QUARTZ_BRICKS(16),
   QUARTZ_PILLAR(2, new String[]{"QUARTZ_BLOCK"}),
   QUARTZ_SLAB(7, new String[]{"STEP"}),
   QUARTZ_STAIRS,
   RABBIT,
   RABBIT_FOOT,
   RABBIT_HIDE,
   RABBIT_SPAWN_EGG(101, new String[]{"MONSTER_EGG"}),
   RABBIT_STEW,
   RAIL(new String[]{"RAILS"}),
   RAISER_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   RAVAGER_SPAWN_EGG(14),
   RAW_COPPER,
   RAW_COPPER_BLOCK,
   RAW_GOLD,
   RAW_GOLD_BLOCK,
   RAW_IRON,
   RAW_IRON_BLOCK,
   RECOVERY_COMPASS(19),
   RED_BANNER(1, new String[]{"STANDING_BANNER", "BANNER"}),
   RED_BED(0, new String[]{"BED_BLOCK", "BED"}),
   RED_CANDLE,
   RED_CARPET(14, new String[]{"CARPET"}),
   RED_CONCRETE(14, new String[]{"CONCRETE"}),
   RED_CONCRETE_POWDER(14, new String[]{"CONCRETE_POWDER"}),
   RED_DYE(1, new String[]{"INK_SACK", "ROSE_RED"}),
   RED_GLAZED_TERRACOTTA(14, 12, new String[0]),
   RED_MUSHROOM,
   RED_MUSHROOM_BLOCK(new String[]{"RED_MUSHROOM", "HUGE_MUSHROOM_2"}),
   RED_NETHER_BRICK_SLAB(4, new String[]{"STEP"}),
   RED_NETHER_BRICK_STAIRS,
   RED_NETHER_BRICK_WALL,
   RED_NETHER_BRICKS(new String[]{"RED_NETHER_BRICK"}),
   RED_SAND(1, new String[]{"SAND"}),
   RED_SANDSTONE,
   RED_SANDSTONE_SLAB(new String[]{"DOUBLE_STONE_SLAB2", "STONE_SLAB2"}),
   RED_SANDSTONE_STAIRS,
   RED_SANDSTONE_WALL,
   RED_SHULKER_BOX,
   RED_STAINED_GLASS(14, new String[]{"STAINED_GLASS"}),
   RED_STAINED_GLASS_PANE(14, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   RED_TERRACOTTA(14, new String[]{"STAINED_CLAY"}),
   RED_TULIP(4, new String[]{"RED_ROSE"}),
   RED_WOOL(14, new String[]{"WOOL"}),
   REDSTONE,
   REDSTONE_BLOCK,
   REDSTONE_LAMP(new String[]{"REDSTONE_LAMP_ON", "REDSTONE_LAMP_OFF"}),
   REDSTONE_ORE(new String[]{"GLOWING_REDSTONE_ORE"}),
   REDSTONE_TORCH(new String[]{"REDSTONE_TORCH_OFF", "REDSTONE_TORCH_ON"}),
   REINFORCED_DEEPSLATE(19),
   REPEATER(new String[]{"DIODE_BLOCK_ON", "DIODE_BLOCK_OFF", "DIODE"}),
   REPEATING_COMMAND_BLOCK(new String[]{"COMMAND", "COMMAND_REPEATING"}),
   RESPAWN_ANCHOR(16),
   RIB_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   ROOTED_DIRT,
   ROSE_BUSH(4, new String[]{"DOUBLE_PLANT"}),
   ROTTEN_FLESH,
   SADDLE,
   SALMON(1, new String[]{"RAW_FISH"}),
   SALMON_BUCKET(0, 13, new String[0]),
   SALMON_SPAWN_EGG(0, 13, new String[0]),
   SAND,
   SANDSTONE,
   SANDSTONE_SLAB(1, new String[]{"DOUBLE_STEP", "STEP", "STONE_SLAB"}),
   SANDSTONE_STAIRS,
   SANDSTONE_WALL,
   SCAFFOLDING(0, 14, new String[0]),
   SCULK(19),
   SCULK_CATALYST(19),
   SCULK_SENSOR,
   SCULK_SHRIEKER(19),
   SCULK_VEIN(19),
   TURTLE_SCUTE(new String[]{"SCUTE"}),
   SEA_LANTERN,
   SEA_PICKLE(13),
   SEAGRASS(0, 13, new String[0]),
   SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   SHEAF_POTTERY_SHERD(20),
   SHEARS,
   SHEEP_SPAWN_EGG(91, new String[]{"MONSTER_EGG"}),
   SHELTER_POTTERY_SHERD(20),
   SHIELD,
   SHROOMLIGHT(16),
   SHULKER_BOX(new String[]{"PURPLE_SHULKER_BOX"}),
   SHULKER_SHELL,
   SHULKER_SPAWN_EGG(69, new String[]{"MONSTER_EGG"}),
   SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   SILVERFISH_SPAWN_EGG(60, new String[]{"MONSTER_EGG"}),
   SKELETON_HORSE_SPAWN_EGG(28, new String[]{"MONSTER_EGG"}),
   SKELETON_SKULL(new String[]{"SKULL", "SKULL_ITEM"}),
   SKELETON_SPAWN_EGG(51, new String[]{"MONSTER_EGG"}),
   SKULL_BANNER_PATTERN,
   SKULL_POTTERY_SHERD(20),
   SLIME_BALL,
   SLIME_BLOCK,
   SLIME_SPAWN_EGG(55, new String[]{"MONSTER_EGG"}),
   SMALL_AMETHYST_BUD,
   SMALL_DRIPLEAF,
   SMITHING_TABLE,
   SMOKER(0, 14, new String[0]),
   SMOOTH_BASALT,
   SMOOTH_QUARTZ(0, 13, new String[0]),
   SMOOTH_QUARTZ_SLAB(7, new String[]{"STEP"}),
   SMOOTH_QUARTZ_STAIRS,
   SMOOTH_RED_SANDSTONE(2, new String[]{"RED_SANDSTONE"}),
   SMOOTH_RED_SANDSTONE_SLAB(new String[]{"STONE_SLAB2"}),
   SMOOTH_RED_SANDSTONE_STAIRS,
   SMOOTH_SANDSTONE(2, new String[]{"SANDSTONE"}),
   SMOOTH_SANDSTONE_SLAB,
   SMOOTH_SANDSTONE_STAIRS,
   SMOOTH_STONE,
   SMOOTH_STONE_SLAB,
   SNIFFER_EGG(20),
   SNIFFER_SPAWN_EGG(20),
   SNORT_POTTERY_SHERD(20),
   SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   SNOW,
   SNOW_BLOCK,
   SNOW_GOLEM_SPAWN_EGG(97, new String[]{"MONSTER_EGG"}),
   SNOWBALL(new String[]{"SNOW_BALL"}),
   SOUL_CAMPFIRE(16),
   SOUL_LANTERN(16),
   SOUL_SAND,
   SOUL_SOIL(16),
   SOUL_TORCH(16),
   SPAWNER(new String[]{"MOB_SPAWNER"}),
   SPECTRAL_ARROW(0, 9, new String[0]),
   SPIDER_EYE,
   SPIDER_SPAWN_EGG(52, new String[]{"MONSTER_EGG"}),
   SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   SPLASH_POTION(new String[]{"1.9", "POTION"}),
   SPONGE,
   SPORE_BLOSSOM,
   SPRUCE_BOAT(new String[]{"BOAT_SPRUCE"}),
   SPRUCE_BUTTON(new String[]{"WOOD_BUTTON"}),
   SPRUCE_CHEST_BOAT(19),
   SPRUCE_DOOR(new String[]{"SPRUCE_DOOR", "SPRUCE_DOOR_ITEM"}),
   SPRUCE_FENCE,
   SPRUCE_FENCE_GATE,
   SPRUCE_HANGING_SIGN(20),
   SPRUCE_LEAVES(1, new String[]{"LEAVES"}),
   SPRUCE_LOG(1, new String[]{"LOG"}),
   SPRUCE_PLANKS(1, new String[]{"WOOD"}),
   SPRUCE_PRESSURE_PLATE(new String[]{"WOOD_PLATE"}),
   SPRUCE_SAPLING(1, new String[]{"SAPLING"}),
   SPRUCE_SIGN(new String[]{"SIGN_POST", "SIGN"}),
   SPRUCE_SLAB(1, new String[]{"WOOD_DOUBLE_STEP", "WOOD_STEP", "WOODEN_SLAB"}),
   SPRUCE_STAIRS(new String[]{"SPRUCE_WOOD_STAIRS"}),
   SPRUCE_TRAPDOOR(new String[]{"TRAP_DOOR"}),
   SPRUCE_WOOD(1, new String[]{"LOG"}),
   SPYGLASS,
   SQUID_SPAWN_EGG(94, new String[]{"MONSTER_EGG"}),
   STICK,
   STICKY_PISTON(new String[]{"PISTON_BASE", "PISTON_STICKY_BASE"}),
   STONE,
   STONE_AXE,
   STONE_BRICK_SLAB(5, new String[]{"DOUBLE_STEP", "STEP", "STONE_SLAB"}),
   STONE_BRICK_STAIRS(new String[]{"SMOOTH_STAIRS"}),
   STONE_BRICK_WALL,
   STONE_BRICKS(new String[]{"SMOOTH_BRICK"}),
   STONE_BUTTON,
   STONE_HOE,
   STONE_PICKAXE,
   STONE_PRESSURE_PLATE(new String[]{"STONE_PLATE"}),
   STONE_SHOVEL(new String[]{"STONE_SPADE"}),
   STONE_SLAB(new String[]{"DOUBLE_STEP", "STEP"}),
   STONE_STAIRS,
   STONE_SWORD,
   STONECUTTER(14),
   STRAY_SPAWN_EGG(6, new String[]{"MONSTER_EGG"}),
   STRIDER_SPAWN_EGG(16),
   STRING,
   STRIPPED_ACACIA_LOG(new String[]{"LOG_2"}),
   STRIPPED_ACACIA_WOOD(new String[]{"LOG_2"}),
   STRIPPED_BAMBOO_BLOCK(20),
   STRIPPED_BIRCH_LOG(2, new String[]{"LOG"}),
   STRIPPED_BIRCH_WOOD(2, new String[]{"LOG"}),
   STRIPPED_CHERRY_LOG(20),
   STRIPPED_CHERRY_WOOD(20),
   STRIPPED_CRIMSON_HYPHAE(16),
   STRIPPED_CRIMSON_STEM(16),
   STRIPPED_DARK_OAK_LOG(new String[]{"LOG"}),
   STRIPPED_DARK_OAK_WOOD(new String[]{"LOG"}),
   STRIPPED_JUNGLE_LOG(3, new String[]{"LOG"}),
   STRIPPED_JUNGLE_WOOD(3, new String[]{"LOG"}),
   STRIPPED_MANGROVE_LOG(19),
   STRIPPED_MANGROVE_WOOD(19),
   STRIPPED_OAK_LOG(new String[]{"LOG"}),
   STRIPPED_OAK_WOOD(new String[]{"LOG"}),
   STRIPPED_SPRUCE_LOG(1, new String[]{"LOG"}),
   STRIPPED_SPRUCE_WOOD(1, new String[]{"LOG"}),
   STRIPPED_WARPED_HYPHAE(16),
   STRIPPED_WARPED_STEM(16),
   STRUCTURE_BLOCK,
   STRUCTURE_VOID(10, new String[]{"BARRIER"}),
   SUGAR,
   SUGAR_CANE(new String[]{"SUGAR_CANE_BLOCK"}),
   SUNFLOWER(new String[]{"DOUBLE_PLANT"}),
   SUSPICIOUS_GRAVEL(20),
   SUSPICIOUS_SAND(20),
   SUSPICIOUS_STEW(0, 14, new String[0]),
   SWEET_BERRIES(14),
   TADPOLE_BUCKET(19),
   TADPOLE_SPAWN_EGG(19),
   TALL_GRASS(2, new String[]{"DOUBLE_PLANT"}),
   TARGET(16),
   TERRACOTTA(new String[]{"HARD_CLAY"}),
   TIDE_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   TINTED_GLASS,
   TIPPED_ARROW(0, 9, new String[0]),
   TNT,
   TNT_MINECART(new String[]{"EXPLOSIVE_MINECART"}),
   TORCH,
   TORCHFLOWER(20),
   TORCHFLOWER_SEEDS(20),
   TOTEM_OF_UNDYING(new String[]{"TOTEM"}),
   TRADER_LLAMA_SPAWN_EGG(103, 14, new String[0]),
   TRAPPED_CHEST,
   TRIDENT(13),
   TRIPWIRE_HOOK,
   TROPICAL_FISH(2, new String[]{"RAW_FISH"}),
   TROPICAL_FISH_BUCKET(0, 13, new String[]{"BUCKET", "WATER_BUCKET"}),
   TROPICAL_FISH_SPAWN_EGG(0, 13, new String[]{"MONSTER_EGG"}),
   TUBE_CORAL(13, new String[]{"VINE"}),
   TUBE_CORAL_BLOCK(13),
   TUBE_CORAL_FAN(13),
   TUFF,
   TURTLE_EGG(0, 13, new String[0]),
   TURTLE_HELMET(0, 13, new String[0]),
   TURTLE_SPAWN_EGG(0, 13, new String[0]),
   TWISTING_VINES(16),
   VERDANT_FROGLIGHT(19),
   VEX_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   VEX_SPAWN_EGG(35, new String[]{"MONSTER_EGG"}),
   VILLAGER_SPAWN_EGG(120, new String[]{"MONSTER_EGG"}),
   VINDICATOR_SPAWN_EGG(36, new String[]{"MONSTER_EGG"}),
   VINE,
   WANDERING_TRADER_SPAWN_EGG(0, 14, new String[0]),
   WARD_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   WARDEN_SPAWN_EGG(19),
   WARPED_BUTTON(16),
   WARPED_DOOR(16),
   WARPED_FENCE(16),
   WARPED_FENCE_GATE(16),
   WARPED_FUNGUS(16),
   WARPED_FUNGUS_ON_A_STICK(16),
   WARPED_HANGING_SIGN(20),
   WARPED_HYPHAE(16),
   WARPED_NYLIUM(16),
   WARPED_PLANKS(16),
   WARPED_PRESSURE_PLATE(16),
   WARPED_ROOTS(16),
   WARPED_SIGN(16),
   WARPED_SLAB(16),
   WARPED_STAIRS(16),
   WARPED_STEM(16),
   WARPED_TRAPDOOR(16),
   WARPED_WART_BLOCK(16),
   WATER_BUCKET,
   WAXED_COPPER_BLOCK,
   WAXED_CUT_COPPER,
   WAXED_CUT_COPPER_SLAB,
   WAXED_CUT_COPPER_STAIRS,
   WAXED_EXPOSED_COPPER,
   WAXED_EXPOSED_CUT_COPPER,
   WAXED_EXPOSED_CUT_COPPER_SLAB,
   WAXED_EXPOSED_CUT_COPPER_STAIRS,
   WAXED_OXIDIZED_COPPER,
   WAXED_OXIDIZED_CUT_COPPER,
   WAXED_OXIDIZED_CUT_COPPER_SLAB,
   WAXED_OXIDIZED_CUT_COPPER_STAIRS,
   WAXED_WEATHERED_COPPER,
   WAXED_WEATHERED_CUT_COPPER,
   WAXED_WEATHERED_CUT_COPPER_SLAB,
   WAXED_WEATHERED_CUT_COPPER_STAIRS,
   WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   WEATHERED_COPPER,
   WEATHERED_CUT_COPPER,
   WEATHERED_CUT_COPPER_SLAB,
   WEATHERED_CUT_COPPER_STAIRS,
   WEEPING_VINES(16),
   WET_SPONGE(1, new String[]{"SPONGE"}),
   WHEAT(new String[]{"CROPS"}),
   WHEAT_SEEDS(new String[]{"SEEDS"}),
   WHITE_BANNER(15, new String[]{"STANDING_BANNER", "BANNER"}),
   WHITE_BED(new String[]{"BED"}),
   WHITE_CANDLE,
   WHITE_CARPET(new String[]{"CARPET"}),
   WHITE_CONCRETE(new String[]{"CONCRETE"}),
   WHITE_CONCRETE_POWDER(new String[]{"CONCRETE_POWDER"}),
   WHITE_DYE(15, 14, new String[]{"INK_SACK", "BONE_MEAL"}),
   WHITE_GLAZED_TERRACOTTA(0, 12, new String[]{"STAINED_CLAY"}),
   WHITE_SHULKER_BOX,
   WHITE_STAINED_GLASS(new String[]{"STAINED_GLASS"}),
   WHITE_STAINED_GLASS_PANE(new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   WHITE_TERRACOTTA(new String[]{"STAINED_CLAY", "TERRACOTTA"}),
   WHITE_TULIP(6, new String[]{"RED_ROSE"}),
   WHITE_WOOL(0, new String[]{"WOOL"}),
   WILD_ARMOR_TRIM_SMITHING_TEMPLATE(20),
   WITCH_SPAWN_EGG(66, new String[]{"MONSTER_EGG"}),
   WITHER_ROSE(0, 14, new String[0]),
   WITHER_SKELETON_SKULL(1, new String[]{"SKULL", "SKULL_ITEM"}),
   WITHER_SKELETON_SPAWN_EGG(5, new String[]{"MONSTER_EGG"}),
   WITHER_SPAWN_EGG(64, new String[]{"MONSTER_EGG"}),
   WOLF_SPAWN_EGG(95, new String[]{"MONSTER_EGG"}),
   WOODEN_AXE(new String[]{"WOOD_AXE"}),
   WOODEN_HOE(new String[]{"WOOD_HOE"}),
   WOODEN_PICKAXE(new String[]{"WOOD_PICKAXE"}),
   WOODEN_SHOVEL(new String[]{"WOOD_SPADE"}),
   WOODEN_SWORD(new String[]{"WOOD_SWORD"}),
   WRITABLE_BOOK(new String[]{"BOOK_AND_QUILL"}),
   WRITTEN_BOOK,
   YELLOW_BANNER(11, new String[]{"STANDING_BANNER", "BANNER"}),
   YELLOW_BED(new String[]{"BED"}),
   YELLOW_CANDLE,
   YELLOW_CARPET(4, new String[]{"CARPET"}),
   YELLOW_CONCRETE(4, new String[]{"CONCRETE"}),
   YELLOW_CONCRETE_POWDER(4, new String[]{"CONCRETE_POWDER"}),
   YELLOW_DYE(11, new String[]{"INK_SACK", "DANDELION_YELLOW"}),
   YELLOW_GLAZED_TERRACOTTA(4, 12, new String[]{"STAINED_CLAY", "YELLOW_TERRACOTTA"}),
   YELLOW_SHULKER_BOX,
   YELLOW_STAINED_GLASS(4, new String[]{"STAINED_GLASS"}),
   YELLOW_STAINED_GLASS_PANE(4, new String[]{"THIN_GLASS", "STAINED_GLASS_PANE"}),
   YELLOW_TERRACOTTA(4, new String[]{"STAINED_CLAY"}),
   YELLOW_WOOL(4, new String[]{"WOOL"}),
   ZOGLIN_SPAWN_EGG(16),
   ZOMBIE_HEAD(2, new String[]{"SKULL", "SKULL_ITEM"}),
   ZOMBIE_HORSE_SPAWN_EGG(29, new String[]{"MONSTER_EGG"}),
   ZOMBIE_SPAWN_EGG(54, new String[]{"MONSTER_EGG"}),
   ZOMBIE_VILLAGER_SPAWN_EGG(27, new String[]{"MONSTER_EGG"}),
   ZOMBIFIED_PIGLIN_SPAWN_EGG(57, new String[]{"MONSTER_EGG", "ZOMBIE_PIGMAN_SPAWN_EGG"}),
   DEBUG_STICK(13);

   public static final XMaterial[] VALUES = values();
   private static final Map<String, XMaterial> NAMES = new HashMap();
   private static final Cache<String, XMaterial> NAME_CACHE = CacheBuilder.newBuilder().expireAfterAccess(1L, TimeUnit.HOURS).build();
   private static final LoadingCache<String, Pattern> CACHED_REGEX = CacheBuilder.newBuilder().expireAfterAccess(3L, TimeUnit.HOURS).build(new CacheLoader<String, Pattern>() {
      public Pattern load(@Nonnull String str) {
         try {
            return Pattern.compile(str);
         } catch (PatternSyntaxException var3) {
            var3.printStackTrace();
            return null;
         }
      }
   });
   private static final byte MAX_DATA_VALUE = 120;
   private static final byte UNKNOWN_DATA_VALUE = -1;
   private static final short MAX_ID = 2267;
   private static final Set<String> DUPLICATED;
   private final byte data;
   private final byte version;
   @Nonnull
   private final String[] legacy;
   @Nullable
   private final Material material;

   private XMaterial(int param3, int param4, @Nonnull String... param5) {
      this.data = (byte)data;
      this.version = (byte)version;
      this.legacy = legacy;
      Material mat = null;
      if (!XMaterial.Data.ISFLAT && this.isDuplicated() || (mat = Material.getMaterial(this.name())) == null) {
         for(int i = legacy.length - 1; i >= 0; --i) {
            mat = Material.getMaterial(legacy[i]);
            if (mat != null) {
               break;
            }
         }
      }

      this.material = mat;
   }

   private XMaterial(int param3, @Nonnull String... param4) {
      this(data, 0, legacy);
   }

   private XMaterial(int param3) {
      this(0, version);
   }

   private XMaterial() {
      this(0, 0);
   }

   private XMaterial(String... param3) {
      this(0, 0, legacy);
   }

   public static boolean isNewVersion() {
      return XMaterial.Data.ISFLAT;
   }

   public static boolean isOneEight() {
      return !supports(9);
   }

   public static boolean isShulker(Material material) {
      return material.name().endsWith("SHULKER_BOX");
   }

   @Nonnull
   private static Optional<XMaterial> getIfPresent(@Nonnull String name) {
      return Optional.ofNullable((XMaterial)NAMES.get(name));
   }

   public static int getVersion() {
      return XMaterial.Data.VERSION;
   }

   @Nullable
   private static XMaterial requestOldXMaterial(@Nonnull String name, byte data) {
      String holder = name + data;
      XMaterial cache = (XMaterial)NAME_CACHE.getIfPresent(holder);
      if (cache != null) {
         return cache;
      } else {
         XMaterial[] var4 = VALUES;
         int var5 = var4.length;

         for(int var6 = 0; var6 < var5; ++var6) {
            XMaterial material = var4[var6];
            if ((data == -1 || data == material.data) && material.anyMatchLegacy(name)) {
               NAME_CACHE.put(holder, material);
               return material;
            }
         }

         return null;
      }
   }

   @Nonnull
   public static Optional<XMaterial> matchXMaterial(@Nonnull String name) {
      Validate.notEmpty(name, "Cannot match a material with null or empty material name");
      Optional<XMaterial> oldMatch = matchXMaterialWithData(name);
      return oldMatch.isPresent() ? oldMatch : matchDefinedXMaterial(format(name), (byte)-1);
   }

   @Nonnull
   private static Optional<XMaterial> matchXMaterialWithData(@Nonnull String name) {
      int index = name.indexOf(58);
      if (index != -1) {
         String mat = format(name.substring(0, index));

         try {
            byte data = (byte)Integer.parseInt(StringUtils.deleteWhitespace(name.substring(index + 1)));
            return data >= 0 && data < 120 ? matchDefinedXMaterial(mat, data) : matchDefinedXMaterial(mat, (byte)-1);
         } catch (NumberFormatException var4) {
            return matchDefinedXMaterial(mat, (byte)-1);
         }
      } else {
         return Optional.empty();
      }
   }

   public static XMaterial matchXMaterial(@Nonnull Block block) {
      if (XMaterial.Data.ISFLAT) {
         return matchXMaterial(block.getType());
      } else {
         String type = block.getType().name();
         byte dataValue = -1;
         MaterialData blockData = block.getState().getData();
         if (blockData instanceof Step) {
            Step step = (Step)blockData;
            if (step.isInverted() || type.equals("DOUBLE_STEP")) {
               dataValue = (byte)Integer.parseInt(String.valueOf(step.getData() & 7));
            }
         } else if (blockData instanceof WoodenStep) {
            WoodenStep step = (WoodenStep)blockData;
            if (step.isInverted() || type.equals("WOOD_DOUBLE_STEP")) {
               dataValue = (byte)Integer.parseInt(String.valueOf(step.getData() & 7));
            }
         } else if (!type.contains("CHEST")) {
            dataValue = block.getData();
         }

         return (XMaterial)matchDefinedXMaterial(type, dataValue).orElseThrow(() -> {
            return new IllegalArgumentException("Unsupported material for block " + dataValue + ": " + block.getType().name());
         });
      }
   }

   @Nonnull
   public static XMaterial matchXMaterial(@Nonnull Material material) {
      Objects.requireNonNull(material, "Cannot match null material");
      return (XMaterial)matchDefinedXMaterial(material.name(), (byte)-1).orElseThrow(() -> {
         return new IllegalArgumentException("Unsupported material with no data value: " + material.name());
      });
   }

   @Nonnull
   public static XMaterial matchXMaterial(@Nonnull ItemStack item) {
      Objects.requireNonNull(item, "Cannot match null ItemStack");
      String material = item.getType().name();
      byte data = (byte)(!XMaterial.Data.ISFLAT && item.getType().getMaxDurability() <= 0 ? item.getDurability() : -1);
      if (!XMaterial.Data.ISFLAT && material.equals("POTION")) {
         data = -1;
      }

      Optional<XMaterial> result = matchDefinedXMaterial(material, data);
      if (result.isPresent()) {
         return (XMaterial)result.get();
      } else {
         SendMessage.logDebugMessage("Matching item with unsupported material: " + material + " (" + data + "), skipping...");
         return AIR;
      }
   }

   @Nonnull
   protected static Optional<XMaterial> matchDefinedXMaterial(@Nonnull String name, byte data) {
      Boolean duplicated = null;
      boolean isAMap = name.equalsIgnoreCase("MAP");
      if (XMaterial.Data.ISFLAT || !isAMap && data <= 0 && !duplicated = isDuplicated(name)) {
         Optional<XMaterial> xMaterial = getIfPresent(name);
         if (xMaterial.isPresent()) {
            return xMaterial;
         }
      }

      XMaterial oldXMaterial = requestOldXMaterial(name, data);
      if (oldXMaterial == null) {
         return data >= 0 && isAMap ? Optional.of(FILLED_MAP) : Optional.empty();
      } else {
         if (!XMaterial.Data.ISFLAT) {
            if (duplicated == null) {
               if (isDuplicated(name)) {
                  return getIfPresent(name);
               }
            } else if (duplicated) {
               return getIfPresent(name);
            }
         }

         return Optional.of(oldXMaterial);
      }
   }

   private static boolean isDuplicated(@Nonnull String name) {
      return DUPLICATED.contains(name);
   }

   /** @deprecated */
   @Nonnull
   @Deprecated
   public static Optional<XMaterial> matchXMaterial(int id, byte data) {
      if (id >= 0 && id <= 2267 && data >= 0) {
         XMaterial[] var2 = VALUES;
         int var3 = var2.length;

         for(int var4 = 0; var4 < var3; ++var4) {
            XMaterial materials = var2[var4];
            if (materials.data == data && materials.getId() == id) {
               return Optional.of(materials);
            }
         }

         return Optional.empty();
      } else {
         return Optional.empty();
      }
   }

   public static double getBlockY(Block block) {
      double extra = 0.5D;
      if (block.getType() != Material.CHEST && block.getType() != Material.ENDER_CHEST) {
         if (ServerInfo.getVersion().newerOrEqualAs(ServerInfo.Version.v1_13_R1) && block.getState().getBlockData() instanceof Slab) {
            Slab slab = (Slab)block.getState().getBlockData();
            if (slab.getType() == Type.BOTTOM) {
               extra -= 0.5D;
            }
         } else if (block.getState().getData() instanceof Step) {
            Step step = (Step)block.getState().getData();
            if (!step.isInverted()) {
               extra -= 0.5D;
            }
         } else if (block.getState().getData() instanceof WoodenStep) {
            WoodenStep step = (WoodenStep)block.getState().getData();
            if (!step.isInverted()) {
               extra -= 0.5D;
            }
         }
      }

      return (double)block.getLocation().getBlockY() + extra;
   }

   @Nonnull
   protected static String format(@Nonnull String name) {
      int len = name.length();
      char[] chs = new char[len];
      int count = 0;
      boolean appendUnderline = false;

      for(int i = 0; i < len; ++i) {
         char ch = name.charAt(i);
         if (!appendUnderline && count != 0 && (ch == '-' || ch == ' ' || ch == '_') && chs[count] != '_') {
            appendUnderline = true;
         } else {
            boolean number = false;
            if (ch >= 'A' && ch <= 'Z' || ch >= 'a' && ch <= 'z' || (number = ch >= '0' && ch <= '9')) {
               if (appendUnderline) {
                  chs[count++] = '_';
                  appendUnderline = false;
               }

               if (number) {
                  chs[count++] = ch;
               } else {
                  chs[count++] = (char)(ch & 95);
               }
            }
         }
      }

      return new String(chs, 0, count);
   }

   public static boolean supports(int version) {
      return XMaterial.Data.VERSION >= version;
   }

   @Nonnull
   public static String getMajorVersion(@Nonnull String version) {
      Validate.notEmpty(version, "Cannot get major Minecraft version from null or empty string");
      int index = version.lastIndexOf("MC:");
      if (index != -1) {
         version = version.substring(index + 4, version.length() - 1);
      } else if (version.endsWith("SNAPSHOT")) {
         index = version.indexOf(45);
         version = version.substring(0, index);
      }

      int lastDot = version.lastIndexOf(46);
      if (version.indexOf(46) != lastDot) {
         version = version.substring(0, lastDot);
      }

      return version;
   }

   public String[] getLegacy() {
      return this.legacy;
   }

   public boolean isOneOf(@Nullable Collection<String> materials) {
      if (materials != null && !materials.isEmpty()) {
         String name = this.name();
         Iterator var3 = materials.iterator();

         while(var3.hasNext()) {
            String comp = (String)var3.next();
            String checker = comp.toUpperCase(Locale.ENGLISH);
            if (checker.startsWith("CONTAINS:")) {
               comp = format(checker.substring(9));
               if (name.contains(comp)) {
                  return true;
               }
            } else if (checker.startsWith("REGEX:")) {
               comp = comp.substring(6);
               Pattern pattern = (Pattern)CACHED_REGEX.getUnchecked(comp);
               if (pattern != null && pattern.matcher(name).matches()) {
                  return true;
               }
            } else {
               Optional<XMaterial> xMat = matchXMaterial(comp);
               if (xMat.isPresent() && xMat.get() == this) {
                  return true;
               }
            }
         }

         return false;
      } else {
         return false;
      }
   }

   @Nonnull
   public ItemStack setType(@Nonnull ItemStack item) {
      Objects.requireNonNull(item, "Cannot set material for null ItemStack");
      Material material = this.parseMaterial();
      Objects.requireNonNull(material, () -> {
         return "Unsupported material: " + this.name();
      });
      item.setType(material);
      if (!XMaterial.Data.ISFLAT && material.getMaxDurability() <= 0) {
         item.setDurability((short)this.data);
      }

      return item;
   }

   private boolean anyMatchLegacy(@Nonnull String name) {
      for(int i = this.legacy.length - 1; i >= 0; --i) {
         if (name.equals(this.legacy[i])) {
            return true;
         }
      }

      return false;
   }

   @Nonnull
   public String toString() {
      return WordUtils.capitalize(this.name().replace('_', ' ').toLowerCase(Locale.ENGLISH));
   }

   public int getId() {
      if (this.data == 0 && this.version < 13) {
         Material material = this.parseMaterial();
         if (material == null) {
            return -1;
         } else {
            return XMaterial.Data.ISFLAT && !material.isLegacy() ? -1 : material.getId();
         }
      } else {
         return -1;
      }
   }

   public byte getData() {
      return this.data;
   }

   @Nullable
   public ItemStack parseItem() {
      try {
         Material material = this.parseMaterial();
         if (material == null) {
            return null;
         } else {
            return XMaterial.Data.ISFLAT ? new ItemStack(material) : new ItemStack(material, 1, (short)this.data);
         }
      } catch (IllegalArgumentException var2) {
         return null;
      }
   }

   @Nullable
   public Material parseMaterial() {
      return this.material;
   }

   public boolean isSimilar(@Nonnull ItemStack item) {
      Objects.requireNonNull(item, "Cannot compare with null ItemStack");
      if (item.getType() != this.parseMaterial()) {
         return false;
      } else {
         return XMaterial.Data.ISFLAT || item.getDurability() == this.data || item.getType().getMaxDurability() <= 0;
      }
   }

   public boolean isSupported() {
      return this.material != null;
   }

   public byte getMaterialVersion() {
      return this.version;
   }

   private boolean isDuplicated() {
      String var1 = this.name();
      byte var2 = -1;
      switch(var1.hashCode()) {
      case -1929109465:
         if (var1.equals("POTATO")) {
            var2 = 2;
         }
         break;
      case -1722057187:
         if (var1.equals("DARK_OAK_DOOR")) {
            var2 = 6;
         }
         break;
      case -519277571:
         if (var1.equals("BIRCH_DOOR")) {
            var2 = 8;
         }
         break;
      case -333218805:
         if (var1.equals("SPRUCE_DOOR")) {
            var2 = 10;
         }
         break;
      case -328086150:
         if (var1.equals("NETHER_BRICK")) {
            var2 = 5;
         }
         break;
      case 76092:
         if (var1.equals("MAP")) {
            var2 = 11;
         }
         break;
      case 63467553:
         if (var1.equals("BRICK")) {
            var2 = 4;
         }
         break;
      case 68077974:
         if (var1.equals("GRASS")) {
            var2 = 3;
         }
         break;
      case 73242259:
         if (var1.equals("MELON")) {
            var2 = 0;
         }
         break;
      case 478520881:
         if (var1.equals("ACACIA_DOOR")) {
            var2 = 7;
         }
         break;
      case 868145122:
         if (var1.equals("CAULDRON")) {
            var2 = 12;
         }
         break;
      case 1379814896:
         if (var1.equals("JUNGLE_DOOR")) {
            var2 = 9;
         }
         break;
      case 1401892433:
         if (var1.equals("FLOWER_POT")) {
            var2 = 14;
         }
         break;
      case 1545025079:
         if (var1.equals("BREWING_STAND")) {
            var2 = 13;
         }
         break;
      case 1980706179:
         if (var1.equals("CARROT")) {
            var2 = 1;
         }
      }

      switch(var2) {
      case 0:
      case 1:
      case 2:
      case 3:
      case 4:
      case 5:
      case 6:
      case 7:
      case 8:
      case 9:
      case 10:
      case 11:
      case 12:
      case 13:
      case 14:
         return true;
      default:
         return false;
      }
   }

   // $FF: synthetic method
   private static XMaterial[] $values() {
      return new XMaterial[]{COPPER_NAUTILUS_ARMOR, IRON_NAUTILUS_ARMOR, DIAMOND_NAUTILUS_ARMOR, GOLDEN_NAUTILUS_ARMOR, NETHERITE_NAUTILUS_ARMOR, NETHERITE_HORSE_ARMOR, CAMEL_HUSK_SPAWN_EGG, NAUTILUS_SPAWN_EGG, PARCHED_SPAWN_EGG, ZOMBIE_NAUTILUS_SPAWN_EGG, WOODEN_SPEAR, STONE_SPEAR, COPPER_SPEAR, IRON_SPEAR, DIAMOND_SPEAR, GOLDEN_SPEAR, NETHERITE_SPEAR, COPPER_CHEST, EXPOSED_COPPER_CHEST, WEATHERED_COPPER_CHEST, OXIDIZED_COPPER_CHEST, WAXED_COPPER_CHEST, WAXED_EXPOSED_COPPER_CHEST, WAXED_WEATHERED_COPPER_CHEST, WAXED_OXIDIZED_COPPER_CHEST, OAK_SHELF, SPRUCE_SHELF, BIRCH_SHELF, JUNGLE_SHELF, ACACIA_SHELF, DARK_OAK_SHELF, MANGROVE_SHELF, CHERRY_SHELF, PALE_OAK_SHELF, BAMBOO_SHELF, CRIMSON_SHELF, WARPED_SHELF, COPPER_GOLEM_STATUE, EXPOSED_COPPER_GOLEM_STATUE, WEATHERED_COPPER_GOLEM_STATUE, OXIDIZED_COPPER_GOLEM_STATUE, WAXED_COPPER_GOLEM_STATUE, WAXED_EXPOSED_COPPER_GOLEM_STATUE, WAXED_WEATHERED_COPPER_GOLEM_STATUE, WAXED_OXIDIZED_COPPER_GOLEM_STATUE, EXPOSED_LIGHTNING_ROD, WEATHERED_LIGHTNING_ROD, OXIDIZED_LIGHTNING_ROD, WAXED_LIGHTNING_ROD, WAXED_EXPOSED_LIGHTNING_ROD, WAXED_WEATHERED_LIGHTNING_ROD, WAXED_OXIDIZED_LIGHTNING_ROD, COPPER_GOLEM_SPAWN_EGG, COPPER_SWORD, COPPER_AXE, COPPER_PICKAXE, COPPER_SHOVEL, COPPER_HOE, COPPER_HELMET, COPPER_CHESTPLATE, COPPER_LEGGINGS, COPPER_BOOTS, COPPER_HORSE_ARMOR, COPPER_NUGGET, COPPER_TORCH, COPPER_WALL_TORCH, COPPER_LANTERN, EXPOSED_COPPER_LANTERN, WEATHERED_COPPER_LANTERN, OXIDIZED_COPPER_LANTERN, WAXED_COPPER_LANTERN, WAXED_EXPOSED_COPPER_LANTERN, WAXED_WEATHERED_COPPER_LANTERN, WAXED_OXIDIZED_COPPER_LANTERN, COPPER_BARS, EXPOSED_COPPER_BARS, WEATHERED_COPPER_BARS, OXIDIZED_COPPER_BARS, WAXED_COPPER_BARS, WAXED_EXPOSED_COPPER_BARS, WAXED_WEATHERED_COPPER_BARS, WAXED_OXIDIZED_COPPER_BARS, COPPER_CHAIN, EXPOSED_COPPER_CHAIN, WEATHERED_COPPER_CHAIN, OXIDIZED_COPPER_CHAIN, WAXED_COPPER_CHAIN, WAXED_EXPOSED_COPPER_CHAIN, WAXED_WEATHERED_COPPER_CHAIN, WAXED_OXIDIZED_COPPER_CHAIN, MUSIC_DISC_LAVA_CHICKEN, WHITE_HARNESS, LIGHT_GRAY_HARNESS, GRAY_HARNESS, BLACK_HARNESS, BROWN_HARNESS, RED_HARNESS, ORANGE_HARNESS, YELLOW_HARNESS, GREEN_HARNESS, LIME_HARNESS, CYAN_HARNESS, BLUE_HARNESS, MAGENTA_HARNESS, LIGHT_BLUE_HARNESS, PURPLE_HARNESS, PINK_HARNESS, MUSIC_DISC_TEARS, HAPPY_GHAST_SPAWN_EGG, DRIED_GHAST, BLUE_EGG, BROWN_EGG, BUSH, CACTUS_FLOWER, FIREFLY_BUSH, LEAF_LITTER, SHORT_DRY_GRASS, TALL_DRY_GRASS, TEST_BLOCK, TEST_INSTANCE_BLOCK, WILDFLOWERS, CREAKING_HEART, CREAKING_SPAWN_EGG, OPEN_EYEBLOSSOM, CLOSED_EYEBLOSSOM, PALE_HANGING_MOSS, PALE_MOSS_BLOCK, PALE_MOSS_CARPET, PALE_OAK_LOG, STRIPPED_PALE_OAK_LOG, PALE_OAK_WOOD, STRIPPED_PALE_OAK_WOOD, PALE_OAK_LEAVES, PALE_OAK_SAPLING, PALE_OAK_PLANKS, PALE_OAK_SIGN, PALE_OAK_BUTTON, PALE_OAK_DOOR, PALE_OAK_FENCE, PALE_OAK_FENCE_GATE, PALE_OAK_PRESSURE_PLATE, PALE_OAK_WALL_SIGN, PALE_OAK_HANGING_SIGN, PALE_OAK_SLAB, PALE_OAK_STAIRS, PALE_OAK_TRAPDOOR, PALE_OAK_BOAT, PALE_OAK_CHEST_BOAT, RESIN_CLUMP, RESIN_BLOCK, RESIN_BRICK, RESIN_BRICKS, RESIN_BRICK_SLAB, RESIN_BRICK_STAIRS, RESIN_BRICK_WALL, CHISELED_RESIN_BRICKS, FIELD_MASONED_BANNER_PATTERN, BORDURE_INDENTED_BANNER_PATTERN, WHITE_BUNDLE, ORANGE_BUNDLE, MAGENTA_BUNDLE, LIGHT_BLUE_BUNDLE, YELLOW_BUNDLE, LIME_BUNDLE, PINK_BUNDLE, GRAY_BUNDLE, LIGHT_GRAY_BUNDLE, CYAN_BUNDLE, PURPLE_BUNDLE, BLUE_BUNDLE, BROWN_BUNDLE, GREEN_BUNDLE, RED_BUNDLE, BLACK_BUNDLE, MUSIC_DISC_CREATOR, MUSIC_DISC_CREATOR_MUSIC_BOX, MUSIC_DISC_PRECIPICE, ARMADILLO_SCUTE, ARMADILLO_SPAWN_EGG, WOLF_ARMOR, HEAVY_CORE, TRIAL_SPAWNER, VAULT, FLOW_BANNER_PATTERN, GUSTER_BANNER_PATTERN, BREEZE_ROD, MACE, OMINOUS_BOTTLE, OMINOUS_TRIAL_KEY, FLOW_POTTERY_SHERD, GUSTER_POTTERY_SHERD, SCRAPE_POTTERY_SHERD, BOLT_ARMOR_TRIM_SMITHING_TEMPLATE, FLOW_ARMOR_TRIM_SMITHING_TEMPLATE, BOGGED_SPAWN_EGG, TRIAL_CHAMBERS_MAP, WIND_CHARGE, CHISELED_COPPER, EXPOSED_CHISELED_COPPER, WEATHERED_CHISELED_COPPER, OXIDIZED_CHISELED_COPPER, WAXED_CHISELED_COPPER, WAXED_EXPOSED_CHISELED_COPPER, WAXED_WEATHERED_CHISELED_COPPER, WAXED_OXIDIZED_CHISELED_COPPER, COPPER_BULB, EXPOSED_COPPER_BULB, WEATHERED_COPPER_BULB, OXIDIZED_COPPER_BULB, WAXED_COPPER_BULB, WAXED_EXPOSED_COPPER_BULB, WAXED_WEATHERED_COPPER_BULB, WAXED_OXIDIZED_COPPER_BULB, COPPER_DOOR, EXPOSED_COPPER_DOOR, WEATHERED_COPPER_DOOR, OXIDIZED_COPPER_DOOR, WAXED_COPPER_DOOR, WAXED_EXPOSED_COPPER_DOOR, WAXED_WEATHERED_COPPER_DOOR, WAXED_OXIDIZED_COPPER_DOOR, COPPER_TRAPDOOR, EXPOSED_COPPER_TRAPDOOR, WEATHERED_COPPER_TRAPDOOR, OXIDIZED_COPPER_TRAPDOOR, WAXED_COPPER_TRAPDOOR, WAXED_EXPOSED_COPPER_TRAPDOOR, WAXED_WEATHERED_COPPER_TRAPDOOR, WAXED_OXIDIZED_COPPER_TRAPDOOR, COPPER_GRATE, EXPOSED_COPPER_GRATE, WEATHERED_COPPER_GRATE, OXIDIZED_COPPER_GRATE, WAXED_COPPER_GRATE, WAXED_EXPOSED_COPPER_GRATE, WAXED_WEATHERED_COPPER_GRATE, WAXED_OXIDIZED_COPPER_GRATE, CRAFTER, TRAIL_SPAWNER, TUFF_STAIRS, TUFF_SLAB, TUFF_WALL, CHISELED_TUFF, POLISHED_TUFF_STAIRS, POLISHED_TUFF_SLAB, POLISHED_TUFF_WALL, POLISHED_TUFF, TUFF_BRICK_STAIRS, TUFF_BRICK_SLAB, TUFF_BRICK_WALL, TUFF_BRICKS, CHISELED_TUFF_BRICKS, BREEZE_SPAWN_EGG, TRIAL_KEY, ACACIA_BOAT, ACACIA_BUTTON, ACACIA_CHEST_BOAT, ACACIA_DOOR, ACACIA_FENCE, ACACIA_FENCE_GATE, ACACIA_HANGING_SIGN, ACACIA_LEAVES, ACACIA_LOG, ACACIA_PLANKS, ACACIA_PRESSURE_PLATE, ACACIA_SAPLING, ACACIA_SIGN, ACACIA_SLAB, ACACIA_STAIRS, ACACIA_TRAPDOOR, ACACIA_WOOD, ACTIVATOR_RAIL, AIR, ALLAY_SPAWN_EGG, ALLIUM, AMETHYST_BLOCK, AMETHYST_CLUSTER, AMETHYST_SHARD, ANCIENT_DEBRIS, ANDESITE, ANDESITE_SLAB, ANDESITE_STAIRS, ANDESITE_WALL, ANGLER_POTTERY_SHERD, ANVIL, APPLE, ARCHER_POTTERY_SHERD, ARMOR_STAND, ARMS_UP_POTTERY_SHERD, ARROW, AXOLOTL_BUCKET, AXOLOTL_SPAWN_EGG, AZALEA, AZALEA_LEAVES, AZURE_BLUET, BAKED_POTATO, BAMBOO, BAMBOO_BLOCK, BAMBOO_BUTTON, BAMBOO_CHEST_RAFT, BAMBOO_DOOR, BAMBOO_FENCE, BAMBOO_FENCE_GATE, BAMBOO_HANGING_SIGN, BAMBOO_MOSAIC, BAMBOO_MOSAIC_SLAB, BAMBOO_MOSAIC_STAIRS, BAMBOO_PLANKS, BAMBOO_PRESSURE_PLATE, BAMBOO_RAFT, BAMBOO_SIGN, BAMBOO_SLAB, BAMBOO_STAIRS, BAMBOO_TRAPDOOR, BARREL, BARRIER, BASALT, BAT_SPAWN_EGG, BEACON, BEDROCK, BEE_NEST, BEE_SPAWN_EGG, BEEF, BEEHIVE, BEETROOT, BEETROOT_SEEDS, BEETROOT_SOUP, BELL, BIG_DRIPLEAF, BIRCH_BOAT, BIRCH_BUTTON, BIRCH_CHEST_BOAT, BIRCH_DOOR, BIRCH_FENCE, BIRCH_FENCE_GATE, BIRCH_HANGING_SIGN, BIRCH_LEAVES, BIRCH_LOG, BIRCH_PLANKS, BIRCH_PRESSURE_PLATE, BIRCH_SAPLING, BIRCH_SIGN, BIRCH_SLAB, BIRCH_STAIRS, BIRCH_TRAPDOOR, BIRCH_WOOD, BLACK_BANNER, BLACK_BED, BLACK_CANDLE, BLACK_CARPET, BLACK_CONCRETE, BLACK_CONCRETE_POWDER, BLACK_DYE, BLACK_GLAZED_TERRACOTTA, BLACK_SHULKER_BOX, BLACK_STAINED_GLASS, BLACK_STAINED_GLASS_PANE, BLACK_TERRACOTTA, BLACK_WOOL, BLACKSTONE, BLACKSTONE_SLAB, BLACKSTONE_STAIRS, BLACKSTONE_WALL, BLADE_POTTERY_SHERD, BLAST_FURNACE, BLAZE_POWDER, BLAZE_ROD, BLAZE_SPAWN_EGG, BLUE_BANNER, BLUE_BED, BLUE_CANDLE, BLUE_CARPET, BLUE_CONCRETE, BLUE_CONCRETE_POWDER, BLUE_DYE, BLUE_GLAZED_TERRACOTTA, BLUE_ICE, BLUE_ORCHID, BLUE_SHULKER_BOX, BLUE_STAINED_GLASS, BLUE_STAINED_GLASS_PANE, BLUE_TERRACOTTA, BLUE_WOOL, BONE, BONE_BLOCK, BONE_MEAL, BOOK, BOOKSHELF, BOW, BOWL, BRAIN_CORAL, BRAIN_CORAL_BLOCK, BRAIN_CORAL_FAN, BREAD, BREWER_POTTERY_SHERD, BREWING_STAND, BRICK, BRICK_SLAB, BRICK_STAIRS, BRICK_WALL, BRICKS, BROWN_BANNER, BROWN_BED, BROWN_CANDLE, BROWN_CARPET, BROWN_CONCRETE, BROWN_CONCRETE_POWDER, BROWN_DYE, BROWN_GLAZED_TERRACOTTA, BROWN_MUSHROOM, BROWN_MUSHROOM_BLOCK, BROWN_SHULKER_BOX, BROWN_STAINED_GLASS, BROWN_STAINED_GLASS_PANE, BROWN_TERRACOTTA, BROWN_WOOL, BRUSH, BUBBLE_CORAL, BUBBLE_CORAL_BLOCK, BUBBLE_CORAL_FAN, BUCKET, BUDDING_AMETHYST, BUNDLE, BURN_POTTERY_SHERD, CACTUS, CAKE, CALCITE, CALIBRATED_SCULK_SENSOR, CAMEL_SPAWN_EGG, CAMPFIRE, CANDLE, CARROT, CARROT_ON_A_STICK, CARTOGRAPHY_TABLE, CARVED_PUMPKIN, CAT_SPAWN_EGG, CAULDRON, CAVE_SPIDER_SPAWN_EGG, IRON_CHAIN, CHAIN_COMMAND_BLOCK, CHAINMAIL_BOOTS, CHAINMAIL_CHESTPLATE, CHAINMAIL_HELMET, CHAINMAIL_LEGGINGS, CHARCOAL, CHERRY_BOAT, CHERRY_BUTTON, CHERRY_CHEST_BOAT, CHERRY_DOOR, CHERRY_FENCE, CHERRY_FENCE_GATE, CHERRY_HANGING_SIGN, CHERRY_LEAVES, CHERRY_LOG, CHERRY_PLANKS, CHERRY_PRESSURE_PLATE, CHERRY_SAPLING, CHERRY_SIGN, CHERRY_SLAB, CHERRY_STAIRS, CHERRY_TRAPDOOR, CHERRY_WOOD, CHEST, CHEST_MINECART, CHICKEN, CHICKEN_SPAWN_EGG, CHIPPED_ANVIL, CHISELED_BOOKSHELF, CHISELED_DEEPSLATE, CHISELED_NETHER_BRICKS, CHISELED_POLISHED_BLACKSTONE, CHISELED_QUARTZ_BLOCK, CHISELED_RED_SANDSTONE, CHISELED_SANDSTONE, CHISELED_STONE_BRICKS, CHORUS_FLOWER, CHORUS_FRUIT, CHORUS_PLANT, CLAY, CLAY_BALL, CLOCK, COAL, COAL_BLOCK, COAL_ORE, COARSE_DIRT, COAST_ARMOR_TRIM_SMITHING_TEMPLATE, COBBLED_DEEPSLATE, COBBLED_DEEPSLATE_SLAB, COBBLED_DEEPSLATE_STAIRS, COBBLED_DEEPSLATE_WALL, COBBLESTONE, COBBLESTONE_SLAB, COBBLESTONE_STAIRS, COBBLESTONE_WALL, COBWEB, COCOA_BEANS, COD, COD_BUCKET, COD_SPAWN_EGG, COMMAND_BLOCK, COMMAND_BLOCK_MINECART, COMPARATOR, COMPASS, COMPOSTER, CONDUIT, COOKED_BEEF, COOKED_CHICKEN, COOKED_COD, COOKED_MUTTON, COOKED_PORKCHOP, COOKED_RABBIT, COOKED_SALMON, COOKIE, COPPER_BLOCK, COPPER_INGOT, COPPER_ORE, CORNFLOWER, COW_SPAWN_EGG, CRACKED_DEEPSLATE_BRICKS, CRACKED_DEEPSLATE_TILES, CRACKED_NETHER_BRICKS, CRACKED_POLISHED_BLACKSTONE_BRICKS, CRACKED_STONE_BRICKS, CRAFTING_TABLE, CREEPER_BANNER_PATTERN, CREEPER_HEAD, CREEPER_SPAWN_EGG, CRIMSON_BUTTON, CRIMSON_DOOR, CRIMSON_FENCE, CRIMSON_FENCE_GATE, CRIMSON_FUNGUS, CRIMSON_HANGING_SIGN, CRIMSON_HYPHAE, CRIMSON_NYLIUM, CRIMSON_PLANKS, CRIMSON_PRESSURE_PLATE, CRIMSON_ROOTS, CRIMSON_SIGN, CRIMSON_SLAB, CRIMSON_STAIRS, CRIMSON_STEM, CRIMSON_TRAPDOOR, CROSSBOW, CRYING_OBSIDIAN, CUT_COPPER, CUT_COPPER_SLAB, CUT_COPPER_STAIRS, CUT_RED_SANDSTONE, CUT_RED_SANDSTONE_SLAB, CUT_SANDSTONE, CUT_SANDSTONE_SLAB, CYAN_BANNER, CYAN_BED, CYAN_CANDLE, CYAN_CARPET, CYAN_CONCRETE, CYAN_CONCRETE_POWDER, CYAN_DYE, CYAN_GLAZED_TERRACOTTA, CYAN_SHULKER_BOX, CYAN_STAINED_GLASS, CYAN_STAINED_GLASS_PANE, CYAN_TERRACOTTA, CYAN_WOOL, DAMAGED_ANVIL, DANDELION, DANGER_POTTERY_SHERD, DARK_OAK_BOAT, DARK_OAK_BUTTON, DARK_OAK_CHEST_BOAT, DARK_OAK_DOOR, DARK_OAK_FENCE, DARK_OAK_FENCE_GATE, DARK_OAK_HANGING_SIGN, DARK_OAK_LEAVES, DARK_OAK_LOG, DARK_OAK_PLANKS, DARK_OAK_PRESSURE_PLATE, DARK_OAK_SAPLING, DARK_OAK_SIGN, DARK_OAK_SLAB, DARK_OAK_STAIRS, DARK_OAK_TRAPDOOR, DARK_OAK_WOOD, DARK_PRISMARINE, DARK_PRISMARINE_SLAB, DARK_PRISMARINE_STAIRS, DAYLIGHT_DETECTOR, DEAD_BRAIN_CORAL, DEAD_BRAIN_CORAL_BLOCK, DEAD_BRAIN_CORAL_FAN, DEAD_BUBBLE_CORAL, DEAD_BUBBLE_CORAL_BLOCK, DEAD_BUBBLE_CORAL_FAN, DEAD_BUSH, DEAD_FIRE_CORAL, DEAD_FIRE_CORAL_BLOCK, DEAD_FIRE_CORAL_FAN, DEAD_HORN_CORAL, DEAD_HORN_CORAL_BLOCK, DEAD_HORN_CORAL_FAN, DEAD_TUBE_CORAL, DEAD_TUBE_CORAL_BLOCK, DEAD_TUBE_CORAL_FAN, DECORATED_POT, DEEPSLATE, DEEPSLATE_BRICK_SLAB, DEEPSLATE_BRICK_STAIRS, DEEPSLATE_BRICK_WALL, DEEPSLATE_BRICKS, DEEPSLATE_COAL_ORE, DEEPSLATE_COPPER_ORE, DEEPSLATE_DIAMOND_ORE, DEEPSLATE_EMERALD_ORE, DEEPSLATE_GOLD_ORE, DEEPSLATE_IRON_ORE, DEEPSLATE_LAPIS_ORE, DEEPSLATE_REDSTONE_ORE, DEEPSLATE_TILE_SLAB, DEEPSLATE_TILE_STAIRS, DEEPSLATE_TILE_WALL, DEEPSLATE_TILES, DETECTOR_RAIL, DIAMOND, DIAMOND_AXE, DIAMOND_BLOCK, DIAMOND_BOOTS, DIAMOND_CHESTPLATE, DIAMOND_HELMET, DIAMOND_HOE, DIAMOND_HORSE_ARMOR, DIAMOND_LEGGINGS, DIAMOND_ORE, DIAMOND_PICKAXE, DIAMOND_SHOVEL, DIAMOND_SWORD, DIORITE, DIORITE_SLAB, DIORITE_STAIRS, DIORITE_WALL, DIRT, DIRT_PATH, DISC_FRAGMENT_5, DISPENSER, DOLPHIN_SPAWN_EGG, DONKEY_SPAWN_EGG, DRAGON_BREATH, DRAGON_EGG, DRAGON_HEAD, DRIED_KELP, DRIED_KELP_BLOCK, DRIPSTONE_BLOCK, DROPPER, DROWNED_SPAWN_EGG, DUNE_ARMOR_TRIM_SMITHING_TEMPLATE, ECHO_SHARD, EGG, ELDER_GUARDIAN_SPAWN_EGG, ELYTRA, EMERALD, EMERALD_BLOCK, EMERALD_ORE, ENCHANTED_BOOK, ENCHANTED_GOLDEN_APPLE, ENCHANTING_TABLE, END_CRYSTAL, END_PORTAL_FRAME, END_ROD, END_STONE, END_STONE_BRICK_SLAB, END_STONE_BRICK_STAIRS, END_STONE_BRICK_WALL, END_STONE_BRICKS, ENDER_CHEST, ENDER_DRAGON_SPAWN_EGG, ENDER_EYE, ENDER_PEARL, ENDERMAN_SPAWN_EGG, ENDERMITE_SPAWN_EGG, EVOKER_SPAWN_EGG, EXPERIENCE_BOTTLE, EXPLORER_POTTERY_SHERD, EXPOSED_COPPER, EXPOSED_CUT_COPPER, EXPOSED_CUT_COPPER_SLAB, EXPOSED_CUT_COPPER_STAIRS, EYE_ARMOR_TRIM_SMITHING_TEMPLATE, FARMLAND, FEATHER, FERMENTED_SPIDER_EYE, FERN, FILLED_MAP, FIRE_CHARGE, FIRE_CORAL, FIRE_CORAL_BLOCK, FIRE_CORAL_FAN, FIREWORK_ROCKET, FIREWORK_STAR, FISHING_ROD, FLETCHING_TABLE, FLINT, FLINT_AND_STEEL, FLOWER_BANNER_PATTERN, FLOWER_POT, FLOWERING_AZALEA, FLOWERING_AZALEA_LEAVES, FOX_SPAWN_EGG, FRIEND_POTTERY_SHERD, FROG_SPAWN_EGG, FROGSPAWN, FURNACE, FURNACE_MINECART, GHAST_SPAWN_EGG, GHAST_TEAR, GILDED_BLACKSTONE, GLASS, GLASS_BOTTLE, GLASS_PANE, GLISTERING_MELON_SLICE, GLOBE_BANNER_PATTERN, GLOW_BERRIES, GLOW_INK_SAC, GLOW_ITEM_FRAME, GLOW_LICHEN, GLOW_SQUID_SPAWN_EGG, GLOWSTONE, GLOWSTONE_DUST, GOAT_HORN, GOAT_SPAWN_EGG, GOLD_BLOCK, GOLD_INGOT, GOLD_NUGGET, GOLD_ORE, GOLDEN_APPLE, GOLDEN_AXE, GOLDEN_BOOTS, GOLDEN_CARROT, GOLDEN_CHESTPLATE, GOLDEN_HELMET, GOLDEN_HOE, GOLDEN_HORSE_ARMOR, GOLDEN_LEGGINGS, GOLDEN_PICKAXE, GOLDEN_SHOVEL, GOLDEN_SWORD, GRANITE, GRANITE_SLAB, GRANITE_STAIRS, GRANITE_WALL, SHORT_GRASS, GRASS_BLOCK, GRASS_PATH, GRAVEL, GRAY_BANNER, GRAY_BED, GRAY_CANDLE, GRAY_CARPET, GRAY_CONCRETE, GRAY_CONCRETE_POWDER, GRAY_DYE, GRAY_GLAZED_TERRACOTTA, GRAY_SHULKER_BOX, GRAY_STAINED_GLASS, GRAY_STAINED_GLASS_PANE, GRAY_TERRACOTTA, GRAY_WOOL, GREEN_BANNER, GREEN_BED, GREEN_CANDLE, GREEN_CARPET, GREEN_CONCRETE, GREEN_CONCRETE_POWDER, GREEN_DYE, GREEN_GLAZED_TERRACOTTA, GREEN_SHULKER_BOX, GREEN_STAINED_GLASS, GREEN_STAINED_GLASS_PANE, GREEN_TERRACOTTA, GREEN_WOOL, GRINDSTONE, GUARDIAN_SPAWN_EGG, GUNPOWDER, HANGING_ROOTS, HAY_BLOCK, HEART_OF_THE_SEA, HEART_POTTERY_SHERD, HEARTBREAK_POTTERY_SHERD, HEAVY_WEIGHTED_PRESSURE_PLATE, HOGLIN_SPAWN_EGG, HONEY_BLOCK, HONEY_BOTTLE, HONEYCOMB, HONEYCOMB_BLOCK, HOPPER, HOPPER_MINECART, HORN_CORAL, HORN_CORAL_BLOCK, HORN_CORAL_FAN, HORSE_SPAWN_EGG, HOST_ARMOR_TRIM_SMITHING_TEMPLATE, HOWL_POTTERY_SHERD, HUSK_SPAWN_EGG, ICE, INFESTED_CHISELED_STONE_BRICKS, INFESTED_COBBLESTONE, INFESTED_CRACKED_STONE_BRICKS, INFESTED_DEEPSLATE, INFESTED_MOSSY_STONE_BRICKS, INFESTED_STONE, INFESTED_STONE_BRICKS, INK_SAC, IRON_AXE, IRON_BARS, IRON_BLOCK, IRON_BOOTS, IRON_CHESTPLATE, IRON_DOOR, IRON_GOLEM_SPAWN_EGG, IRON_HELMET, IRON_HOE, IRON_HORSE_ARMOR, IRON_INGOT, IRON_LEGGINGS, IRON_NUGGET, IRON_ORE, IRON_PICKAXE, IRON_SHOVEL, IRON_SWORD, IRON_TRAPDOOR, ITEM_FRAME, JACK_O_LANTERN, JIGSAW, JUKEBOX, JUNGLE_BOAT, JUNGLE_BUTTON, JUNGLE_CHEST_BOAT, JUNGLE_DOOR, JUNGLE_FENCE, JUNGLE_FENCE_GATE, JUNGLE_HANGING_SIGN, JUNGLE_LEAVES, JUNGLE_LOG, JUNGLE_PLANKS, JUNGLE_PRESSURE_PLATE, JUNGLE_SAPLING, JUNGLE_SIGN, JUNGLE_SLAB, JUNGLE_STAIRS, JUNGLE_TRAPDOOR, JUNGLE_WOOD, KELP, KNOWLEDGE_BOOK, LADDER, LANTERN, LAPIS_BLOCK, LAPIS_LAZULI, LAPIS_ORE, LARGE_AMETHYST_BUD, LARGE_FERN, LAVA_BUCKET, LEAD, LEATHER, LEATHER_BOOTS, LEATHER_CHESTPLATE, LEATHER_HELMET, LEATHER_HORSE_ARMOR, LEATHER_LEGGINGS, LECTERN, LEVER, LIGHT, LIGHT_BLUE_BANNER, LIGHT_BLUE_BED, LIGHT_BLUE_CANDLE, LIGHT_BLUE_CARPET, LIGHT_BLUE_CONCRETE, LIGHT_BLUE_CONCRETE_POWDER, LIGHT_BLUE_DYE, LIGHT_BLUE_GLAZED_TERRACOTTA, LIGHT_BLUE_SHULKER_BOX, LIGHT_BLUE_STAINED_GLASS, LIGHT_BLUE_STAINED_GLASS_PANE, LIGHT_BLUE_TERRACOTTA, LIGHT_BLUE_WOOL, LIGHT_GRAY_BANNER, LIGHT_GRAY_BED, LIGHT_GRAY_CANDLE, LIGHT_GRAY_CARPET, LIGHT_GRAY_CONCRETE, LIGHT_GRAY_CONCRETE_POWDER, LIGHT_GRAY_DYE, LIGHT_GRAY_GLAZED_TERRACOTTA, LIGHT_GRAY_SHULKER_BOX, LIGHT_GRAY_STAINED_GLASS, LIGHT_GRAY_STAINED_GLASS_PANE, LIGHT_GRAY_TERRACOTTA, LIGHT_GRAY_WOOL, LIGHT_WEIGHTED_PRESSURE_PLATE, LIGHTNING_ROD, LILAC, LILY_OF_THE_VALLEY, LILY_PAD, LIME_BANNER, LIME_BED, LIME_CANDLE, LIME_CARPET, LIME_CONCRETE, LIME_CONCRETE_POWDER, LIME_DYE, LIME_GLAZED_TERRACOTTA, LIME_SHULKER_BOX, LIME_STAINED_GLASS, LIME_STAINED_GLASS_PANE, LIME_TERRACOTTA, LIME_WOOL, LINGERING_POTION, LLAMA_SPAWN_EGG, LODESTONE, LOOM, MAGENTA_BANNER, MAGENTA_BED, MAGENTA_CANDLE, MAGENTA_CARPET, MAGENTA_CONCRETE, MAGENTA_CONCRETE_POWDER, MAGENTA_DYE, MAGENTA_GLAZED_TERRACOTTA, MAGENTA_SHULKER_BOX, MAGENTA_STAINED_GLASS, MAGENTA_STAINED_GLASS_PANE, MAGENTA_TERRACOTTA, MAGENTA_WOOL, MAGMA_BLOCK, MAGMA_CREAM, MAGMA_CUBE_SPAWN_EGG, MANGROVE_BOAT, MANGROVE_BUTTON, MANGROVE_CHEST_BOAT, MANGROVE_DOOR, MANGROVE_FENCE, MANGROVE_FENCE_GATE, MANGROVE_HANGING_SIGN, MANGROVE_LEAVES, MANGROVE_LOG, MANGROVE_PLANKS, MANGROVE_PRESSURE_PLATE, MANGROVE_PROPAGULE, MANGROVE_ROOTS, MANGROVE_SIGN, MANGROVE_SLAB, MANGROVE_STAIRS, MANGROVE_TRAPDOOR, MANGROVE_WOOD, MAP, MEDIUM_AMETHYST_BUD, MELON, MELON_SEEDS, MELON_SLICE, MILK_BUCKET, MINECART, MINER_POTTERY_SHERD, MOJANG_BANNER_PATTERN, MOOSHROOM_SPAWN_EGG, MOSS_BLOCK, MOSS_CARPET, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE_SLAB, MOSSY_COBBLESTONE_STAIRS, MOSSY_COBBLESTONE_WALL, MOSSY_STONE_BRICK_SLAB, MOSSY_STONE_BRICK_STAIRS, MOSSY_STONE_BRICK_WALL, MOSSY_STONE_BRICKS, MOURNER_POTTERY_SHERD, MUD, MUD_BRICK_SLAB, MUD_BRICK_STAIRS, MUD_BRICK_WALL, MUD_BRICKS, MUDDY_MANGROVE_ROOTS, MULE_SPAWN_EGG, MUSHROOM_STEM, MUSHROOM_STEW, MUSIC_DISC_11, MUSIC_DISC_13, MUSIC_DISC_5, MUSIC_DISC_BLOCKS, MUSIC_DISC_CAT, MUSIC_DISC_CHIRP, MUSIC_DISC_FAR, MUSIC_DISC_MALL, MUSIC_DISC_MELLOHI, MUSIC_DISC_OTHERSIDE, MUSIC_DISC_PIGSTEP, MUSIC_DISC_RELIC, MUSIC_DISC_STAL, MUSIC_DISC_STRAD, MUSIC_DISC_WAIT, MUSIC_DISC_WARD, MUTTON, MYCELIUM, NAME_TAG, NAUTILUS_SHELL, NETHER_BRICK, NETHER_BRICK_FENCE, NETHER_BRICK_SLAB, NETHER_BRICK_STAIRS, NETHER_BRICK_WALL, NETHER_BRICKS, NETHER_GOLD_ORE, NETHER_QUARTZ_ORE, NETHER_SPROUTS, NETHER_STAR, NETHER_WART, NETHER_WART_BLOCK, NETHERITE_AXE, NETHERITE_BLOCK, NETHERITE_BOOTS, NETHERITE_CHESTPLATE, NETHERITE_HELMET, NETHERITE_HOE, NETHERITE_INGOT, NETHERITE_LEGGINGS, NETHERITE_PICKAXE, NETHERITE_SCRAP, NETHERITE_SHOVEL, NETHERITE_SWORD, NETHERITE_UPGRADE_SMITHING_TEMPLATE, NETHERRACK, NOTE_BLOCK, OAK_BOAT, OAK_BUTTON, OAK_CHEST_BOAT, OAK_DOOR, OAK_FENCE, OAK_FENCE_GATE, OAK_HANGING_SIGN, OAK_LEAVES, OAK_LOG, OAK_PLANKS, OAK_PRESSURE_PLATE, OAK_SAPLING, OAK_SIGN, OAK_SLAB, OAK_STAIRS, OAK_TRAPDOOR, OAK_WOOD, OBSERVER, OBSIDIAN, OCELOT_SPAWN_EGG, OCHRE_FROGLIGHT, ORANGE_BANNER, ORANGE_BED, ORANGE_CANDLE, ORANGE_CARPET, ORANGE_CONCRETE, ORANGE_CONCRETE_POWDER, ORANGE_DYE, ORANGE_GLAZED_TERRACOTTA, ORANGE_SHULKER_BOX, ORANGE_STAINED_GLASS, ORANGE_STAINED_GLASS_PANE, ORANGE_TERRACOTTA, ORANGE_TULIP, ORANGE_WOOL, OXEYE_DAISY, OXIDIZED_COPPER, OXIDIZED_CUT_COPPER, OXIDIZED_CUT_COPPER_SLAB, OXIDIZED_CUT_COPPER_STAIRS, PACKED_ICE, PACKED_MUD, PAINTING, PANDA_SPAWN_EGG, PAPER, PARROT_SPAWN_EGG, PEARLESCENT_FROGLIGHT, PEONY, PETRIFIED_OAK_SLAB, PHANTOM_MEMBRANE, PHANTOM_SPAWN_EGG, PIG_SPAWN_EGG, PIGLIN_BANNER_PATTERN, PIGLIN_BRUTE_SPAWN_EGG, PIGLIN_HEAD, PIGLIN_SPAWN_EGG, PILLAGER_SPAWN_EGG, PINK_BANNER, PINK_BED, PINK_CANDLE, PINK_CARPET, PINK_CONCRETE, PINK_CONCRETE_POWDER, PINK_DYE, PINK_GLAZED_TERRACOTTA, PINK_PETALS, PINK_SHULKER_BOX, PINK_STAINED_GLASS, PINK_STAINED_GLASS_PANE, PINK_TERRACOTTA, PINK_TULIP, PINK_WOOL, PISTON, PITCHER_PLANT, PITCHER_POD, PLAYER_HEAD, PLENTY_POTTERY_SHERD, PODZOL, POINTED_DRIPSTONE, POISONOUS_POTATO, POLAR_BEAR_SPAWN_EGG, POLISHED_ANDESITE, POLISHED_ANDESITE_SLAB, POLISHED_ANDESITE_STAIRS, POLISHED_BASALT, POLISHED_BLACKSTONE, POLISHED_BLACKSTONE_BRICK_SLAB, POLISHED_BLACKSTONE_BRICK_STAIRS, POLISHED_BLACKSTONE_BRICK_WALL, POLISHED_BLACKSTONE_BRICKS, POLISHED_BLACKSTONE_BUTTON, POLISHED_BLACKSTONE_PRESSURE_PLATE, POLISHED_BLACKSTONE_SLAB, POLISHED_BLACKSTONE_STAIRS, POLISHED_BLACKSTONE_WALL, POLISHED_DEEPSLATE, POLISHED_DEEPSLATE_SLAB, POLISHED_DEEPSLATE_STAIRS, POLISHED_DEEPSLATE_WALL, POLISHED_DIORITE, POLISHED_DIORITE_SLAB, POLISHED_DIORITE_STAIRS, POLISHED_GRANITE, POLISHED_GRANITE_SLAB, POLISHED_GRANITE_STAIRS, POPPED_CHORUS_FRUIT, POPPY, PORKCHOP, POTATO, POTION, POTTED_ACACIA_SAPLING, POTTED_ALLIUM, POTTED_AZALEA_BUSH, POTTED_AZURE_BLUET, POTTED_BAMBOO, POTTED_BIRCH_SAPLING, POTTED_BLUE_ORCHID, POTTED_BROWN_MUSHROOM, POTTED_CACTUS, POTTED_CORNFLOWER, POTTED_CRIMSON_FUNGUS, POTTED_CRIMSON_ROOTS, POTTED_DANDELION, POTTED_DARK_OAK_SAPLING, POTTED_DEAD_BUSH, POTTED_FERN, POTTED_FLOWERING_AZALEA_BUSH, POTTED_JUNGLE_SAPLING, POTTED_LILY_OF_THE_VALLEY, POTTED_MANGROVE_PROPAGULE, POTTED_OAK_SAPLING, POTTED_ORANGE_TULIP, POTTED_OXEYE_DAISY, POTTED_PINK_TULIP, POTTED_POPPY, POTTED_RED_MUSHROOM, POTTED_RED_TULIP, POTTED_SPRUCE_SAPLING, POTTED_WARPED_FUNGUS, POTTED_WARPED_ROOTS, POTTED_WHITE_TULIP, POTTED_WITHER_ROSE, POTTERY_SHARD_ARCHER, POTTERY_SHARD_ARMS_UP, POTTERY_SHARD_PRIZE, POTTERY_SHARD_SKULL, POWDER_SNOW_BUCKET, POWERED_RAIL, PRISMARINE, PRISMARINE_BRICK_SLAB, PRISMARINE_BRICK_STAIRS, PRISMARINE_BRICKS, PRISMARINE_CRYSTALS, PRISMARINE_SHARD, PRISMARINE_SLAB, PRISMARINE_STAIRS, PRISMARINE_WALL, PRIZE_POTTERY_SHERD, PUFFERFISH, PUFFERFISH_BUCKET, PUFFERFISH_SPAWN_EGG, PUMPKIN, PUMPKIN_PIE, PUMPKIN_SEEDS, PURPLE_BANNER, PURPLE_BED, PURPLE_CANDLE, PURPLE_CARPET, PURPLE_CONCRETE, PURPLE_CONCRETE_POWDER, PURPLE_DYE, PURPLE_GLAZED_TERRACOTTA, PURPLE_SHULKER_BOX, PURPLE_STAINED_GLASS, PURPLE_STAINED_GLASS_PANE, PURPLE_TERRACOTTA, PURPLE_WOOL, PURPUR_BLOCK, PURPUR_PILLAR, PURPUR_SLAB, PURPUR_STAIRS, QUARTZ, QUARTZ_BLOCK, QUARTZ_BRICKS, QUARTZ_PILLAR, QUARTZ_SLAB, QUARTZ_STAIRS, RABBIT, RABBIT_FOOT, RABBIT_HIDE, RABBIT_SPAWN_EGG, RABBIT_STEW, RAIL, RAISER_ARMOR_TRIM_SMITHING_TEMPLATE, RAVAGER_SPAWN_EGG, RAW_COPPER, RAW_COPPER_BLOCK, RAW_GOLD, RAW_GOLD_BLOCK, RAW_IRON, RAW_IRON_BLOCK, RECOVERY_COMPASS, RED_BANNER, RED_BED, RED_CANDLE, RED_CARPET, RED_CONCRETE, RED_CONCRETE_POWDER, RED_DYE, RED_GLAZED_TERRACOTTA, RED_MUSHROOM, RED_MUSHROOM_BLOCK, RED_NETHER_BRICK_SLAB, RED_NETHER_BRICK_STAIRS, RED_NETHER_BRICK_WALL, RED_NETHER_BRICKS, RED_SAND, RED_SANDSTONE, RED_SANDSTONE_SLAB, RED_SANDSTONE_STAIRS, RED_SANDSTONE_WALL, RED_SHULKER_BOX, RED_STAINED_GLASS, RED_STAINED_GLASS_PANE, RED_TERRACOTTA, RED_TULIP, RED_WOOL, REDSTONE, REDSTONE_BLOCK, REDSTONE_LAMP, REDSTONE_ORE, REDSTONE_TORCH, REINFORCED_DEEPSLATE, REPEATER, REPEATING_COMMAND_BLOCK, RESPAWN_ANCHOR, RIB_ARMOR_TRIM_SMITHING_TEMPLATE, ROOTED_DIRT, ROSE_BUSH, ROTTEN_FLESH, SADDLE, SALMON, SALMON_BUCKET, SALMON_SPAWN_EGG, SAND, SANDSTONE, SANDSTONE_SLAB, SANDSTONE_STAIRS, SANDSTONE_WALL, SCAFFOLDING, SCULK, SCULK_CATALYST, SCULK_SENSOR, SCULK_SHRIEKER, SCULK_VEIN, TURTLE_SCUTE, SEA_LANTERN, SEA_PICKLE, SEAGRASS, SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE, SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE, SHEAF_POTTERY_SHERD, SHEARS, SHEEP_SPAWN_EGG, SHELTER_POTTERY_SHERD, SHIELD, SHROOMLIGHT, SHULKER_BOX, SHULKER_SHELL, SHULKER_SPAWN_EGG, SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE, SILVERFISH_SPAWN_EGG, SKELETON_HORSE_SPAWN_EGG, SKELETON_SKULL, SKELETON_SPAWN_EGG, SKULL_BANNER_PATTERN, SKULL_POTTERY_SHERD, SLIME_BALL, SLIME_BLOCK, SLIME_SPAWN_EGG, SMALL_AMETHYST_BUD, SMALL_DRIPLEAF, SMITHING_TABLE, SMOKER, SMOOTH_BASALT, SMOOTH_QUARTZ, SMOOTH_QUARTZ_SLAB, SMOOTH_QUARTZ_STAIRS, SMOOTH_RED_SANDSTONE, SMOOTH_RED_SANDSTONE_SLAB, SMOOTH_RED_SANDSTONE_STAIRS, SMOOTH_SANDSTONE, SMOOTH_SANDSTONE_SLAB, SMOOTH_SANDSTONE_STAIRS, SMOOTH_STONE, SMOOTH_STONE_SLAB, SNIFFER_EGG, SNIFFER_SPAWN_EGG, SNORT_POTTERY_SHERD, SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE, SNOW, SNOW_BLOCK, SNOW_GOLEM_SPAWN_EGG, SNOWBALL, SOUL_CAMPFIRE, SOUL_LANTERN, SOUL_SAND, SOUL_SOIL, SOUL_TORCH, SPAWNER, SPECTRAL_ARROW, SPIDER_EYE, SPIDER_SPAWN_EGG, SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE, SPLASH_POTION, SPONGE, SPORE_BLOSSOM, SPRUCE_BOAT, SPRUCE_BUTTON, SPRUCE_CHEST_BOAT, SPRUCE_DOOR, SPRUCE_FENCE, SPRUCE_FENCE_GATE, SPRUCE_HANGING_SIGN, SPRUCE_LEAVES, SPRUCE_LOG, SPRUCE_PLANKS, SPRUCE_PRESSURE_PLATE, SPRUCE_SAPLING, SPRUCE_SIGN, SPRUCE_SLAB, SPRUCE_STAIRS, SPRUCE_TRAPDOOR, SPRUCE_WOOD, SPYGLASS, SQUID_SPAWN_EGG, STICK, STICKY_PISTON, STONE, STONE_AXE, STONE_BRICK_SLAB, STONE_BRICK_STAIRS, STONE_BRICK_WALL, STONE_BRICKS, STONE_BUTTON, STONE_HOE, STONE_PICKAXE, STONE_PRESSURE_PLATE, STONE_SHOVEL, STONE_SLAB, STONE_STAIRS, STONE_SWORD, STONECUTTER, STRAY_SPAWN_EGG, STRIDER_SPAWN_EGG, STRING, STRIPPED_ACACIA_LOG, STRIPPED_ACACIA_WOOD, STRIPPED_BAMBOO_BLOCK, STRIPPED_BIRCH_LOG, STRIPPED_BIRCH_WOOD, STRIPPED_CHERRY_LOG, STRIPPED_CHERRY_WOOD, STRIPPED_CRIMSON_HYPHAE, STRIPPED_CRIMSON_STEM, STRIPPED_DARK_OAK_LOG, STRIPPED_DARK_OAK_WOOD, STRIPPED_JUNGLE_LOG, STRIPPED_JUNGLE_WOOD, STRIPPED_MANGROVE_LOG, STRIPPED_MANGROVE_WOOD, STRIPPED_OAK_LOG, STRIPPED_OAK_WOOD, STRIPPED_SPRUCE_LOG, STRIPPED_SPRUCE_WOOD, STRIPPED_WARPED_HYPHAE, STRIPPED_WARPED_STEM, STRUCTURE_BLOCK, STRUCTURE_VOID, SUGAR, SUGAR_CANE, SUNFLOWER, SUSPICIOUS_GRAVEL, SUSPICIOUS_SAND, SUSPICIOUS_STEW, SWEET_BERRIES, TADPOLE_BUCKET, TADPOLE_SPAWN_EGG, TALL_GRASS, TARGET, TERRACOTTA, TIDE_ARMOR_TRIM_SMITHING_TEMPLATE, TINTED_GLASS, TIPPED_ARROW, TNT, TNT_MINECART, TORCH, TORCHFLOWER, TORCHFLOWER_SEEDS, TOTEM_OF_UNDYING, TRADER_LLAMA_SPAWN_EGG, TRAPPED_CHEST, TRIDENT, TRIPWIRE_HOOK, TROPICAL_FISH, TROPICAL_FISH_BUCKET, TROPICAL_FISH_SPAWN_EGG, TUBE_CORAL, TUBE_CORAL_BLOCK, TUBE_CORAL_FAN, TUFF, TURTLE_EGG, TURTLE_HELMET, TURTLE_SPAWN_EGG, TWISTING_VINES, VERDANT_FROGLIGHT, VEX_ARMOR_TRIM_SMITHING_TEMPLATE, VEX_SPAWN_EGG, VILLAGER_SPAWN_EGG, VINDICATOR_SPAWN_EGG, VINE, WANDERING_TRADER_SPAWN_EGG, WARD_ARMOR_TRIM_SMITHING_TEMPLATE, WARDEN_SPAWN_EGG, WARPED_BUTTON, WARPED_DOOR, WARPED_FENCE, WARPED_FENCE_GATE, WARPED_FUNGUS, WARPED_FUNGUS_ON_A_STICK, WARPED_HANGING_SIGN, WARPED_HYPHAE, WARPED_NYLIUM, WARPED_PLANKS, WARPED_PRESSURE_PLATE, WARPED_ROOTS, WARPED_SIGN, WARPED_SLAB, WARPED_STAIRS, WARPED_STEM, WARPED_TRAPDOOR, WARPED_WART_BLOCK, WATER_BUCKET, WAXED_COPPER_BLOCK, WAXED_CUT_COPPER, WAXED_CUT_COPPER_SLAB, WAXED_CUT_COPPER_STAIRS, WAXED_EXPOSED_COPPER, WAXED_EXPOSED_CUT_COPPER, WAXED_EXPOSED_CUT_COPPER_SLAB, WAXED_EXPOSED_CUT_COPPER_STAIRS, WAXED_OXIDIZED_COPPER, WAXED_OXIDIZED_CUT_COPPER, WAXED_OXIDIZED_CUT_COPPER_SLAB, WAXED_OXIDIZED_CUT_COPPER_STAIRS, WAXED_WEATHERED_COPPER, WAXED_WEATHERED_CUT_COPPER, WAXED_WEATHERED_CUT_COPPER_SLAB, WAXED_WEATHERED_CUT_COPPER_STAIRS, WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE, WEATHERED_COPPER, WEATHERED_CUT_COPPER, WEATHERED_CUT_COPPER_SLAB, WEATHERED_CUT_COPPER_STAIRS, WEEPING_VINES, WET_SPONGE, WHEAT, WHEAT_SEEDS, WHITE_BANNER, WHITE_BED, WHITE_CANDLE, WHITE_CARPET, WHITE_CONCRETE, WHITE_CONCRETE_POWDER, WHITE_DYE, WHITE_GLAZED_TERRACOTTA, WHITE_SHULKER_BOX, WHITE_STAINED_GLASS, WHITE_STAINED_GLASS_PANE, WHITE_TERRACOTTA, WHITE_TULIP, WHITE_WOOL, WILD_ARMOR_TRIM_SMITHING_TEMPLATE, WITCH_SPAWN_EGG, WITHER_ROSE, WITHER_SKELETON_SKULL, WITHER_SKELETON_SPAWN_EGG, WITHER_SPAWN_EGG, WOLF_SPAWN_EGG, WOODEN_AXE, WOODEN_HOE, WOODEN_PICKAXE, WOODEN_SHOVEL, WOODEN_SWORD, WRITABLE_BOOK, WRITTEN_BOOK, YELLOW_BANNER, YELLOW_BED, YELLOW_CANDLE, YELLOW_CARPET, YELLOW_CONCRETE, YELLOW_CONCRETE_POWDER, YELLOW_DYE, YELLOW_GLAZED_TERRACOTTA, YELLOW_SHULKER_BOX, YELLOW_STAINED_GLASS, YELLOW_STAINED_GLASS_PANE, YELLOW_TERRACOTTA, YELLOW_WOOL, ZOGLIN_SPAWN_EGG, ZOMBIE_HEAD, ZOMBIE_HORSE_SPAWN_EGG, ZOMBIE_SPAWN_EGG, ZOMBIE_VILLAGER_SPAWN_EGG, ZOMBIFIED_PIGLIN_SPAWN_EGG, DEBUG_STICK};
   }

   static {
      XMaterial[] var0 = VALUES;
      int var1 = var0.length;

      for(int var2 = 0; var2 < var1; ++var2) {
         XMaterial material = var0[var2];
         NAMES.put(material.name(), material);
      }

      if (XMaterial.Data.ISFLAT) {
         DUPLICATED = null;
      } else {
         DUPLICATED = new HashSet(4);
         DUPLICATED.add(SHORT_GRASS.name());
         DUPLICATED.add(MELON.name());
         DUPLICATED.add(BRICK.name());
         DUPLICATED.add(NETHER_BRICK.name());
      }

   }

   private static final class Data {
      private static final int VERSION = Integer.parseInt(XMaterial.getMajorVersion(Bukkit.getVersion()).substring(2));
      private static final boolean ISFLAT = XMaterial.supports(13);
   }
}
