package ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.packettype.config.clientbound;

public enum ClientboundConfigPacketType_1_21_6 {
   COOKIE_REQUEST,
   PLUGIN_MESSAGE,
   DISCONNECT,
   CONFIGURATION_END,
   KEEP_ALIVE,
   PING,
   RESET_CHAT,
   REGISTRY_DATA,
   RESOURCE_PACK_REMOVE,
   RESOURCE_PACK_SEND,
   STORE_COOKIE,
   TRANSFER,
   UPDATE_ENABLED_FEATURES,
   UPDATE_TAGS,
   SELECT_KNOWN_PACKS,
   CUSTOM_REPORT_DETAILS,
   SERVER_LINKS,
   CLEAR_DIALOG,
   SHOW_DIALOG;

   // $FF: synthetic method
   private static ClientboundConfigPacketType_1_21_6[] $values() {
      return new ClientboundConfigPacketType_1_21_6[]{COOKIE_REQUEST, PLUGIN_MESSAGE, DISCONNECT, CONFIGURATION_END, KEEP_ALIVE, PING, RESET_CHAT, REGISTRY_DATA, RESOURCE_PACK_REMOVE, RESOURCE_PACK_SEND, STORE_COOKIE, TRANSFER, UPDATE_ENABLED_FEATURES, UPDATE_TAGS, SELECT_KNOWN_PACKS, CUSTOM_REPORT_DETAILS, SERVER_LINKS, CLEAR_DIALOG, SHOW_DIALOG};
   }
}
